acquisitions/src/main/resources/domain/mod-invoice/invoice.feature, acquisitions/src/main/resources/domain/mod-invoice/scenario/prorated-adjustments-special-cases.feature, acquisitions/src/test/java/org/folio/InvoicesApiTest.java
Verified on testing by running
`mvn test -DargLine="-Dkarate.env=testing" -Dtest=InvoicesApiTest -pl acquisitions`
=> MODINVOICE-59 Prorated adjustments part 2 - validation/special cases

acquisitions/src/main/resources/domain/mod-invoice/invoice.feature, acquisitions/src/main/resources/domain/mod-invoice/scenario/check-remaining-amount-upon-invoice-approval.feature
=> [MODINVOICE-114] Check remaining amount expendable upon invoice approval

acquisitions/src/main/resources/domain/mod-finance/features/budget-expense-classes.feature, acquisitions/src/main/resources/domain/mod-finance/features/update-encumbrance-transactions.feature, acquisitions/src/main/resources/domain/mod-finance/finance.feature, acquisitions/src/main/resources/domain/mod-finance/reusable/createTransaction.feature, acquisitions/src/main/resources/karate-config.js
[MODFIN-136](https://issues.folio.org/browse/MODFIN-136)
Folio-testing:
=> MODFIN-136 Define and implement GET /finance/budgets/id/expense-classes-totals API

common/src/main/resources/common/tenant.feature, gulfstream/pom.xml, gulfstream/src/test/java/org/folio/GulfstreamTestsRunner.java, gulfstream/src/test/resources/domain/mod-configuration/delete_config_by_id.feature, gulfstream/src/test/resources/domain/mod-configuration/get_oaipmh_configs.feature, gulfstream/src/test/resources/domain/mod-configuration/mod-configuration.feature, gulfstream/src/test/resources/domain/oaipmh/features/oaipmh-basic.feature, gulfstream/src/test/resources/domain/oaipmh/features/oaipmh-enhancement.feature, gulfstream/src/test/resources/domain/oaipmh/oaipmh.feature, gulfstream/src/test/resources/global/add-okapi-permissions.feature, gulfstream/src/test/resources/global/init_data/mod_configuration_init_data.feature, gulfstream/src/test/resources/global/init_data/mod_inventory_init_data.feature, gulfstream/src/test/resources/global/init_data/postRecord.feature, gulfstream/src/test/resources/global/init_data/postToInventory.feature, gulfstream/src/test/resources/global/init_data/srs_init_data.feature, gulfstream/src/test/resources/global/module-utils.feature, gulfstream/src/test/resources/karate-config.js, gulfstream/src/test/resources/logback-test.xml, gulfstream/src/test/resources/samples/holding.json, gulfstream/src/test/resources/samples/instance.json, gulfstream/src/test/resources/samples/item.json, gulfstream/src/test/resources/samples/marc_record.json, pom.xml, runtests.sh
Integration tests for OAI-PMH based on http://www.openarchives.org/Register/ValidateSite
=> MODOAIPMH-142: Integration tests for OAI-PMH

common/src/main/resources/common/module.feature, common/src/main/resources/common/tenant.feature
Get modules enabled for admin user and then install them in new test tenant
=> In new test tenant install modules enabled in diku modules

acquisitions/src/main/resources/domain/cross-modules/cross-modules.feature, acquisitions/src/main/resources/domain/cross-modules/features/create-order-with-invoice-that-has-enough-money.feature, acquisitions/src/main/resources/domain/mod-finance/reusable/createBudget.feature, acquisitions/src/main/resources/domain/mod-orders/features/create-order-that-has-not-enough-money.feature, acquisitions/src/main/resources/global/configuration.feature, acquisitions/src/main/resources/global/finances.feature, acquisitions/src/main/resources/global/variables.feature, acquisitions/src/test/java/org/folio/CrossModulesApiTest.java, common/src/main/resources/common/module.feature
=> [MODFISTO-125] Api tests

gulfstream/src/test/resources/common/destroy-data.feature, gulfstream/src/test/resources/common/module.feature, gulfstream/src/test/resources/domain/mod-configuration/mod-configuration.feature, gulfstream/src/test/resources/karate-config.js
=> Copy common files

.rancher-pipeline.yml, README.md, runtests.sh
* Setup a general purpose rancher pipeline and add docs how to run integration tests for a specific project and environment
=> MODOAIPMH-209: Rancher integration

mod-oai-pmh/pom.xml, mod-oai-pmh/src/test/java/com/gurock/testrail/APIClient.java, mod-oai-pmh/src/test/java/com/gurock/testrail/APIException.java, mod-oai-pmh/src/test/java/org/folio/ModOaiPmhTests.java, mod-oai-pmh/src/test/java/org/folio/TestRailStatus.java, mod-oai-pmh/src/test/java/org/folio/TestRailUtilsNew.java, mod-oai-pmh/src/test/resources/domain/oaipmh/oaipmh-basic.feature
Integrate mod-oai-pmh basic tests with testrail
=> MODOAIPMH-195: Test rail integration #1

mod-oai-pmh/src/test/java/org/folio/ModOaiPmhTests.java
Connect mod-oai-pmh features with testrail
=> Connect mod-oai-pmh features with testrail

acquisitions/src/main/resources/domain/mod-finance/features/budget-update.feature, acquisitions/src/main/resources/domain/mod-finance/finance.feature
https://issues.folio.org/browse/MODFIN-147
Verified on folio-testing:
=> MODFIN-147 Budget allocation calculation out of sync with transaction log

acquisitions/src/main/resources/domain/mod-finance/features/current-budget-for-fund.feature, acquisitions/src/main/resources/domain/mod-finance/finance.feature
=> [MODFIN-146] Adding API tests for current budget for fund

acquisitions/src/main/resources/domain/mod-finance/features/budget-transfer-transactions.feature, acquisitions/src/main/resources/domain/mod-finance/finance.feature, acquisitions/src/main/resources/domain/mod-finance/reusable/createLedger.feature, acquisitions/src/main/resources/karate-config.js
=> [MODFISTO-103] Add tests for verification of transfer transactions

quick-marc/src/main/resources/domain/mod-quick-marc/scenario/test-quick-marc.feature
[MODQM-31](https://issues.folio.org/browse/MODQM-31) - mod-quick-marc: RMB Update
* fixed test condition
Verified on [folio-testing](https://folio-testing-okapi.dev.folio.org:443):
=> MODQM-31 - mod-quick-marc: RMB Update

acquisitions/src/main/resources/domain/mod-invoice/features/check-remaining-amount-upon-invoice-approval.feature
=> [MODINVOICE-188] Update tests with adjustments

acquisitions/src/main/resources/domain/mod-finance/features/transaction-summaries-crud.feature, acquisitions/src/main/resources/domain/mod-finance/finance.feature
https://issues.folio.org/browse/MODFIN-153
Verified on folio testing
=> MODFIN-153 added transaction-summaries-crud.feature

acquisitions/src/main/resources/domain/mod-invoice/features/exchange-rate-update-after-invoice-approval.feature, acquisitions/src/main/resources/domain/mod-invoice/invoice.feature
https://issues.folio.org/browse/MODINVOICE-181
Local run:
=> MODINVOICE-181 Update Pending payments when exchange rate is edited

acquisitions/src/main/resources/domain/mod-orders/orders.feature
https://issues.folio.org/browse/MODORDERS-420
=> MODORDERS-420 uncomment expense class test

acquisitions/src/main/resources/domain/cross-modules/cross-modules.feature, acquisitions/src/main/resources/domain/cross-modules/features/order-invoice-relation.feature, common/src/main/resources/common/dev.feature
=> [MODINVOICE-148] Add integration test for order invoice relation

acquisitions/pom.xml, acquisitions/src/main/resources/domain/cross-modules/cross-modules-junit.feature, acquisitions/src/main/resources/domain/cross-modules/cross-modules.feature, acquisitions/src/main/resources/domain/mod-finance/features/create-planned-budget-without-expense-classes-when-there-is-no-current-budget.feature, acquisitions/src/main/resources/domain/mod-finance/features/when-creating-budget-add-expense-classes-from-previous-budget-automatically.feature, acquisitions/src/main/resources/domain/mod-finance/features/when-creating-budget-add-expense-classes-if-them-provided-by-user.feature, acquisitions/src/main/resources/domain/mod-finance/finance-junit.feature, acquisitions/src/main/resources/domain/mod-finance/finance.feature, acquisitions/src/main/resources/domain/mod-invoice/features/check-invoice-and-invoice-lines-deletion-restrictions.feature, acquisitions/src/main/resources/domain/mod-invoice/invoice-junit.feature, acquisitions/src/main/resources/domain/mod-invoice/invoice.feature, acquisitions/src/main/resources/domain/mod-orders/features/encumbrance-tags-inheritance.feature, acquisitions/src/main/resources/domain/mod-orders/orders-junit.feature, acquisitions/src/main/resources/domain/mod-orders/orders.feature, acquisitions/src/main/resources/karate-config.js, acquisitions/src/main/resources/logback-test.xml, acquisitions/src/test/java/com/gurock/testrail/APIClient.java, acquisitions/src/test/java/com/gurock/testrail/APIException.java, acquisitions/src/test/java/org/folio/CrossModulesApiTest.java, acquisitions/src/test/java/org/folio/FinanceApiTest.java, acquisitions/src/test/java/org/folio/InvoicesApiTest.java, acquisitions/src/test/java/org/folio/OrdersApiTest.java, acquisitions/src/test/java/org/folio/TestUtils.java, acquisitions/src/test/java/org/folio/testrail/AbstractTestRailIntegrationTest.java, acquisitions/src/test/java/org/folio/testrail/TestConfigurationConstants.java, acquisitions/src/test/java/org/folio/testrail/TestConfigurationEnum.java, acquisitions/src/test/java/org/folio/testrail/TestRailIntegrationHelper.java, acquisitions/src/test/java/org/folio/testrail/TestRailStatus.java, acquisitions/src/test/java/org/folio/testrail/TestRailUtilsNew.java, common/src/main/resources/common/shared-callable.feature
Initial integration with TestRails.
https://issues.folio.org/browse/FAT-5
=> FAT-5: Integrate existing Karate tests with TestRail

acquisitions/src/test/java/com/gurock/testrail/api/ApiEntry.java, acquisitions/src/test/java/com/gurock/testrail/api/ApiEntryHolder.java, acquisitions/src/test/java/com/gurock/testrail/api/CasesApiEntry.java, acquisitions/src/test/java/com/gurock/testrail/api/ResultsApiEntry.java, acquisitions/src/test/java/com/gurock/testrail/api/RunsApiEntry.java, acquisitions/src/test/java/com/gurock/testrail/api/TestRailsApiEntries.java, acquisitions/src/test/java/com/gurock/testrail/api/TestsApiEntry.java, acquisitions/src/test/java/org/folio/CrossModulesApiTest.java, acquisitions/src/test/java/org/folio/FinanceApiTest.java, acquisitions/src/test/java/org/folio/InvoicesApiTest.java, acquisitions/src/test/java/org/folio/OrdersApiTest.java, acquisitions/src/test/java/org/folio/testrail/AbstractTestRailIntegrationTest.java, acquisitions/src/test/java/org/folio/testrail/TestRailIntegrationHelper.java, acquisitions/src/test/java/org/folio/testrail/config/TestConfigurationConstants.java, acquisitions/src/test/java/org/folio/testrail/config/TestConfigurationEnum.java, pom.xml
Added hotfix implementation integration karate tests with TestRais.
According to the closed ticket - https://issues.folio.org/browse/FAT-5
=> Hotfix implementation of Acquisitions modules integration with TestRails.

mod-data-export/pom.xml, mod-data-export/src/test/java/org/folio/ModDataExport.java, mod-data-export/src/test/java/org/folio/TestRailStatus.java, mod-data-export/src/test/java/org/folio/TestRailUtilsNew.java, mod-data-export/src/test/java/testrail/APIClient.java, mod-data-export/src/test/java/testrail/APIException.java, mod-data-export/src/test/resources/common/destroy-data.feature, mod-data-export/src/test/resources/common/dev.feature, mod-data-export/src/test/resources/common/login.feature, mod-data-export/src/test/resources/common/module.feature, mod-data-export/src/test/resources/common/setup-users.feature, mod-data-export/src/test/resources/common/tenant.feature, mod-data-export/src/test/resources/domain/dataexport/data-export-basic.feature, mod-data-export/src/test/resources/global/add-okapi-permissions.feature, mod-data-export/src/test/resources/karate-config.js, mod-data-export/src/test/resources/logback-test.xml, mod-data-export/src/test/resources/samples/holding.json, mod-data-export/src/test/resources/samples/instance.json, mod-data-export/src/test/resources/samples/item.json, mod-data-export/src/test/resources/samples/marc_record.json, pom.xml
https://issues.folio.org/browse/FAT-127
Create a base for karate tests for data-export. PR contains creating of the new module, infrastructure changes for karate tests, and basic test to get the default mapping profile.
=> FAT-127 Create a base karate tests for mod-data-export

acquisitions/src/main/resources/domain/mod-finance/features/ledger-totals.feature
=> MODFISTO-181 Move allocated logic from trigger to java code

acquisitions/src/main/resources/domain/mod-finance/features/ledger-fiscal-year-rollover.feature, acquisitions/src/main/resources/domain/mod-finance/finance-junit.feature, acquisitions/src/main/resources/domain/mod-finance/finance.feature
Updated rollover feature to check order lines after rollover
=> MODORDERS-464 Implement rollover orders logic

acquisitions/src/main/resources/domain/mod-finance/features/ledger-totals.feature, acquisitions/src/main/resources/global/finances.feature
https://issues.folio.org/browse/MODFIN-168
=> MODFIN-168 Update logic with financial detail in the Ledger summary to improve the users ability to manage financial activity

acquisitions/src/main/resources/domain/mod-finance/features/budget-update.feature
https://issues.folio.org/browse/MODFIN-175
Before merging this PR, please go through the following list and take appropriate actions.
- Does this PR meet or exceed the expected quality standards?
- Does this introduce breaking changes?
If there are breaking changes, please **STOP** and consider the following:
- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
- Are the JIRAs under active development?  
- Do PRs exist for these changes?
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.  
While it's helpful for reviewers to help …
=> [MODFIN-175] Correct tests for Support PUT for the Budget feature

acquisitions/src/main/resources/domain/mod-finance/features/group-fiscal-year-totals.feature, acquisitions/src/main/resources/domain/mod-finance/finance.feature, acquisitions/src/main/resources/global/finances.feature, acquisitions/src/test/java/org/folio/FinanceApiTest.java
https://issues.folio.org/browse/MODFIN-173
=> MODFIN-173 Update /finance/group-fiscal-year-summaries API to include more summary information

acquisitions/src/main/resources/domain/mod-finance/features/fiscal-year-totals.feature, acquisitions/src/main/resources/domain/mod-finance/features/ledger-fiscal-year-rollover.feature, acquisitions/src/main/resources/domain/mod-finance/finance.feature, acquisitions/src/main/resources/domain/mod-invoice/features/expense-classes-validation.feature, acquisitions/src/main/resources/karate-config.js, acquisitions/src/test/java/org/folio/FinanceApiTest.java
https://issues.folio.org/browse/MODFIN-170
=> MODFIN-170 Update business API for retrieving fiscal year by Id with financial summary

acquisitions/src/main/resources/domain/mod-finance/features/fiscal-year-totals.feature, acquisitions/src/main/resources/domain/mod-finance/features/group-fiscal-year-totals.feature, acquisitions/src/main/resources/domain/mod-finance/features/ledger-totals.feature
https://issues.folio.org/browse/MODFISTO-211
Verified on folio-testing:
=> MODFISTO-211 Incorrect budget overExpended value

acquisitions/src/main/resources/domain/mod-orders/features/check-order-re-encumber-api.feature, acquisitions/src/main/resources/domain/mod-orders/features/check-order-re-encumber-work-correctly.feature, acquisitions/src/main/resources/domain/mod-orders/orders.feature, acquisitions/src/test/java/org/folio/OrdersApiTest.java
https://issues.folio.org/browse/MODORDERS-439
Verified on folio-testing:
=> MODORDERS-439 Implement re-encumber orders logic

acquisitions/src/main/resources/domain/mod-finance/features/ledger-fiscal-year-rollover.feature, acquisitions/src/main/resources/karate-config.js, pom.xml
=> Modfisto 210

acquisitions/src/main/resources/domain/mod-orders/features/open-ongoing-order.feature, acquisitions/src/main/resources/domain/mod-orders/orders.feature, acquisitions/src/test/java/org/folio/OrdersApiTest.java
=> MODORDERS-459 add checks for ongoing order

acquisitions/src/main/resources/domain/mod-finance/features/ledger-fiscal-year-rollover.feature, acquisitions/src/main/resources/domain/mod-invoice/features/check-remaining-amount-upon-invoice-approval.feature, acquisitions/src/main/resources/domain/mod-invoice/features/create-voucher-lines-honor-expense-classes.feature, acquisitions/src/main/resources/domain/mod-invoice/features/exchange-rate-update-after-invoice-approval.feature, acquisitions/src/main/resources/domain/mod-invoice/features/expense-classes-validation.feature
* https://issues.folio.org/browse/MODINVOICE-222
adjust remaining amount checks
=> MODINVOICE-222 adjust remaining amount checks

acquisitions/src/main/resources/domain/mod-finance/features/allowable-encumbrance-and-expenditure-restrictions.feature, acquisitions/src/main/resources/domain/mod-finance/features/ledger-fiscal-year-rollover.feature, acquisitions/src/test/java/org/folio/FinanceApiTest.java
[MODFISTO-206](https://issues.folio.org/browse/MODFISTO-206)
Test allowable encumbrance and expenditure restrictions.
=> [MODFISTO-206] Test allowable encumbrance and expenditure restrictions

acquisitions/src/main/resources/domain/mod-finance/features/ledger-fiscal-year-rollover.feature
=> Modfisto 220

acquisitions/src/main/resources/domain/mod-orders/features/close-order-and-release-encumbrances.feature, acquisitions/src/main/resources/domain/mod-orders/orders.feature, acquisitions/src/test/java/org/folio/OrdersApiTest.java
=> MODORDERS-391 Release all encumbrances when order is closed Api test

acquisitions/src/main/resources/domain/mod-orders/features/check-new-tags-in-central-tag-repository.feature, acquisitions/src/main/resources/domain/mod-orders/features/increase-poline-quantity-for-open-order.feature, acquisitions/src/main/resources/domain/mod-orders/orders-junit.feature, acquisitions/src/main/resources/domain/mod-orders/orders.feature, acquisitions/src/test/java/org/folio/OrdersApiTest.java
=> MODORDERS-470 central tag repository check

acquisitions/src/main/resources/domain/mod-orders/features/create-order-that-has-not-enough-money.feature
[MODORDERS-471](https://issues.folio.org/browse/MODORDERS-471)
Added tests to `create-order-that-has-not-enough-money.feature` to check that open order will pass if and only if the budget has enough available money based on total funding (including netTransfers).
=> [MODORDERS-471] Make sure allowable encumbrance restriction is based on total funding

acquisitions/src/main/resources/domain/mod-finance/features/ledger-fiscal-year-rollover.feature
[MODFISTO-222](https://issues.folio.org/browse/MODFISTO-222)
=> MODFISTO-222 Budget created for inactive fund

acquisitions/src/main/resources/domain/mod-finance/features/ledger-fiscal-year-rollover.feature, acquisitions/src/main/resources/karate-config.js
MODORDERS-479
MODORDERS-479 Api teset for updated fd amount
=> MODORDERS-479 Api teset for updated fd amount

acquisitions/src/main/resources/domain/mod-finance/features/ledger-fiscal-year-rollover.feature
https://issues.folio.org/browse/MODFISTO-224
=> MODFISTO-224 Calculate transaction amount based on fundDistribution percentage value

acquisitions/src/main/resources/domain/mod-orders/features/check_total_encumbered_expended_calculated_correctly.feature, acquisitions/src/main/resources/domain/mod-orders/orders.feature, common/src/main/resources/common/setup-users.feature, mod-oai-pmh/src/test/resources/common/setup-users.feature
https://issues.folio.org/browse/MODORDERS-478
=> MODORDERS-478 Total encumbered for PO showing more than one year of encumbrances

mod-feesfines/pom.xml, mod-feesfines/src/main/resources/domain/mod-feesfines/features/owners.feature, mod-feesfines/src/main/resources/karate-config.js, mod-feesfines/src/main/resources/logback-test.xml, mod-feesfines/src/test/java/org/folio/OwnersApiTest.java, pom.xml
This PR is first attempt to create Karate tests for mod-feesfines. It features basic CRUD tests for Fee/fine Owners API.
Resolves [FAT-26](https://issues.folio.org/browse/FAT-26).
=> [FAT-26] Initial setup for mod-feesfines

acquisitions/src/main/resources/domain/mod-orders/features/check-order-re-encumber-work-correctly.feature, acquisitions/src/main/resources/domain/mod-orders/features/open-order-with-different-po-line-currency.feature, acquisitions/src/main/resources/domain/mod-orders/features/open-order-with-manual-exchange-rate.feature
https://issues.folio.org/browse/MODORDERS-482
=> MODORDERS-482 Cannot split funds on a PO with an odd number of pennies as the cost

acquisitions/src/main/resources/domain/mod-finance/features/ledger-fiscal-year-rollover.feature
=> MODFISTO-225 Missing penny tests

acquisitions/src/main/resources/domain/mod-ebsconet/ebsconet-junit.feature, acquisitions/src/main/resources/domain/mod-ebsconet/ebsconet.feature, acquisitions/src/main/resources/domain/mod-ebsconet/features/get-ebsconet-order-line.feature, acquisitions/src/test/java/org/folio/EbsconetApiTest.java
Created a new test suite for mod-ebsconet, including the GET feature. The new suite was also added to TestRail, along with a new section.
[MODEBSNET-3](https://issues.folio.org/browse/MODEBSNET-3)
=> [MODEBSNET-3] Added a new test suite for mod-ebsconet

acquisitions/src/main/resources/domain/mod-invoice/features/check-remaining-amount-upon-invoice-approval.feature, acquisitions/src/main/resources/domain/mod-invoice/features/should_populate_vendor_address_on_get_voucher_by_id.feature, acquisitions/src/main/resources/domain/mod-invoice/invoice.feature, acquisitions/src/test/java/org/folio/InvoicesApiTest.java
https://issues.folio.org/browse/MODINVOICE-241
=> MODINVOICE-241 Populate Vendor primary address on GET /voucher/vouchers/id

acquisitions/src/main/resources/domain/mod-ebsconet/ebsconet.feature, acquisitions/src/main/resources/domain/mod-ebsconet/features/update-ebsconet-order-line.feature, acquisitions/src/test/java/org/folio/EbsconetApiTest.java
=> MODEBSNET-4 add put ebsconet test

acquisitions/src/main/resources/domain/mod-invoice/features/check-approve-and-pay-invoice-with-odd-pennies-number.feature, acquisitions/src/main/resources/domain/mod-invoice/invoice.feature, acquisitions/src/test/java/org/folio/InvoicesApiTest.java
https://issues.folio.org/browse/MODINVOICE-232
* Created test for odd number of pennies
=> MODINVOICE-232 - split odd number of pennies

mod-patron-blocks/pom.xml, mod-patron-blocks/src/main/resources/domain/mod-patron-blocks/features/limits.feature, mod-patron-blocks/src/main/resources/karate-config.js, mod-patron-blocks/src/main/resources/logback-test.xml, mod-patron-blocks/src/test/java/org/folio/LimitsApiTest.java, mod-patron-blocks/src/test/java/org/folio/TestUtils.java, pom.xml
This PR is first attempt to create Karate tests for mod-patron-blocks. It features basic CRUD tests for limits API.
Resolves [FAT-167](https://issues.folio.org/browse/FAT-167)
=> FAT-167 Initial setup for mod-patron-blocks

acquisitions/src/main/resources/domain/mod-finance/features/unrelease-encumbrance.feature, acquisitions/src/main/resources/domain/mod-finance/finance.feature, acquisitions/src/test/java/org/folio/FinanceApiTest.java
[MODFISTO-233](https://issues.folio.org/browse/MODFISTO-233) reOpen logic for encumbrances
Added tests to unrelease the encumbrance.
=> [MODFISTO-233] Added tests to unrelease encumbrance

acquisitions/src/main/resources/domain/cross-modules/cross-modules-junit.feature, acquisitions/src/main/resources/domain/cross-modules/cross-modules.feature, acquisitions/src/main/resources/domain/cross-modules/features/create-order-and-invoice-with-odd-penny.feature, acquisitions/src/test/java/org/folio/CrossModulesApiTest.java
=> [MODINVOICE-255] Credit transaction is given value of $0

mod-patron-blocks/src/main/resources/domain/mod-patron-blocks/features/limits.feature
Use `testUser` for Limits API tests.
=> [FAT-198] fix mod-patron-blocks tests

mod-oai-pmh/src/test/resources/domain/oaipmh/oaipmh-enhancement.feature
Jira: https://issues.folio.org/browse/MODOAIPMH-325
Not all of the tests were run cause some of them were failed due to the bug [MODOAIPMH-327.]( https://issues.folio.org/browse/MODOAIPMH-327) In order to better verify the logic work, the tests were enriched with additional checks. The failed test structure was beautified a bit as well.
=> MODOAIPMH-325: Investigate why not all OAI-PMH Karate tests are executed

mod-event-config/pom.xml, mod-event-config/src/main/resources/domain/mod-event-config/event-config-junit.feature, mod-event-config/src/main/resources/domain/mod-event-config/features/eventConfig.feature, mod-event-config/src/main/resources/karate-config.js, mod-event-config/src/main/resources/logback-test.xml, mod-event-config/src/test/java/org/folio/ModEventConfigTests.java
Resolves [FAT-195](https://issues.folio.org/browse/FAT-195)
=> FAT-195 Set up karate tests for mod-event-config

mod-sender/pom.xml, mod-sender/src/main/resources/domain/mod-sender/features/sender.feature, mod-sender/src/main/resources/domain/mod-sender/sender-junit.feature, mod-sender/src/main/resources/karate-config.js, mod-sender/src/main/resources/logback-test.xml, mod-sender/src/test/java/org/folio/ModSenderTests.java
Resolves [FAT-196](https://issues.folio.org/browse/FAT-196)
=> FAT-196 Set up karate tests for mod-sender

mod-template-engine/pom.xml, mod-template-engine/src/main/resources/domain/mod-template-engine/features/templateEngine.feature, mod-template-engine/src/main/resources/domain/mod-template-engine/template-engine-junit.feature, mod-template-engine/src/main/resources/karate-config.js, mod-template-engine/src/main/resources/logback-test.xml, mod-template-engine/src/test/java/org/folio/ModTemplateEngineTests.java
Resolves [FAT-197](https://issues.folio.org/browse/FAT-197)
=> FAT-197 Set up karate tests for mod-template-engine

mod-calendar/pom.xml, mod-calendar/src/main/resources/domain/mod-calendar/calendar-junit.feature, mod-calendar/src/main/resources/domain/mod-calendar/features/openingHours.feature, mod-calendar/src/main/resources/karate-config.js, mod-calendar/src/main/resources/logback-test.xml, mod-calendar/src/test/java/org/folio/ModCalendarTests.java
Resolves [FAT-199](https://issues.folio.org/browse/FAT-199)
Set up Karate tests for mod-calendar
=> FAT-199 Set up Karate tests for mod-calendar

edge-caiasoft/pom.xml, edge-caiasoft/src/main/resources/domain/edge-caiasoft/features/return-should-change-item-status-to-available-when-no-hold-request-exists.feature, edge-caiasoft/src/main/resources/domain/edge-caiasoft/features/return-should-create-retrieval-queue-record-when-hold-request-exists.feature, edge-caiasoft/src/main/resources/global/variables.feature, edge-caiasoft/src/main/resources/karate-config.js, edge-caiasoft/src/main/resources/logback-test.xml, edge-caiasoft/src/test/java/org/folio/EdgeCaiasoftApiTest.java, pom.xml
[EDGCSOFT-6](https://issues.folio.org/browse/EDGCSOFT-6) - Returning an Item to remote storage
=> EDGCSOFT-6 - Returning an Item to remote storage

mod-user-import/pom.xml, mod-user-import/src/main/resources/domain/mod-user-import/features/userImport.feature, mod-user-import/src/main/resources/domain/mod-user-import/user-import-junit.feature, mod-user-import/src/main/resources/karate-config.js, mod-user-import/src/main/resources/logback-test.xml, mod-user-import/src/test/java/org/folio/ModUserImportTests.java, pom.xml
This is just for wiring up karate to mod-user-import. The actual tests will follow in FAT-170 and FAT-171.
=> FAT-159 Setting up karate tests for mod-user-import

mod-notify/src/main/resources/domain/mod-notify/features/notify.feature, mod-notify/src/main/resources/domain/mod-notify/features/patronNotice.feature, mod-notify/src/test/java/org/folio/ModNotifyTests.java
Test plan for mod-notify. Resolves [FAT-206](https://issues.folio.org/browse/FAT-206).
=> [FAT-206] test plan for mod-notify

mod-email/src/main/resources/domain/mod-email/features/delayedTasks.feature, mod-email/src/main/resources/domain/mod-email/features/email.feature, mod-email/src/test/java/org/folio/EmailApiTests.java
Resolves: [FAT-204](https://issues.folio.org/browse/FAT-204)
=> FAT-206 create test plan for mod-emails

edge-dematic/src/main/resources/domain/edge-dematic/features/lookup-asr-requests.feature, edge-dematic/src/main/resources/domain/edge-dematic/features/lookup-new-asr-items.feature, edge-dematic/src/main/resources/karate-config.js
[FAT-150](https://issues.folio.org/browse/FAT-150) - edge-dematic tests fail on Jenkins
Verified on folio-testing env:
=> FAT-150 - edge-dematic tests fail on Jenkins

mod-data-export/src/test/resources/domain/dataexport/features/export.feature, mod-data-export/src/test/resources/domain/dataexport/features/get-job-execution.feature, mod-data-export/src/test/resources/domain/dataexport/features/quick-export.feature, mod-data-export/src/test/resources/karate-config.js
Jira: https://issues.folio.org/browse/FAT-141
Cause the environment modules process files slower than locally it is required to give more time to the system for uploading a file.
=> FAT-141: Implement API Karate tests - PART 2 (improvments)

mod-audit/src/main/resources/domain/mod-audit/features/requestEvent.feature, mod-audit/src/main/resources/domain/mod-audit/mod-audit-junit.feature, mod-audit/src/main/resources/global/variables.feature, mod-audit/src/test/java/org/folio/ModAuditApiTest.java
[FAT-8](https://issues.folio.org/browse/FAT-8) - MODAUD: Implement API Karate tests
=> FAT-8 - Karate tests for mod-audit

quick-marc/src/main/resources/domain/mod-quick-marc/features/setup/setup.feature
Fix incorrect data type for job profile
changed data type from MARC_BIB to MARC
https://issues.folio.org/browse/MODQM-132
=> Analyse KARATE logs on the jenkins for mod-quick-marc

acquisitions/src/main/resources/domain/mod-finance/features/ledger-fiscal-year-rollover-MODFISTO-247.feature
[MODFISTO-247](https://issues.folio.org/browse/MODFISTO-247)
Check that 0-amount encumbrances can still be modified after rollover.
=> [MODFISTO-247] Added a test to change a 0 amount after rollover

mod-tags/pom.xml, mod-tags/src/test/java/org/folio/ModTagsApiTest.java, mod-tags/src/test/resources/domain/tags/basic-junit.feature, mod-tags/src/test/resources/domain/tags/features/tags.feature, mod-tags/src/test/resources/karate-config.js, mod-tags/src/test/resources/logback-test.xml, mod-tags/src/test/resources/samples/tag.json, pom.xml
Create module mod-tags and template for Karate tests
https://issues.folio.org/browse/FAT-903
=> mod-tags: Setup API Karate tests in the module

mod-tags/src/test/resources/domain/tags/features/tags.feature
Create test plan to cover functionality with API Karate test
https://issues.folio.org/browse/FAT-904
=> mod-tags: Create test plan to cover functionality with API Karate test

mod-password-validator/src/test/java/org.folio/ModPasswordValidatorApiTest.java, mod-password-validator/src/test/resources/domain/passwordvalidator/features/validate.feature
Adding undefined scenarios
https://issues.folio.org/browse/FAT-194
=> FAT-194 mod-password-validator: Created test plan

mod-tags/src/test/resources/domain/tags/features/tags.feature
Reverts folio-org/folio-integration-tests#225
=> Revert "mod-tags: Create test plan to cover functionality with API Karate test"

acquisitions/src/main/resources/domain/mod-finance/features/unopen-order-after-rollover-MODORDERS-542.feature, acquisitions/src/main/resources/domain/mod-finance/finance-junit.feature, acquisitions/src/main/resources/domain/mod-finance/finance.feature, acquisitions/src/test/java/org/folio/FinanceApiTest.java
=> MODORDERS-542 added tests

mod-email/src/main/resources/domain/mod-email/email-junit.feature, mod-email/src/main/resources/domain/mod-email/features/delayedTasks.feature, mod-email/src/main/resources/domain/mod-email/features/email.feature, mod-email/src/main/resources/domain/mod-email/features/samples/email-request-entity.json, mod-email/src/test/java/org/folio/EmailApiTests.java
https://issues.folio.org/browse/FAT-31
=> Fat 31 - tests for mod-email

mod-kb-ebsco-java/src/main/resources/domain/mod-kb-ebsco-java/features/titles.feature, mod-kb-ebsco-java/src/test/java/org/folio/KbEbscoApiTests.java
Create test plan to cover functionality with API Karate test
Undefined scenarios added and shown in Cucumber report
[**Titles**](https://s3.amazonaws.com/foliodocs/api/mod-kb-ebsco-java/titles.html)
[FAT-907](https://issues.folio.org/browse/FAT-907)
=> FAT-907 mod-kb-ebsco-java: Create test plan to cover functionality with API Karate test - Titles

mod-kb-ebsco-java/src/main/resources/domain/mod-kb-ebsco-java/features/providers.feature, mod-kb-ebsco-java/src/test/java/org/folio/KbEbscoApiTests.java
Create test plan to cover functionality with API Karate test
Undefined scenarios added and shown in Cucumber report
[**Providers**](https://s3.amazonaws.com/foliodocs/api/mod-kb-ebsco-java/providers.html#)
[FAT-905](https://issues.folio.org/browse/FAT-905)
=> FAT-905 mod-kb-ebsco-java: Create test plan to cover functionality with API Karate test - Providers

mod-data-export/src/test/resources/domain/dataexport/features/job-profiles.feature, mod-data-export/src/test/resources/domain/dataexport/features/mapping-profiles.feature
Correct the "match" statement when verifying the job's total records number.
=> FAT-938: fix job profile test

mod-audit/src/main/resources/domain/mod-audit/features/checkInCheckOutEvent.feature, mod-audit/src/main/resources/domain/mod-audit/features/loanEvent.feature, mod-audit/src/main/resources/domain/mod-audit/features/requestEvent.feature, mod-audit/src/main/resources/global/initTest.feature, mod-audit/src/main/resources/karate-config.js
[FAT-8](https://issues.folio.org/browse/FAT-8) - MODAUD: Implement API Karate tests
=> FAT-8 - MODAUD: Implement API Karate tests

data-import/src/main/resources/domain/data-import/data-import-junit.feature, data-import/src/main/resources/domain/data-import/features/get-completed-job-execution.feature
=> FAT-937/947: Retries improved.

mod-kb-ebsco-java/src/main/resources/domain/mod-kb-ebsco-java/features/user-assignment.feature, mod-kb-ebsco-java/src/test/java/org/folio/KbEbscoApiTests.java
Create test plan to cover functionality with API Karate test
Undefined scenarios added and shown in Cucumber report
[**User Assignment**](https://s3.amazonaws.com/foliodocs/api/mod-kb-ebsco-java/assigned-users.html#)
[FAT-911](https://issues.folio.org/browse/FAT-911)
=> FAT-911 mod-kb-ebsco-java: Create test plan to cover functionality with API Karate test - User Assignment

mod-kb-ebsco-java/src/main/resources/domain/mod-kb-ebsco-java/features/kb-credentials.feature, mod-kb-ebsco-java/src/main/resources/domain/mod-kb-ebsco-java/features/samples/user-assigment/createUser.json, mod-kb-ebsco-java/src/main/resources/domain/mod-kb-ebsco-java/features/samples/user-assigment/existUser.json, mod-kb-ebsco-java/src/main/resources/domain/mod-kb-ebsco-java/features/user-assignment.feature, mod-kb-ebsco-java/src/main/resources/karate-config.js
Added karate tests for kb-ebsco-java user-assigment
Implement tests
[FAT-980](https://issues.folio.org/browse/FAT-980)
[Assigned Users API](https://s3.amazonaws.com/foliodocs/api/mod-kb-ebsco-java/assigned-users.html#)
=> FAT-980: mod-kb-ebsco-java: Implement API Karate tests - User Assignment

acquisitions/src/main/resources/domain/mod-invoice/features/batch-voucher-export-with-many-lines.feature, acquisitions/src/main/resources/domain/mod-invoice/invoice.feature, acquisitions/src/test/java/org/folio/InvoicesApiTest.java
[MODINVOICE-312](https://issues.folio.org/browse/MODINVOICE-312)
Reproduced reported issue with 16 voucher lines.
=> [MODINVOICE-312] Test batch voucher export with many lines

acquisitions/src/main/resources/domain/mod-orders/features/MODORDERS-538-piece-against-non-package-mixed-pol-manual-piece-creation-is-false.feature
=> MODORDERS-538 fixed matcher

mod-inventory/src/main/resources/domain/mod-inventory/features/inventoryFeatureTest.feature, mod-inventory/src/main/resources/domain/mod-inventory/inventory-junit.feature
@steveellis :
Task:-Create Karate test for Inventory: When duplicating an existing holdings, then a new Holdings is created with a unique UUID and Holdings HRID (inv-5).
Here i don't think generating id by calling UUID function is good. kindly let me know if any suggestion.
=> * MODINV-512 to MODINV-518 -create Karate tests for MOD-INVENTORY.

mod-circulation/src/main/resources/domain/mod-circulation/features/loans.feature, mod-circulation/src/main/resources/domain/mod-circulation/features/util/initData.feature
[FAT-1004](https://issues.folio.org/browse/FAT-1004)
_When a loaned item is checked in at a service point that does not serve its location and no request exists, change the item status to In-transit and destination to primary service point for its location (circ-14)_
=> FAT-1004 - Created Karate test for Loans

mod-circulation/src/main/resources/domain/mod-circulation/circulation-junit.feature, mod-circulation/src/main/resources/domain/mod-circulation/features/loans.feature
Increase mod-circulation coverage by integration tests
Created karate test for Loans: When an item has the status of in process allow checkout
https://issues.folio.org/browse/FAT-1010
=> FAT-1010: When an item has the status of in process allow checkout 

mod-circulation/src/main/resources/domain/mod-circulation/features/loans.feature
[FAT-1005](https://issues.folio.org/browse/FAT-1005)
_When a loaned item is checked in at a service point that does not serve its location and a request exists, change the item status to In-transit and destination to pickup loaction in the request (circ-15)_
=> FAT-1005 Created Karate test for Loans

mod-circulation/src/main/resources/domain/mod-circulation/features/loans.feature
[FAT-1008](https://issues.folio.org/browse/FAT-1008)
_Create Karate test for Loans: When an item has the status of restricted, allow checkout with override (circ-18)_
=> FAT-1008 Createed Karate test for Loans

mod-circulation/src/main/resources/domain/mod-circulation/features/loans.feature
[FAT-1012](https://issues.folio.org/browse/FAT-1012)
_Create Karate test for Loans: When an item has the status of on order allow checkout_
=> FAT-1012 : When an item has the status of on order allow checkout

mod-circulation/src/main/resources/vega/mod-circulation/circulation-junit.feature, mod-circulation/src/main/resources/vega/mod-circulation/features/loans.feature, mod-circulation/src/main/resources/vega/mod-circulation/features/samples/feefine/manual-charge-entity-request.json, mod-circulation/src/main/resources/vega/mod-circulation/features/samples/feefine/owner-entity-request.json, mod-circulation/src/main/resources/vega/mod-circulation/features/samples/feefine/pay-entity-request.json, mod-circulation/src/main/resources/vega/mod-circulation/features/samples/feefine/payment-method-entity-request.json, mod-circulation/src/main/resources/vega/mod-circulation/features/util/get-time-now-function.js, mod-circulation/src/main/resources/vega/mod-circulation/features/util/initData.feature
[FAT-1017](https://issues.folio.org/browse/FAT-1017)
_Create Karate test for Loans: When an overdue item is returned, an overdue fine is billed per the Overdue Fine Policy_
=> FAT-1017: When an overdue item is returned, an overdue fine is billed per the Overdue Fine Policy

mod-circulation/src/main/resources/vega/mod-circulation/circulation-junit.feature, mod-circulation/src/main/resources/vega/mod-circulation/features/loans.feature, mod-circulation/src/main/resources/vega/mod-circulation/features/samples/claim-item-returned-entity-request.json, mod-circulation/src/main/resources/vega/mod-circulation/features/samples/feefine/refund-to-patron-entity-request.json, mod-circulation/src/main/resources/vega/mod-circulation/features/samples/update-account-entity-request.json, mod-circulation/src/main/resources/vega/mod-circulation/features/util/initData.feature
[FAT-999](https://issues.folio.org/browse/FAT-999)
_When an existing loan is claimed returned, update claimedReturnedDate, suspend any lost item fees billed and refund any lost item fees paid_
=> FAT-999: When an existing loan is claimed returned, update claimedReturnedDate, suspend any lost item fees billed and refund any lost item fees paid

acquisitions/src/main/resources/thunderjet/cross-modules/features/delete-encumbrance.feature
=> [MODORDERS-609] - Fix test

mod-notes/src/main/resources/spitfire/mod-notes/features/note-types.feature, mod-notes/src/main/resources/spitfire/mod-notes/features/setup/get-default-note-type.feature, mod-notes/src/test/java/org/folio/ModNotesTest.java
Write tests for note types
Results:
=> FAT-1113 Adjust Karate tests for mod-notes

data-import/src/main/resources/domain/data-import/global/add-okapi-permissions.feature
Fix data-import flow in jenkins
- Remove duplicate permission
=> Remove duplicate permission

mod-notes/src/main/resources/karate-config.js, mod-notes/src/main/resources/spitfire/mod-notes/features/note-links.feature, mod-notes/src/main/resources/spitfire/mod-notes/features/note-types.feature, mod-notes/src/main/resources/spitfire/mod-notes/features/notes.feature, mod-notes/src/main/resources/spitfire/mod-notes/features/samples/note-links.json, mod-notes/src/main/resources/spitfire/mod-notes/features/samples/note-put.json, mod-notes/src/main/resources/spitfire/mod-notes/features/setup/setup-test-note-type.feature, mod-notes/src/main/resources/spitfire/mod-notes/features/setup/setup-test-note.feature, mod-notes/src/main/resources/spitfire/mod-notes/notes-junit.feature, mod-notes/src/test/java/org/folio/ModNotesTest.java
After migration to Spring, some Karate tests should be adjusted to module responses.
Note links and Notes tests passed successfully.
https://issues.folio.org/browse/FAT-1134
=> FAT-1134 Adjust Karate tests for mod-notes (Notes and Note links)

data-import/src/main/resources/domain/data-import/data-import-junit.feature
Ensure that mod-data-import flow are started in temp env
- Commented out module and permission related with mod-data-export from set up file
https://issues.folio.org/browse/FAT-1139
=> FAT-1139 Ensure CREATE flows run on temp env

mod-kb-ebsco-java/src/main/resources/karate-config.js, mod-kb-ebsco-java/src/main/resources/spitfire/mod-kb-ebsco-java/features/samples/usage-consolidation/ucCredentials.json, mod-kb-ebsco-java/src/main/resources/spitfire/mod-kb-ebsco-java/features/samples/usage-consolidation/ucSettings.json, mod-kb-ebsco-java/src/main/resources/spitfire/mod-kb-ebsco-java/features/usage-consolidation.feature
Implement usage consolidation cases
- add config parameters
- implement scenarios
- add sample files
[FAT-981](https://issues.folio.org/browse/FAT-981)
=> FAT-981 mod-kb-ebsco-java: Implement API Karate tests - Usage Consolidation

mod-search/src/test/java/org/folio/SearchApiTest.java, mod-search/src/test/resources/falcon/mod-search/filters/facet-search.feature, mod-search/src/test/resources/falcon/mod-search/filters/filter-search.feature, mod-search/src/test/resources/falcon/mod-search/filters/sort-by-option-search.feature, mod-search/src/test/resources/falcon/mod-search/search/single-property-search.feature, mod-search/src/test/resources/falcon/mod-search/set-up/create-test-data.feature, mod-search/src/test/resources/falcon/mod-search/set-up/tenant-init.feature, mod-search/src/test/resources/samples/facet.json, mod-search/src/test/resources/samples/test-data/holdings.json, mod-search/src/test/resources/samples/test-data/instances.json, mod-search/src/test/resources/samples/test-data/items.json
* wildcards
* facet search
* operators (with sorting, limit, offset, expand all)
** "any"
** "=="
** "<>"
** dates "<=", ">=", "<", ">" 
[FAT-989](https://issues.folio.org/browse/FAT-989)
=> FAT-989 Karate tests: Implement missing tests

mod-circulation/src/main/resources/vega/mod-circulation/features/loans.feature, mod-circulation/src/main/resources/vega/mod-circulation/features/requests.feature, mod-circulation/src/main/resources/vega/mod-circulation/features/samples/policies/request-policy-entity-request.json, mod-circulation/src/main/resources/vega/mod-circulation/features/samples/request-entity-request.json, mod-circulation/src/main/resources/vega/mod-circulation/features/util/initData.feature, mod-circulation/src/test/java/org/folio/ModCirculationTests.java
[FAT-1030](https://issues.folio.org/browse/FAT-1030)
_Given an item Id, a user Id, and a pickup location, attempt to create a page request when the applicable request policy disallows pages_
=> FAT-1030: Given an item Id, a user Id, and a pickup location, attempt to create a page request when the applicable request policy disallows pages 

edge-patron/src/main/resources/domain/edge-patron/features/util/initData.feature
As file systems may be case sensitive.
=> Fix path for generated file

data-import/src/main/resources/domain/data-import/data-import-junit.feature
Run the tests after the task has been unlocked
- Uncommented data-export mod and perms in mod-data-import flow setup
https://issues.folio.org/browse/FAT-1102
=> FAT-1102 Investigate and fix issues regarding data-import-integration tests

acquisitions/src/main/resources/global/finances.feature, acquisitions/src/main/resources/thunderjet/mod-ebsconet/features/update-ebsconet-order-line.feature, acquisitions/src/main/resources/thunderjet/mod-ebsconet/features/update-mixed-order-line.feature, acquisitions/src/main/resources/thunderjet/mod-finance/features/ledger-fiscal-year-rollover-pol-and-system-currencies-are-different.feature, acquisitions/src/main/resources/thunderjet/mod-finance/features/ledger-fiscal-year-rollover.feature, acquisitions/src/main/resources/thunderjet/mod-invoice/features/should_populate_vendor_address_on_get_voucher_by_id.feature, acquisitions/src/main/resources/thunderjet/mod-orders/features/open-ongoing-order-should-fail-if-interval-or-renewaldate-notset.feature, acquisitions/src/main/resources/thunderjet/mod-orders/features/open-ongoing-order.feature
=> MODFISTO-279 update test data

mod-inn-reach/pom.xml, mod-inn-reach/src/main/resources/domain/mod-inn-reach.feature, mod-inn-reach/src/main/resources/karate-config.js, mod-inn-reach/src/main/resources/logback-test.xml, pom.xml
Purpose
https://issues.folio.org/browse/FAT-918
Approach
Set up API Karate tests for the module
API Karate Tests are set up and can be implemented for the module.
=> [FAT-918] mod-inn-reach: Setup API Karate tests in the module.

mod-users/src/main/resources/domain/mod-users/features/users.feature
Changed Username "aaa" to "mnq".
=>  mod-users-karate-test_fix_duplicate_user

mod-notify/src/main/resources/vega/mod-notify/features/notify.feature, mod-notify/src/main/resources/vega/mod-notify/features/patronNotice.feature, mod-notify/src/main/resources/vega/mod-notify/features/samples/sleep-function.js
Fix mod-notify tests
Add sleep before /email call
https://issues.folio.org/browse/FAT-1548
=> FAT-1548 Add sleep to patronNotice.feature

mod-audit/src/main/resources/firebird/mod-audit/features/loanEvent.feature, mod-audit/src/main/resources/firebird/mod-audit/features/requestEvent.feature
[FAT-1478](https://issues.folio.org/browse/FAT-1478) - MODAUD: fix api karate tests failures for mod-audit module
Before merging this PR, please go through the following list and take appropriate actions.
- Does this PR meet or exceed the expected quality standards?
- Does this introduce breaking changes?
If there are breaking changes, please **STOP** and consider the following:
- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
- Are the JIRAs under active development?
- Do PRs exist for these changes?
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …
=> [FAT-1478] - add pause

mod-search/src/test/resources/falcon/mod-search/filters/facet-search.feature
Should rename field after completing this task: [MSEARCH-298](https://issues.folio.org/browse/MSEARCH-298)
=> mod-search Rename field

edge-caiasoft/src/main/resources/firebird/edge-caiasoft/features/return-should-change-item-status-to-available-when-no-hold-request-exists.feature, edge-caiasoft/src/main/resources/firebird/edge-caiasoft/features/return-should-create-retrieval-queue-record-when-hold-request-exists.feature, edge-dematic/src/main/resources/firebird/edge-dematic/features/lookup-asr-requests.feature, edge-dematic/src/main/resources/firebird/edge-dematic/features/update-asr-item-being-retrieved.feature, edge-dematic/src/main/resources/firebird/edge-dematic/features/update-asr-item-status-available.feature
[FAT-1604](https://issues.folio.org/browse/FAT-1606) - Fix API karate tests failures for edge-caiasoft and edge-dematic modules
=> FAT-1606 - update expiration date for users for caisoft and dematic

mod-search/src/test/java/org/folio/SearchApiTest.java, mod-search/src/test/resources/samples/test-data/instances.json, mod-search/src/test/resources/spitfire/mod-search/browse/subject-browse.feature, mod-search/src/test/resources/spitfire/mod-search/set-up/tenant-init.feature
Since the subject browsing has been implemented, karate test must be added to validate existing approach.
- Update instances with subjects for browsing
- Add integration tests for browsing around, around_including, forward and backward directions
=> FAT-1611 Implement integration tests for browsing by subjects

mod-search/src/test/resources/spitfire/mod-search/set-up/create-test-data.feature, mod-search/src/test/resources/spitfire/mod-search/set-up/tenant-init.feature
Since the https://issues.folio.org/browse/MSEARCH-323 has been implemented, tests are failing because the return values changed
=> FAT-1611 Fix test after changing default behaviour

mod-bulk-edit/src/main/resources/firebird/bulk-edit/features/bulk-edit-users.feature, mod-bulk-edit/src/main/resources/global/diku-setup-users.feature, mod-bulk-edit/src/main/resources/global/variables.feature, mod-bulk-edit/src/main/resources/karate-config.js, mod-bulk-edit/src/main/resources/samples/user/expected-users-preview-after-identifiers-job.json, mod-bulk-edit/src/main/resources/samples/user/expected-users-preview-after-update-job.json
Update tests due to last mod-data-export-worker changes
Make test users be totally unique
=> FAT-1592: Update preview endpoint, make tests users to be totally unique

mod-bulk-edit/src/main/resources/karate-config.js, mod-bulk-edit/src/test/java/org/folio/ModBulkEditApiTest.java
Replace tenant diku with supertenant
=> FAT-1592: change the tenant from diku to supertenant since the diku is absent on karate env

mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/quick-marc-holdings-records.feature, mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/setup/setup.feature
Remove qm record creation in setup
https://issues.folio.org/browse/FAT-1658
=> FAT-1658 Remove qm record creation in setup

data-import/src/main/resources/folijet/data-import/features/data-import-integration.feature
[FAT-1458](https://issues.folio.org/browse/FAT-1458)
=> FAT-1458 Add check in Create Instance, Holdings, Item flow for Holdings source

acquisitions/src/main/resources/thunderjet/cross-modules/cross-modules.feature, acquisitions/src/main/resources/thunderjet/cross-modules/features/check-encumbrances-after-order-is-reopened.feature, acquisitions/src/main/resources/thunderjet/cross-modules/features/check-po-numbers-updates.feature, acquisitions/src/main/resources/thunderjet/cross-modules/features/chek-po-numbers-updates-when-invoice-line-deleted.feature, acquisitions/src/main/resources/thunderjet/cross-modules/features/link-invoice-line-to-po-line.feature, acquisitions/src/main/resources/thunderjet/mod-invoice/features/check-invoice-lines-and-documents-are-deleted-with-invoice.feature, acquisitions/src/main/resources/thunderjet/mod-invoice/features/exchange-rate-update-after-invoice-approval.feature, acquisitions/src/main/resources/thunderjet/mod-invoice/features/expense-classes-validation.feature, acquisitions/src/main/resources/thunderjet/mod-invoice/features/prorated-adjustments-special-cases.feature
[MODINVOICE-373](https://issues.folio.org/browse/MODINVOICE-373)
=> MODINVOICE-373 Improve validation to preventing creation invoice lines with wrong expense classes

acquisitions/src/main/resources/thunderjet/cross-modules/cross-modules.feature, acquisitions/src/main/resources/thunderjet/cross-modules/features/partial-rollover.feature, acquisitions/src/main/resources/thunderjet/mod-finance/finance-junit.feature, acquisitions/src/main/resources/thunderjet/mod-finance/finance.feature, acquisitions/src/main/resources/thunderjet/mod-finance/reusable/createFiscalYear.feature, acquisitions/src/main/resources/thunderjet/mod-orders/reusable/create-order-line.feature, acquisitions/src/main/resources/thunderjet/mod-orders/reusable/create-order.feature, acquisitions/src/main/resources/thunderjet/mod-orders/reusable/open-order.feature, acquisitions/src/test/java/org/folio/CrossModulesApiTest.java
[MODFISTO-298](https://issues.folio.org/browse/MODFISTO-298) - Unable to access adjustment ledger
- New test of a rollover with no order type selected for encumbrances
- New reusable features
- Fixed a permission issue
=> [MODFISTO-298] Partial rollover

mod-circulation/src/main/resources/vega/mod-circulation/features/loans.feature
[FAT-1000](https://issues.folio.org/browse/FAT-1000)
_When an existing loan is aged to lost update agedToLostDate, item status to Aged to lost_
=> FAT-1000: Fix time interval issue to get aged-to-lost loan

mod-inn-reach/src/main/resources/volaris/mod-inn-reach/features/contribution-criteria.feature, mod-inn-reach/src/main/resources/volaris/mod-inn-reach/samples/contribution-criteria/contribution-criteria.json
Purpose/Overview:
Karate implementation is created for the following endpoints
GET /central-servers/{centralServerId}/contribution-criteria
POST /central-servers/{centralServerId}/contribution-criteria
PUT /central-servers/{centralServerId}/contribution-criteria
DELETE /central-servers/{centralServerId}/contribution-criteria
https://issues.folio.org/browse/FAT-1536
=> FAT-1536 - mod-inn-reach: Implement API Karate tests - Contribution criteria

mod-circulation/src/main/resources/vega/mod-circulation/features/loans.feature
[FAT-1018](https://issues.folio.org/browse/FAT-1018)
_When an overdue item is renewed, an overdue fine is billed per the Overdue Fine Policy_
=> FAT-1018: When an overdue item is renewed, an overdue fine is billed per the Overdue Fine Policy

acquisitions/src/main/resources/thunderjet/mod-finance/features/ledger-fiscal-year-rollover.feature, acquisitions/src/main/resources/thunderjet/mod-finance/features/ledger-fiscal-year-rollovers-multiple.feature, acquisitions/src/main/resources/thunderjet/mod-finance/finance.feature
=> MODFISTO-311 - integration test for multiple ledger rollovers

acquisitions/src/main/resources/thunderjet/mod-ebsconet/ebsconet.feature, acquisitions/src/main/resources/thunderjet/mod-ebsconet/features/cancel-order-lines-with-ebsconet.feature, acquisitions/src/main/resources/thunderjet/mod-ebsconet/features/get-ebsconet-order-line.feature, acquisitions/src/main/resources/thunderjet/mod-ebsconet/features/update-ebsconet-order-line.feature, acquisitions/src/test/java/org/folio/EbsconetApiTest.java
[MODEBSNET-22](https://issues.folio.org/browse/MODEBSNET-22) - Support canceling POL(s) through EBSCONET integration
- Added a new test
- Partially fixed the other tests
[MODEBSNET-34](https://issues.folio.org/browse/MODEBSNET-34) - Resolve issue with failing test
=> [MODEBSNET-22] Cancel pol with ebsconet

data-import/src/main/resources/folijet/data-import/features/data-import-authority-records.feature, data-import/src/main/resources/folijet/data-import/features/data-import-delete-logs.feature, data-import/src/main/resources/folijet/data-import/features/data-import-holdings-records.feature, data-import/src/main/resources/folijet/data-import/features/data-import-integration.feature, data-import/src/main/resources/folijet/data-import/features/get-completed-job-execution.feature, data-import/src/main/resources/folijet/data-import/features/import-edi-invoice.feature, data-import/src/test/java/org/folio/DataImportApiTest.java
There are 4 known issues with functionality (requests/files/profiles) for data import
=> FAT-964 Fixed causes for data-import-integration karate tests failure on autorun

mod-inn-reach/src/main/resources/volaris/mod-inn-reach/features/item-type-mapping.feature, mod-inn-reach/src/main/resources/volaris/mod-inn-reach/samples/item-type-mapping/item-type-mapping-schema.json, mod-inn-reach/src/main/resources/volaris/mod-inn-reach/samples/item-type-mapping/item-type-mappings.json
**Purpose/Overview:**
Karate implementation is created for the following endpoints
```
GET /central-servers/{centralServerId}/item-type-mappings
PUT /central-servers/{centralServerId}/item-type-mappings
```
=> FAT-1544 mod-inn-reach: Implement API Karate tests - Item type mappings

mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/quick-marc-authority-records.feature, mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/setup/setup.feature
- Increase timeout
- Edit optimistic locking for Authority
=> FAT-2117 Karate test fail: [spitfire/mod-quick-marc]

mod-inn-reach/src/main/resources/volaris/mod-inn-reach/features/central-patron-type-mapping.feature, mod-inn-reach/src/main/resources/volaris/mod-inn-reach/features/item-contribution-options-configuration.feature, mod-inn-reach/src/main/resources/volaris/mod-inn-reach/features/user-custom-field-mapping.feature, mod-inn-reach/src/main/resources/volaris/mod-inn-reach/samples/user-custom-field-mapping/create-user-custom-field-mappings-invalid-request.json, mod-inn-reach/src/main/resources/volaris/mod-inn-reach/samples/user-custom-field-mapping/create-user-custom-field-mappings-request.json
[FAT-1545](https://issues.folio.org/browse/FAT-1545)
- mod-inn-reach: Implement API Karate tests - User custom field mapping
Karate implementation is created for the following endpoints:
GET /central-servers/{centralServerId}/user-custom-field-mappings
POST /central-servers/{centralServerId}/user-custom-field-mappings
PUT /central-servers/{centralServerId}/user-custom-field-mappings
API test are created
Positive and negative cases covered
=> FAT-1545 - mod-inn-reach: Implement API Karate tests - User custom field mapping

mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/quick-marc-authority-records.feature, mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/quick-marc-holdings-records.feature, mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/setup/setup.feature
Sometimes created record instantly started be "IN_PROGRESS" instead of be "NEW", and test falls
So it fix that moment and check if it's not "IN_PROGRESS"
=> FAT-2117 Wait for holdings creation

mod-inn-reach/src/main/resources/karate-config.js
Comment call to add-okapi-permissions.feature needed for local development/testing only
JIRA: [FAT-2109](https://issues.folio.org/browse/FAT-2109), [FAT-2108](https://issues.folio.org/browse/FAT-2108)
=> FAT-2109 Comment call to add-okapi-permissions.feature needed for local development only

mod-source-record-manager/src/main/resources/folijet/mod-source-record-manager/features/mapping-rules.feature
Add ability to restore default rules for Authorities
=> FAT-2118 Restore rules for authority

mod-inn-reach/src/main/resources/volaris/mod-inn-reach/features/bib-info.feature, mod-inn-reach/src/main/resources/volaris/mod-inn-reach/features/central-server-configuration.feature, mod-inn-reach/src/main/resources/volaris/mod-inn-reach/features/contribution.feature, mod-inn-reach/src/main/resources/volaris/mod-inn-reach/features/inn-reach-circulation.feature, mod-inn-reach/src/main/resources/volaris/mod-inn-reach/features/inn-reach-proxy.feature, mod-inn-reach/src/main/resources/volaris/mod-inn-reach/features/inn-reach-transaction.feature, mod-inn-reach/src/main/resources/volaris/mod-inn-reach/features/patron-info.feature
Cucumber treats undefined scenarios as failures. Mark all "undefined" features with @ignore to avoid failures in cucumber report.
Sample of report with unwanted failures: https://jenkins-aws.indexdata.com/job/Testing/job/Scheduled%20Karate%20Tests/315/cucumber-html-reports/overview-features.html
=> FAT-2109 Mark all "undefined" features with @ignore to avoid failures in cucumber report

mod-inn-reach/src/main/resources/volaris/mod-inn-reach/features/contribution.feature, mod-inn-reach/src/main/resources/volaris/mod-inn-reach/mocks/general/auth-mock.feature, mod-inn-reach/src/main/resources/volaris/mod-inn-reach/mocks/general/inn-reach-locations-response.json, mod-inn-reach/src/main/resources/volaris/mod-inn-reach/samples/library-mapping/library-mappings1.json, mod-inn-reach/src/main/resources/volaris/mod-inn-reach/samples/material-type-mapping/create-material-type-mappings.json
Purpose:
Implement Karate test for the following endpoint:
- POST /inn-reach/central-servers/{centralServerId}/contributions
JIRA: [FAT-1555](https://issues.folio.org/browse/FAT-1555)
Approach:
- API test created in contribution.feature
- Sample json files added
- Mock for /innreach/v2/contribution/locations added
=> [FAT-1555] mod-inn-reach: Implement API Karate tests: Contribution - Initiate new "initial/full record contribution"

acquisitions/src/main/resources/global/inventory.feature, acquisitions/src/main/resources/global/variables.feature
Created FOLIO holdings source before tests starting
[MODORDERS-717](https://issues.folio.org/browse/MODORDERS-717) - Holdings source gets updated to MARC during importing from bib - happens when holdings was created by Order app (Lotus HF2)
=> MODORDERS-717 Holdings source gets updated to MARC during importing from bib - happens when holdings was created by Order app (Lotus HF2)

acquisitions/src/main/resources/thunderjet/mod-ebsconet/features/get-ebsconet-order-line.feature, acquisitions/src/main/resources/thunderjet/mod-ebsconet/features/update-ebsconet-order-line.feature
Add check for renewalNote field to the existing tests
=> MODEBSNET-39. Renewal note is blank after update

mod-inn-reach/src/main/resources/volaris/mod-inn-reach/features/central-server.feature, mod-inn-reach/src/main/resources/volaris/mod-inn-reach/features/inn-reach-transaction.feature, mod-inn-reach/src/main/resources/volaris/mod-inn-reach/mod-inn-reach-junit.feature, mod-inn-reach/src/main/resources/volaris/mod-inn-reach/samples/item/item_storage.json, mod-inn-reach/src/main/resources/volaris/mod-inn-reach/samples/patron-hold/patron-hold-request-2.json, mod-inn-reach/src/main/resources/volaris/mod-inn-reach/samples/unshipped-item/invalid-unshipped-item.json, mod-inn-reach/src/main/resources/volaris/mod-inn-reach/samples/unshipped-item/unshipped-item.json
[FAT-1563](https://issues.folio.org/browse/FAT-1563)
: mod-inn-reach: Implement API Karate tests: Circulation - Receive unshipped item at borrowing site
=> Start Receive Unshipped Item

mod-inn-reach/src/main/resources/volaris/mod-inn-reach/features/inn-reach-transaction.feature
[FAT-1562](https://issues.folio.org/browse/FAT-1562) - Circulation - Receive shipped item at borrowing site
Karate implementation is created for the following endpoint
PUT /transactions/{id}/receive-item/{servicePointId}
Tests implemented for positive and negative scenarios
=> FAT-1562 - Circulation - Receive shipped item at borrowing site

mod-inn-reach/src/main/resources/volaris/mod-inn-reach/features/inn-reach-transaction.feature, mod-inn-reach/src/main/resources/volaris/mod-inn-reach/samples/item-hold/uncirculated-request.json, mod-inn-reach/src/main/resources/volaris/mod-inn-reach/samples/patron-hold/cancel-patron-hold-request.json, mod-inn-reach/src/main/resources/volaris/mod-inn-reach/samples/unshipped-item/unshipped-item.json
FAT-1564 ( https://issues.folio.org/browse/FAT-1564 ) 
Purpose -> 
Karate implementation is created to test the following reactions to mod-circulation-storage events
Result ->
=> FAT-1564-a

mod-bulk-edit/src/main/resources/firebird/bulk-edit/features/bulk-edit-items-status.feature, mod-bulk-edit/src/main/resources/samples/item/json/invalid_item_status_content_update.json, mod-bulk-edit/src/main/resources/samples/item/json/item_status_content_update.json
[MODEXPW-181](https://issues.folio.org/browse/MODEXPW-181) - users-in-app-update: Update ITEMS content update in BulkEditController
Before merging this PR, please go through the following list and take appropriate actions.
- Does this PR meet or exceed the expected quality standards?
- Does this introduce breaking changes?
If there are breaking changes, please **STOP** and consider the following:
- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
- Are the JIRAs under active development?
- Do PRs exist for these changes?
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …
=> MODEXPW-181 - users-in-app-update: Update ITEMS content update in BulkEditController

mod-search/src/test/resources/spitfire/mod-search/browse/call-number-browse.feature
- Add fullCallNumber to not matched result
- Change prev/next from shelfKey to callNumber
=> FAT-2470 Fix Karate test for browse call-numbers

mod-inn-reach/src/main/resources/volaris/mod-inn-reach/features/inn-reach-transaction.feature, mod-inn-reach/src/main/resources/volaris/mod-inn-reach/samples/item-hold/in-transit-request.json
=> FAT-1576 : Implement API Karate tests: Owning Site API - Update the transaction when the item in-transit message is received

mod-data-import-converter-storage/src/main/resources/folijet/mod-data-import-converter-storage/data-import-converter-storage-junit.feature, mod-data-import-converter-storage/src/main/resources/folijet/mod-data-import-converter-storage/features/field-protection.feature, mod-data-import-converter-storage/src/test/java/org/folio/ModDataImportConverterStorageTest.java
Cover mod-data-import-converter-storage with API tests for field-protection
Jira: https://issues.folio.org/browse/FAT-1069
=> FAT-1069 : cover mod-data-import-converter-storage with API tests

mod-source-record-manager/src/main/resources/folijet/mod-source-record-manager/features/job-execution.feature, mod-source-record-manager/src/main/resources/folijet/mod-source-record-manager/source-record-manager.feature, mod-source-record-manager/src/test/java/org/folio/ModSourceRecordManagerTest.java
Cover mod-source-record-manager with API tests
Jira: https://issues.folio.org/browse/FAT-137
=> FAT-137: Cover mod-source-record-manager with API tests

acquisitions/src/main/resources/thunderjet/mod-finance/features/update-encumbrance-transactions.feature
=> MODFISTO-337 fixed optimistic locking usage

acquisitions/src/main/resources/thunderjet/cross-modules/features/check-encumbrances-after-order-is-reopened.feature, acquisitions/src/main/resources/thunderjet/mod-finance/features/update-encumbrance-transactions.feature
=> Modfisto 337 - optimistick locking test fix

acquisitions/src/main/resources/thunderjet/mod-organizations/features/acquisitions-api-tests.feature, acquisitions/src/main/resources/thunderjet/mod-organizations/organizations-junit.feature, acquisitions/src/main/resources/thunderjet/mod-organizations/organizations.feature
https://issues.folio.org/browse/FAT-2965
Results after fix:
=> [FAT-2965] Karate test fail: [thunderjet/mod-organizations] OrganizationsApiTest

acquisitions/src/main/resources/thunderjet/mod-finance/features/ledger-fiscal-year-preview-rollover.feature, acquisitions/src/main/resources/thunderjet/mod-finance/features/ledger-fiscal-year-rollover-MODFISTO-247.feature, acquisitions/src/main/resources/thunderjet/mod-finance/features/ledger-fiscal-year-rollover-pol-and-system-currencies-are-different.feature, acquisitions/src/main/resources/thunderjet/mod-finance/features/ledger-fiscal-year-rollover.feature, acquisitions/src/main/resources/thunderjet/mod-finance/features/ledger-fiscal-year-rollovers-multiple.feature
=> [MODFIN-270] Define and implement Business API : Ledger Rollover Logs

mod-bulk-edit/src/main/resources/karate-config.js
[FAT-1645](https://issues.folio.org/browse/FAT-1645) - Bulk-edit(Users) move tests run to test tenant
Fix karate config and remove localhost.
=> FAT-1645 Fixed karate config

mod-circulation/src/main/resources/vega/mod-circulation/features/loans.feature, mod-circulation/src/main/resources/vega/mod-circulation/features/util/initData.feature
=> FAT-2185 Do not expect check-in to succeed after unregistering from pubsub

teams-assignment.json
[FAT-1651](https://issues.folio.org/browse/FAT-1651) - Create Karate test skeleton for edge OAI-PMH
Update configuration to get notifications in slack channel
=> FAT-1651 - update configuration

mod-source-record-storage/src/main/resources/folijet/mod-source-record-storage/features/get-source-storage-records.feature, mod-source-record-storage/src/main/resources/folijet/mod-source-record-storage/source-record-storage.feature, mod-source-record-storage/src/test/java/org/folio/ModSourceRecordStorageTest.java
Add test case to retrieve deleted records
https://issues.folio.org/browse/MODSOURCE-552
=> Add test case for deleted source-record

mod-source-record-manager/src/main/resources/folijet/mod-source-record-manager/features/mapping-metadata.feature, mod-source-record-manager/src/main/resources/folijet/mod-source-record-manager/source-record-manager.feature, mod-source-record-manager/src/test/java/org/folio/ModSourceRecordManagerTest.java
Add karate test for MODSOURMAN-888
https://issues.folio.org/browse/MODSOURMAN-888
=> MODSOURMAN-888 - Link update: Implement API endpoint to retrieve mapping metadata by record type

common/src/main/resources/common/util/random_numbers.feature, common/src/main/resources/common/util/random_string.feature, common/src/main/resources/common/util/uuid1.feature, mod-users/src/main/resources/karate-config.js, mod-users/src/main/resources/prokopovych/mod-users/features/users.feature, mod-users/src/main/resources/prokopovych/mod-users/features/util/initData.feature
User proper param syntax in users.feature.
Move common functions to common/util/*.feature.
Use util1 and util2 as function name space in initData.feature to avoid hiding the same functions in users.feature.
=> FAT-2134: Karate test fail: [prokopovych/mod-users]

mod-kb-ebsco-java/src/main/resources/spitfire/mod-kb-ebsco-java/features/usage-consolidation.feature
=> FAT-3295 Fix error message

acquisitions/src/main/resources/thunderjet/mod-invoice/features/check-that-not-possible-pay-for-invoice-if-no-voucher.feature
=> [MODINVOICE-428]-updated error code.

mod-circulation/src/main/resources/vega/mod-circulation/features/requests.feature
=> Added groupId

mod-search/src/test/java/org/folio/SearchApiTest.java, mod-search/src/test/resources/spitfire/mod-search/browse/call-number-browse.feature
- Split Parameterized Test to single tests
- Use shelfKey in prev/next responses
=> mod-search: remove Parameterized Tests

mod-circulation/src/main/resources/vega/mod-circulation/features/requests.feature
https://issues.folio.org/browse/FAT-3333
made changes to https://issues.folio.org/browse/FAT-1045
=> FAT-3333: Made changes to FAT-1045 to fix bugs

acquisitions/src/main/resources/thunderjet/mod-orders/features/cancel-item-after-canceling-poline-in-multi-line-orders.feature, acquisitions/src/main/resources/thunderjet/mod-orders/orders.feature
=> [MODORDERS-792] - POL cancellation on multi-line orders

mod-circulation/src/main/resources/vega/mod-circulation/features/requests.feature
JIRA: https://issues.folio.org/browse/FAT-3333
https://issues.folio.org/browse/FAT-1045
=> FAT-3333 Made changes to FAT-1045 to fix bugs

mod-inn-reach/src/main/resources/volaris/mod-inn-reach/global/mod_inventory_init_data.feature, mod-inn-reach/src/main/resources/volaris/mod-inn-reach/global/mod_locations_util.feature, mod-inn-reach/src/main/resources/volaris/mod-inn-reach/samples/location-mapping/campuses-mainLibrary.json, mod-inn-reach/src/main/resources/volaris/mod-inn-reach/samples/location-mapping/institutions-ku.json, mod-inn-reach/src/main/resources/volaris/mod-inn-reach/samples/location-mapping/libraries-mainLibrary.json, mod-inn-reach/src/main/resources/volaris/mod-inn-reach/samples/location-mapping/locations-mainLibrary.json, mod-inn-reach/src/main/resources/volaris/mod-inn-reach/samples/location-mapping/service-points-mainLibrary.json
https://issues.folio.org/browse/FAT-3429
_This pull request has the code changes to add the main library location such that it can be used to create the initial data setup._
_Dedicated location POST request were called because the locations are no more present in reference data._
=> FAT-3429 - Add main-library location for the initial setup

acquisitions/src/main/resources/thunderjet/mod-orders/features/update_fund_in_poline_when_invoice_approved.feature, acquisitions/src/main/resources/thunderjet/mod-orders/orders.feature
=> [MODORDERS-803] - Add test for flow 3

README.md, edge-inn-reach/src/main/resources/volaris/edge-inn-reach/features/central-server.feature, mod-inn-reach/src/main/resources/volaris/mod-inn-reach/features/central-server.feature
Mock Server migration from old rancher to new rancher
* Mock server url updated
=> [FAT-3601]: mock server url updated for mod-inn-reach

mod-data-export/src/test/resources/global/inventory_data_setup_util.feature, mod-data-export/src/test/resources/global/mod_inventory_init_data.feature, mod-data-export/src/test/resources/samples/location/campus.json, mod-data-export/src/test/resources/samples/location/institution.json, mod-data-export/src/test/resources/samples/location/library.json, mod-data-export/src/test/resources/samples/location/locations.json, mod-data-export/src/test/resources/samples/location/permanentLocation.json, mod-data-export/src/test/resources/samples/location/service_point.json, mod-data-export/src/test/resources/samples/location/temporaryLocation.json
[FAT-3428](https://issues.folio.org/browse/FAT-3428) - Karate test fail: [firebird/data-export] ModDataExportApiTest {1}  firebird/dataexport/data-export-basic-junit.feature
Verified on karate testing environment:
=> FAT-3428 - Karate test fail: [firebird/data-export] ModDataExportApiTest {1}  firebird/dataexport/data-export-basic-junit.feature

acquisitions/src/main/resources/samples/mod-gobi/po-physical-annex-holding-1.xml, acquisitions/src/main/resources/samples/mod-gobi/po-physical-annex-holding-2.xml, acquisitions/src/main/resources/thunderjet/mod-gobi/features/find-holdings-by-location-and-instance.feature, acquisitions/src/main/resources/thunderjet/mod-gobi/gobi.feature
=> [MODORDERS-647] - Find logic for Holdings generated

mod-audit/src/main/resources/firebird/mod-audit/features/orderEvent.feature, mod-audit/src/main/resources/firebird/mod-audit/features/orderLineEvent.feature, mod-audit/src/main/resources/global/samples/mod-orders/orderLines/minimal-order-line.json, mod-audit/src/main/resources/global/variables.feature, mod-audit/src/test/java/org/folio/ModAuditApiTest.java
https://issues.folio.org/browse/MODAUD-144
https://issues.folio.org/browse/MODAUD-145
=> [MODAUD-144]-Added test to retrieve Order & Order_Line Change events

acquisitions/src/main/resources/thunderjet/mod-orders/features/MODORDERS-538-piece-against-non-package-mixed-pol-manual-piece-creation-is-false.feature, acquisitions/src/main/resources/thunderjet/mod-orders/features/MODORDERS-538-piece-against-non-package-mixed-pol-manual-piece-creation-is-true.feature, acquisitions/src/main/resources/thunderjet/mod-orders/features/update_copy_number.feature, acquisitions/src/main/resources/thunderjet/mod-orders/features/update_fields_in_item.feature, acquisitions/src/main/resources/thunderjet/mod-orders/orders.feature, acquisitions/src/test/java/org/folio/OrdersApiTest.java
The tests have been updated as the logic of creating holdings has been updated. Now if the piece contains only the 'LocationID' field when it is created, the corresponding 'holdingId' will be searched, if it is not, a new one will be created.
=> [MODORDERS-807] - Test for copy number

mod-circulation/src/main/resources/vega/mod-circulation/features/loans.feature
JIRA: https://issues.folio.org/browse/FAT-3790
=> FAT-3790: Remove usage of random() in generating barcodes in [vega/mod-circulation]

acquisitions/src/main/resources/thunderjet/mod-orders/features/update_linked_invoice_lines_fund_distribution_reference.feature, acquisitions/src/main/resources/thunderjet/mod-orders/orders.feature, acquisitions/src/test/java/org/folio/OrdersApiTest.java
[MODORDERS-801](https://issues.folio.org/browse/MODORDERS-801)
=> [MODORDERS-801] Check and correct encumbrance ID links for invoices with Open or Reviewed status (FLOW #4)

acquisitions/src/main/resources/global/finances.feature
=> MODFISTO-363 updated FY samples for 2023

acquisitions/src/main/resources/thunderjet/cross-modules/cross-modules.feature, acquisitions/src/main/resources/thunderjet/cross-modules/features/pay-invoice-and-delete-piece.feature, acquisitions/src/main/resources/thunderjet/cross-modules/features/unopen-approve-invoice-reopen.feature, acquisitions/src/main/resources/thunderjet/mod-invoice/reusable/approve-invoice.feature, acquisitions/src/main/resources/thunderjet/mod-invoice/reusable/create-invoice.feature, acquisitions/src/main/resources/thunderjet/mod-invoice/reusable/pay-invoice.feature, acquisitions/src/test/java/org/folio/CrossModulesApiTest.java
[MODORDERS-833](https://issues.folio.org/browse/MODORDERS-833) - Negative encumbrance values appear for expense classes after rollover
Added 2 new tests for encumbrances, matching the scenarios in the ticket.
=> [MODORDERS-833] New encumbrance tests

acquisitions/src/main/resources/thunderjet/mod-orders/features/MODORDERS-538-piece-against-non-package-mixed-pol-manual-piece-creation-is-false.feature, acquisitions/src/main/resources/thunderjet/mod-orders/features/MODORDERS-538-piece-against-non-package-mixed-pol-manual-piece-creation-is-true.feature
Reverted to the previous testing logic
https://github.com/folio-org/folio-integration-tests/commit/f09087ebba178199a10abba6da9a07b21bc9d604
=> [MODORDERS-821] - Create new holding for location tests

acquisitions/src/main/resources/thunderjet/mod-finance/reusable/createLedger.feature, acquisitions/src/main/resources/thunderjet/mod-invoice/features/fiscal-year-balance-with-negative-available.feature, acquisitions/src/main/resources/thunderjet/mod-invoice/invoice.feature, acquisitions/src/main/resources/thunderjet/mod-invoice/reusable/create-invoice-line.feature, acquisitions/src/test/java/org/folio/InvoicesApiTest.java
[MODFISTO-285](https://issues.folio.org/browse/MODFISTO-285) - Fiscal year "available" is over stated
Added a test to check the FY balance when an invoice is paid using a fund with a 0 balance.
=> [MODFISTO-285] Fiscal year balance with negative available

acquisitions/src/main/resources/thunderjet/mod-invoice/features/check-vendor-address-included-with-batch-voucher.feature
https://issues.folio.org/browse/MODINVOICE-431
=> MODINVOICE-431 adjusted batch voucher test after implementing new approach

acquisitions/src/main/resources/thunderjet/mod-orders/features/update_fund_in_poline_when_invoice_approved.feature
[FAT-4400](https://issues.folio.org/browse/FAT-4400)
=> [FAT-4400] - Removed oldEncumbrance before updating POL's funds

acquisitions/src/main/resources/thunderjet/mod-finance/features/group-and-ledger-transfers-after-rollover.feature, acquisitions/src/main/resources/thunderjet/mod-finance/finance.feature, acquisitions/src/test/java/org/folio/FinanceApiTest.java
[MODFIN-299](https://issues.folio.org/browse/MODFIN-299) - Group and Ledger summary for Net Transfers do not include Rollover transfer amounts.
Added a new test checking net transfers for group summaries and ledgers after a rollover using `rolloverAvailable`.
=> [MODFIN-299] Group and ledger transfers after rollover

acquisitions/src/main/resources/thunderjet/mod-orders/features/moving_expended_value_to_newly_created_encumbrance.feature, acquisitions/src/main/resources/thunderjet/mod-orders/features/update_fund_in_poline_when_invoice_approved.feature
[MODORDERS-841](https://issues.folio.org/browse/MODORDERS-841)
=> [MODORDERS-841] - Encumbrance current amount is calculated incorrectly after changing fund distribution when related paid invoice exists

acquisitions/src/main/resources/karate-config.js, acquisitions/src/main/resources/thunderjet/mod-orders/features/moving_expended_value_to_newly_created_encumbrance.feature
https://issues.folio.org/browse/MODFISTO-370
=> [MODFISTO-370] FLOW #2. Check and verify the rollover script and budget totals are working as expected

acquisitions/src/main/resources/thunderjet/cross-modules/cross-modules.feature, acquisitions/src/main/resources/thunderjet/cross-modules/features/change-fd-check-initial-amount.feature, acquisitions/src/test/java/org/folio/CrossModulesApiTest.java
[MODORDERS-842](https://issues.folio.org/browse/MODORDERS-842) - Incorrect displaying initial amount encumbered after changing distribution percentage
New test: open an order, pay an invoice, change the fund distribution, check encumbrances' initialAmountEncumbered.
=> [MODORDERS-842] Change fund dist, check initial amount

mod-inn-reach/src/main/resources/volaris/mod-inn-reach/features/central-server.feature
=> MODINREACH-337 update validations for mod-inn-reach not to rely on elements order

mod-circulation/src/main/resources/vega/mod-circulation/features/util/initData.feature, mod-feesfines/src/main/resources/vega/mod-feesfines/features/actualCostFeeFine.feature, mod-feesfines/src/main/resources/vega/mod-feesfines/features/samples/actual-cost-fee-fine-cancel-request-entity.json, mod-feesfines/src/main/resources/vega/mod-feesfines/features/samples/declare-item-lost-request-entity.json, mod-feesfines/src/main/resources/vega/mod-feesfines/features/samples/policies/lost-item-fee-policy-with-actual-cost-entity-request.json, mod-feesfines/src/main/resources/vega/mod-feesfines/features/util/initData.feature, mod-feesfines/src/main/resources/vega/mod-feesfines/feesfines-junit.feature, mod-feesfines/src/test/java/org/folio/FeesFinesApiTests.java
Create a test for manual actual cost fee/fine cancellation.
Resolves [FAT-3419](https://issues.folio.org/browse/FAT-3419)
=> FAT-3419: Tests for actual cost fee/fine cancellation

mod-bulk-operations/src/test/java/org/folio/ModBulkOperationsApiTest.java
[FAT-4558](https://issues.folio.org/browse/FAT-4558) - Karate Test:  Bulk edit holdings records - happy path
=> FAT-4558 - Karate Test:  Bulk edit holdings records - happy path

teams-assignment.json
Assign mod-copycat module to Folijet
=> Assign mod-copycat to Folijet

mod-bulk-operations/src/main/resources/samples/holdings/service-points.json, mod-bulk-operations/src/test/java/org/folio/ModBulkOperationsApiTest.java
[FAT-4575](https://issues.folio.org/browse/FAT-4575) - Karate test fail: [firebird/mod-bulk-operations] ModBulkOperationsApiTest {3}  firebird/mod-bulk-operations/features/holdings.feature
=> FAT-4575 - Karate test fail: [firebird/mod-bulk-operations] ModBulkOperationsApiTest {3}  firebird/mod-bulk-operations/features/holdings.feature

acquisitions/src/main/resources/thunderjet/mod-orders/features/item-and-holding-operations-for-order-flows.feature
=> [FAT-4438]-updated HoldingIds

data-import/src/test/java/org/folio/DataImportApiTest.java
Fix failing data-import-order tests
Change order of executing order import test
=> [FAT-3047] Change order of executing order import test

mod-search/src/test/resources/samples/createLink.json, mod-search/src/test/resources/samples/test-data/instances.json, mod-search/src/test/resources/spitfire/mod-search/browse/contributor-browse.feature, mod-search/src/test/resources/spitfire/mod-search/browse/subject-browse.feature
=> Fixes for Series and Subjects schema changes

mod-feesfines/src/main/resources/vega/mod-feesfines/features/automateFeeFines.feature
Resolves https://issues.folio.org/browse/FAT-4547
=> FAT-4547: Karate test fail: [vega/mod-feesfines] FeesFinesApiTests {8} vega/mod-feesfines/features/automateFeeFines.feature

mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/items.feature
[FAT-4556](https://issues.folio.org/browse/FAT-4556) - items feature
=> FAT-4556 - update pause values

mod-bulk-edit/src/main/resources/firebird/bulk-edit/bulk-edit-junit.feature, mod-bulk-edit/src/main/resources/firebird/bulk-edit/features/bulk-edit-users.feature, mod-bulk-edit/src/main/resources/karate-config.js
[FAT-4209](https://issues.folio.org/browse/FAT-4209) - Karate test fail: [firebird/bulk-edit] ModBulkEditApiTest {3} firebird/bulk-edit/features/bulk-edit-users.feature
=> FAT-4209 - update configs, timeouts, count of files

mod-search/src/test/resources/spitfire/mod-search/browse/contributor-browse.feature
Fix Karate test failure
Changed object field order in result list
[https://issues.folio.org/browse/FAT-4889](https://issues.folio.org/browse/FAT-4889)
=> FAT-4889: Changed response object list field order

mod-circulation/src/main/resources/vega/mod-circulation/features/loans.feature
Resolves: [FAT-4906](https://issues.folio.org/browse/FAT-4906) Karate test fail: [vega/mod-circulation] ModCirculationTests {2} vega/mod-circulation/features/root.feature
=> FAT-4906: Add retry to verify circulation rule has been saved in mod-circulation/features/loans.feature file

edge-oai-pmh/src/main/resources/samples/instance.json
[FAT-1662](https://issues.folio.org/browse/FAT-1662) - Karate test: C13781 List records in marc21 format with starting date
Test cases were implemented in scope of [FAT-1665](https://issues.folio.org/browse/FAT-1665). Fixed instance source to MARC.
=> FAT-1662 - Karate test: C13781 List records in marc21 format with starting date

acquisitions/src/main/resources/thunderjet/mod-orders/features/receive-20-pieces.feature, acquisitions/src/main/resources/thunderjet/mod-orders/orders.feature, acquisitions/src/main/resources/thunderjet/mod-orders/reusable/receive-piece.feature, acquisitions/src/test/java/org/folio/OrdersApiTest.java
[MODORDERS-862](https://issues.folio.org/browse/MODORDERS-862) - Issues with receiving Pieces
Added a new test receiving 20 pieces in a package order.
=> [MODORDERS-862] New test to receive 20 pieces

mod-circulation/src/main/resources/vega/mod-circulation/features/loans.feature
Resolves: [FAT-4976](https://issues.folio.org/browse/FAT-4976) Karate test fail: [vega/mod-circulation] ModCirculationTests {2} vega/mod-circulation/features/root.feature
=> FAT-4976: Reorder order of independent requests in mod-circulation/features/loans.feature file

acquisitions/src/main/resources/thunderjet/mod-orders/features/check-new-tags-in-central-tag-repository.feature
=> [FAT-4437]-updated tags feature.

data-import/src/main/resources/folijet/data-import/features/data-import-delete-logs.feature
add retries when getting job log entries during data import. It is setup to then delete the job log.
=> FAT-4701 retry when getting job log entries

acquisitions/src/main/resources/thunderjet/cross-modules/cross-modules-junit.feature, acquisitions/src/main/resources/thunderjet/cross-modules/cross-modules.feature, acquisitions/src/main/resources/thunderjet/mod-ebsconet/ebsconet-junit.feature, acquisitions/src/main/resources/thunderjet/mod-ebsconet/ebsconet.feature, acquisitions/src/main/resources/thunderjet/mod-orders/orders-junit.feature, acquisitions/src/main/resources/thunderjet/mod-orders/orders.feature
=> MODORDERS-865 fixed permission set

acquisitions/src/main/resources/thunderjet/cross-modules/cross-modules-junit.feature, acquisitions/src/main/resources/thunderjet/cross-modules/cross-modules.feature, acquisitions/src/main/resources/thunderjet/mod-ebsconet/ebsconet-junit.feature, acquisitions/src/main/resources/thunderjet/mod-ebsconet/ebsconet.feature, acquisitions/src/main/resources/thunderjet/mod-orders/orders-junit.feature, acquisitions/src/main/resources/thunderjet/mod-orders/orders.feature
=> Modorders 865 perms

acquisitions/src/main/resources/thunderjet/mod-invoice/features/invoice-fiscal-years.feature, acquisitions/src/main/resources/thunderjet/mod-invoice/invoice.feature, acquisitions/src/test/java/org/folio/InvoicesApiTest.java
[MODINVOICE-465](https://issues.folio.org/browse/MODINVOICE-465) - Provide endpoint to retrieve fiscal year for invoice
Added a new test
The test might have to be update if and when we support adding invoice lines with funds that don't have a current budget.
=> [MODINVOICE-465] Invoice fiscal years

mod-search/src/test/resources/samples/test-data/instances.json, mod-search/src/test/resources/spitfire/mod-search/browse/contributor-browse.feature
Adjust contributor browse test to updated response
10 of 10 were successful:
=> MSEARCH-510 Adjust contributor browse test to updated response

acquisitions/src/main/resources/thunderjet/mod-orders/features/find-holdings-by-location-and-instance-for-mixed-pol.feature, acquisitions/src/main/resources/thunderjet/mod-orders/orders.feature, acquisitions/src/test/java/org/folio/OrdersApiTest.java
=> [MODORDERS-871] - Test added for finding holdings record during import open P/E mix orderLine

data-import/src/main/resources/folijet/data-import/samples/samples_for_upload/default-marc-bib-rules.json
Update default marc-bib mapping rules to match changes in srm: https://github.com/folio-org/mod-source-record-manager/pull/768/commits/e11f9749bde7a34d231a4f8d45322199210da98a
Update default marc-bib mapping rules
=> [MODDICORE-323] Update default marc-bib mapping rules

acquisitions/src/main/resources/thunderjet/mod-invoice/features/approve-and-pay-invoice-with-past-fiscal-year.feature, acquisitions/src/main/resources/thunderjet/mod-invoice/invoice.feature, acquisitions/src/test/java/org/folio/InvoicesApiTest.java
[MODINVOICE-463](https://issues.folio.org/browse/MODINVOICE-463) - Provide fiscalYear field for pending payments, payments and credits
Added a new test.
See [related mod-invoice PR](https://github.com/folio-org/mod-invoice/pull/406).
=> [MODINVOICE-463] Approve and pay invoice with past fiscal year

mod-search/src/test/resources/spitfire/mod-search/search/authority-single-property-search.feature
Removed unused field and changed result due to numberOfTitles count new logic.
=> FAT-5392 Removed unused field and changed result due to numberOfTitles count new logic

mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/quick-marc-bib-records.feature
Fixed the response fields of quickMarc Json
=> FAT-5540 Fixed the response fields of quickMarc Json

mod-circulation/src/main/resources/vega/mod-circulation/features/loans.feature, mod-circulation/src/main/resources/vega/mod-circulation/features/requests.feature, mod-circulation/src/main/resources/vega/mod-circulation/features/root.feature, mod-circulation/src/main/resources/vega/mod-circulation/features/samples/automated-patron-blocks/array-of-automated-patron-blocks.json
Resolves: [FAT-5600](https://issues.folio.org/browse/FAT-5600) and [FAT-5559](https://issues.folio.org/browse/FAT-5559)
Add retry attempt to retrieve 'automatedPatronBlocks'
=> [FAT-5600] Karate test fail in mod-circulation

mod-circulation/src/main/resources/vega/mod-circulation/features/requests.feature, mod-circulation/src/main/resources/vega/mod-circulation/features/samples/holdings-entity-request.json, mod-circulation/src/main/resources/vega/mod-circulation/features/samples/item/item-entity-request.json
https://issues.folio.org/browse/FAT-5355
=> FAT-5355: Test request filtering by call number

mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/quick-marc-authority-records.feature
Add additional delete operations to warm up the server and make jobs finish successfully.
=> FAT-5539 Changed the order of scenarios and added addition delete operation to warm up the server and make jobs finish successfully

edge-oai-pmh/src/main/resources/firebird/edge-oai-pmh/features/edge-oai-pmh.feature
[FAT-1649](https://issues.folio.org/browse/FAT-1649) - Karate tests: List records in marc21 format with start and end date
=> FAT-1649 - ListRecords marc21 from,until and resumption token

mod-circulation/src/main/resources/vega/mod-circulation/features/requests.feature
https://issues.folio.org/browse/FAT-5722
=> FAT-5722: Karate test fail in mod-circulation

edge-oai-pmh/src/main/resources/firebird/edge-oai-pmh/features/edge-oai-pmh.feature, edge-oai-pmh/src/main/resources/firebird/edge-oai-pmh/features/init_data/init-edge-oai-pmh.feature, edge-oai-pmh/src/main/resources/samples/item.json
[MODOAIPMH-477)](https://issues.folio.org/browse/MODOAIPMH-477) - Adjust 856 mappings
=> MODOAIPMH-477 - new types of electronic access relationship

common/src/main/resources/common/setup-users.feature, mod-bulk-edit/src/main/resources/global/diku-setup-users.feature, mod-oai-pmh/src/test/resources/common/setup-users.feature, mod-oai-pmh/src/test/resources/common/tenant.feature
=> Increased timeout when enabling tenant

mod-circulation/src/main/resources/vega/mod-circulation/features/requests.feature, mod-circulation/src/main/resources/vega/mod-circulation/features/samples/request/request-entity-request.json
https://issues.folio.org/browse/FAT-5722
=> FAT-5722: Fix test fail in mod-circulation

mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/quick-marc-holdings-records.feature
The externalHrid field becomes mandatory.
=> FAT-5815 Add the missing required externalHrid field.

mod-source-record-manager/src/main/resources/folijet/mod-source-record-manager/features/mapping-metadata.feature
to fix linking rules extraction for verification
https://issues.folio.org/browse/FAT-5839
=> FAT-5839 - Fixed linkingRules extraction

mod-users-bl/src/main/resources/prokopovych/mod-users-bl/features/users-bl.feature
To fix the failing test case of mod-users-bl
Updated the password as it was failing due to password.compromised.invalid
=> [FAT-5912] - Updated the password as it was failing due to password.compromised.invalid

edge-caiasoft/src/main/resources/firebird/edge-caiasoft/features/check-in-by-request-id-and-remote-configuration-id.feature, edge-caiasoft/src/main/resources/firebird/edge-caiasoft/features/return-should-create-retrieval-queue-record-when-hold-request-exists.feature, edge-dematic/src/main/resources/firebird/edge-dematic/features/lookup-asr-requests.feature, edge-dematic/src/main/resources/firebird/edge-dematic/features/update-asr-item-status-available.feature, edge-patron/src/main/resources/prokopovych/edge-patron/features/samples/request/request-entity-request.json, mod-audit/src/main/resources/firebird/mod-audit/features/requestEvent.feature, mod-circulation/src/main/resources/vega/mod-circulation/features/samples/cancel-request-entity-request.json, mod-circulation/src/main/resources/vega/mod-circulation/features/samples/request/legacy-request-entity-request.json, mod-circulation/src/main/resources/vega/mod-circulation/features/samples/request/request-entity-request.json, mod-circulation/src/main/resources/vega/mod-circulation/features/samples/request/title-level-request-entity-request.json, mod-patron-blocks/src/main/resources/vega/mod-patron-blocks/features/samples/item-request-entity.json, mod-patron-blocks/src/main/resources/vega/mod-patron-blocks/features/samples/page-request-entity.json, mod-patron-blocks/src/main/resources/vega/mod-patron-blocks/features/samples/recall-request-entity.json
https://issues.folio.org/browse/FAT-5958
=> FAT-5958: Karate test fail in mod-circulation

mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/setup/samples/parsed-records/bib-record.json
Fix QuickMarc Create 
Add _actionType missing field
=> FAT-5816 Add _actionType missing field

acquisitions/src/main/resources/thunderjet/mod-invoice/features/check-vendor-address-included-with-batch-voucher.feature
=> MODINVOICE-480 fixed test

acquisitions/src/main/resources/karate-config.js, acquisitions/src/main/resources/thunderjet/mod-invoice/features/batch-voucher-uploaded.feature, acquisitions/src/main/resources/thunderjet/mod-invoice/features/check-vendor-address-included-with-batch-voucher.feature, acquisitions/src/test/java/org/folio/InvoicesApiTest.java
=> Modinvoice 480 - fixed batch voucher uploading test

acquisitions/src/main/resources/thunderjet/mod-invoice/invoice-junit.feature, acquisitions/src/main/resources/thunderjet/mod-invoice/invoice.feature
=> [MODINVOICE-471] - Added permission

acquisitions/src/main/resources/karate-config.js, acquisitions/src/main/resources/thunderjet/mod-invoice/features/batch-voucher-uploaded.feature
=> FAT-6485 fix batch-voucher-uploaded.feature

acquisitions/src/main/resources/thunderjet/mod-orders/features/open-order-with-the-same-fund-distributions.feature, acquisitions/src/main/resources/thunderjet/mod-orders/features/unopen-order-after-adding-the-same-fund-distribution.feature, acquisitions/src/main/resources/thunderjet/mod-orders/orders.feature, acquisitions/src/test/java/org/folio/OrdersApiTest.java
[MODORDERS-894](https://issues.folio.org/browse/MODORDERS-894)
=> [MODORDERS-894] - Adding fund distribution line in the POL breaks the order record. Can no longer open.

acquisitions/src/main/resources/thunderjet/mod-consortia/features/tenant.feature
https://issues.folio.org/browse/MODCON-64
=> [MODCON - 64] - Fixed transaction behaviour of saving tenant method

mod-circulation/src/main/resources/vega/mod-circulation/features/loans.feature
Resolves: [FAT-6711](https://issues.folio.org/browse/FAT-6711) Karate test fail: [vega/mod-circulation] ModCirculationTests {2} vega/mod-circulation/features/root.feature
=> [FAT-6711] Karate test fail in 'mod-circulation'

acquisitions/src/main/resources/thunderjet/mod-consortia/features/user-tenant-associations.feature
Continuation of [MODCON-53](https://issues.folio.org/browse/MODCON-53) Cover missed karate scenarios for Consortia functionality:
Added test case: _If we DELETE real user all records related to this user should be deleted for both 'central' (isCentral=true) and institutional (isCentral=false) tenants_
=> [MODCON-53] Cover missed karate scenarios for Consortia functionality

mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/holdings.feature
[MODBULKOPS-102](https://issues.folio.org/browse/MODBULKOPS-102) - Suppress from discovery holdings records in bulk
=> MODBULKOPS-102 - update bulk edit holdings

acquisitions/src/main/resources/thunderjet/mod-orders/features/find-holdings-by-location-and-instance-for-mixed-pol-with-create-inventory-none.feature, acquisitions/src/test/java/org/folio/OrdersApiTest.java
https://issues.folio.org/browse/MODORDERS-902
=> [MODORDERS-902]-Added Karate test.

acquisitions/src/main/resources/thunderjet/mod-consortia/consortia-junit.feature, acquisitions/src/main/resources/thunderjet/mod-consortia/features/publish-coordinator.feature
* implemented tests for
https://issues.folio.org/browse/MODCON-48
https://issues.folio.org/browse/MODCON-49
https://issues.folio.org/browse/MODCON-56
=> MODCON-48 publish coordinator API tests

mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/items.feature
[MODBULKOPS-101](https://issues.folio.org/browse/MODBULKOPS-101) - Supported bulk edit action for item notes
=> MODBULKOPS-101 - Supported bulk edit action for item notes

data-import/src/main/resources/folijet/data-import/global/default-import-instance-holding-item.feature, data-import/src/main/resources/folijet/data-import/samples/samples_for_upload/default-marc-bib-rules.json
_Fix data-import-integration.feature scenarios._
_Regarding coordinator name, actual value is `Hampton, Alexander J. B.,` but the expected value from the response is without coma symbol._
=> FAT-6493: Update marc bib rules according to MODDICORE-347

mod-circulation/src/main/resources/vega/mod-circulation/features/requests.feature, mod-circulation/src/main/resources/vega/mod-circulation/features/samples/instance/instance-entity-request.json, mod-circulation/src/main/resources/vega/mod-circulation/features/util/initData.feature, mod-feesfines/src/main/resources/vega/mod-feesfines/features/samples/instance-entity-request.json
Tests for [CIRC-1826](https://issues.folio.org/browse/CIRC-1826)
=> FAT-7137 Tests for allowed service points for item

acquisitions/src/main/resources/thunderjet/mod-finance/features/ledger-fiscal-year-preview-rollover.feature, acquisitions/src/main/resources/thunderjet/mod-finance/features/ledger-fiscal-year-sequential-rollovers.feature, acquisitions/src/main/resources/thunderjet/mod-finance/finance.feature, acquisitions/src/test/java/org/folio/FinanceApiTest.java
[MODFISTO-436](https://issues.folio.org/browse/MODFISTO-436)
Add testcases for fiscal year rollover
=> MODFISTO-436 add test cases for fiscal year rollover

acquisitions/src/main/resources/thunderjet/cross-modules/features/rollover-with-closed-order.feature
* https://issues.folio.org/browse/MODORDERS-904
=> MODORDERS-904 check poline with empty encumbrance skipped from processing during rollover

acquisitions/src/main/resources/thunderjet/mod-consortia/features/consortium.feature, acquisitions/src/main/resources/thunderjet/mod-consortia/features/user-tenant-associations.feature
Resolves: [FAT-7387](https://issues.folio.org/browse/FAT-7387) Karate test fail in 'mod-consortia'
=> [FAT-7387] Karate test fail in 'mod-consortia'

acquisitions/src/main/resources/thunderjet/mod-finance/features/ledger-fiscal-year-skip-previous-year-encumbrance.feature, acquisitions/src/main/resources/thunderjet/mod-finance/finance.feature, acquisitions/src/test/java/org/folio/FinanceApiTest.java
[MODFISTO-441](https://issues.folio.org/browse/MODFISTO-441)
=> [MODFISTO-441] - Add the ability to skip the transaction if it is from the previous year

mod-circulation/src/main/resources/vega/mod-circulation/features/requests.feature, mod-circulation/src/main/resources/vega/mod-circulation/features/tlr-requests.feature
Cover new functionality intoduced in [CIRC-1834](https://issues.folio.org/browse/CIRC-1834) with tests
=> FAT-7216: Tests for CIRC-1834

mod-oai-pmh/src/test/resources/firebird/oaipmh/oaipmh-enhancement.feature, mod-oai-pmh/src/test/resources/karate-config.js
[MODOAIPMH-528](https://issues.folio.org/browse/MODOAIPMH-528) - Karate test: ListRecords - Verify elements of the resumption token
=> MODOAIPMH-528 - Karate test: ListRecords - Verify elements of the resumption token

mod-consortia/src/main/resources/thunderjet/mod-consortia/features/user-tenant-associations.feature
Related PR: https://github.com/folio-org/mod-consortia/pull/89
=> MODCON-81. Add permission to system user to delete users #89

mod-consortia/src/main/resources/karate-config.js, mod-consortia/src/main/resources/thunderjet/mod-consortia/features/user-tenant-associations.feature
Approach
Do not use placeholders for unknown property
=> Fix scheduled build

mod-consortia/src/main/resources/karate-config.js, mod-consortia/src/main/resources/thunderjet/mod-consortia/features/user-tenant-associations.feature
Remove mobius placeholder occurence
=> Fix failed scheduled build

mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/users-positive-scenarios.feature
[MODBULKOPS-127](https://issues.folio.org/browse/MODBULKOPS-127)
Added scenario for /bulk-operations/list-users endpoint
=> MODBULKOPS-127 - scenario for /bulk-operations/list-users endpoint

mod-consortia/src/main/resources/thunderjet/mod-consortia/consortia-junit.feature, mod-consortia/src/main/resources/thunderjet/mod-consortia/features/user-tenant-associations.feature
https://issues.folio.org/browse/MODCON-83
=> [MODCON-83]-Added custom-field check

acquisitions/src/main/resources/thunderjet/mod-data-export-spring/data-export-spring-junit.feature
=> [FAT-7535] - Increased the readTimeout

mod-consortia/src/main/resources/thunderjet/mod-consortia/features/publish-coordinator.feature, mod-consortia/src/main/resources/thunderjet/mod-consortia/features/sharing-setting.feature
Resolves: [MODCON-87](https://issues.folio.org/browse/MODCON-87) Cover missed ECS Scenarios with karate tests
1. Adjust existing tests to work with 3 tenants and add additional verification for response body
2. Add test for ERROR status code
=> [MODCON-87] Refactor/adjust existing tests. Add test case for ERROR status code

mod-circulation/src/main/resources/vega/mod-circulation/features/requests.feature
Resolves: [FAT-7997](https://issues.folio.org/browse/FAT-7997)
=> FAT-7997 fix test according to the logic in CIRC-1875

mod-consortia/src/main/resources/thunderjet/mod-consortia/consortia-junit.feature, mod-consortia/src/main/resources/thunderjet/mod-consortia/features/consortia-skip-not-required-user-types.feature, mod-consortia/src/main/resources/thunderjet/mod-consortia/features/sharing-setting.feature, mod-consortia/src/main/resources/thunderjet/mod-consortia/features/user-tenant-associations.feature, mod-consortia/src/main/resources/thunderjet/mod-consortia/features/util/initData.feature
Add more karate tests for stories:
https://issues.folio.org/browse/MODCON-78
https://issues.folio.org/browse/MODUSERS-384
=> FAT-8079. MODCON-78. Add additional consortia tests

mod-search/src/test/resources/spitfire/mod-search/search/resource-job-ids-search.feature
Fix search resource job by id execution status
[FAT-7608](https://issues.folio.org/browse/FAT-7608)
=> FAT-7608: Fix search resource job by id execution status

acquisitions/src/main/resources/thunderjet/mod-finance/features/ledger-fiscal-year-preview-rollover.feature
=> [FAT-8535] - Fix preview rollover feature

mod-circulation/src/main/resources/vega/mod-circulation/features/requests.feature
Resolves [FAT-8538](https://issues.folio.org/browse/FAT-8538)
=> FAT-8538: Fix tests for allowed service points endpoint

mod-circulation/src/main/resources/vega/mod-circulation/features/requests.feature
Covers: [FAT-6351](https://issues.folio.org/browse/FAT-6351)
Check that only available service points will be available for request when Item's status checked out
=> FAT-6351 Request - allowed service points Karate test

mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/items.feature
[MODBULKOPS-139](https://issues.folio.org/browse/MODBULKOPS-139) - Separate notes in different columns
=> MODBULKOPS-139 - update preview

mod-consortia/src/main/resources/thunderjet/mod-consortia/features/consortia-system-users-verification.feature
https://issues.folio.org/browse/UICONSET-69
=> UICONSET-69. Add necessary permissions for karate tests

mod-circulation/src/main/resources/vega/mod-circulation/features/requests.feature
Fix new test for [FAT-6351](https://issues.folio.org/browse/FAT-6351).
=> FAT-6351: Fix test for allowed service points endpoint

mod-consortia/src/main/resources/thunderjet/mod-consortia/features/consortia-system-users-verification.feature
https://issues.folio.org/browse/UICONSET-99
Increased system user's length of permissions
https://github.com/folio-org/mod-consortia/pull/120
=> [UICONSET-99] - Increased expected permission length

mod-consortia/src/main/resources/thunderjet/mod-consortia/features/consortia-system-users-verification.feature
Changes https://github.com/folio-org/mod-consortia/pull/122/files
https://issues.folio.org/browse/UICONSET-88
Increased the number of system user's permission
=> [UICONSET-88] - Increased expected permission length

mod-consortia/src/main/resources/thunderjet/mod-consortia/features/consortia-skip-not-required-user-types.feature, mod-consortia/src/main/resources/thunderjet/mod-consortia/features/tenant.feature
https://issues.folio.org/browse/MODCON-103
- Created users with different type before creating tenant 
- Checking them after tenants are registered
=> [MODCON - 103] - Skip shadow users when migrating existing users

mod-data-export/src/test/resources/firebird/dataexport/features/delete-job-execution.feature, mod-data-export/src/test/resources/firebird/dataexport/features/export-for-authority.feature, mod-data-export/src/test/resources/firebird/dataexport/features/export-for-cql.feature, mod-data-export/src/test/resources/firebird/dataexport/features/export-for-holdings.feature, mod-data-export/src/test/resources/firebird/dataexport/features/export.feature, mod-data-export/src/test/resources/samples/authority.json
[FAT-8123](https://issues.folio.org/browse/FAT-8123) - fix entity for authority, progress
=> FAT-8123 - fix entity for authority 

mod-kb-ebsco-java/src/main/resources/spitfire/mod-kb-ebsco-java/features/setup/destroy.feature
=> FAT-8304 Fix agreement deletion

acquisitions/src/main/resources/samples/mod-gobi/po-unlisted-print-monograph.xml, acquisitions/src/main/resources/samples/mod-gobi/unlisted-print-monograph.json, acquisitions/src/main/resources/thunderjet/mod-gobi/features/gobi-api-tests.feature
https://issues.folio.org/browse/MODGOBI-195
Created a test where we create an invalid custom mapping and later using it to create an order.
=> [MODGOBI-195] - error handling improvement

edge-oai-pmh/src/main/resources/firebird/edge-oai-pmh/edge-oai-pmh-junit.feature, mod-data-export/src/test/resources/firebird/dataexport/features/consortia-export.feature, mod-data-export/src/test/resources/firebird/dataexport/features/consortia/export.feature, mod-data-export/src/test/resources/samples/marc_consortia_record.json, mod-oai-pmh/src/test/resources/common/destroy-data.feature, mod-oai-pmh/src/test/resources/common/setup-users.feature, mod-oai-pmh/src/test/resources/common/tenant.feature
[FAT-7648](https://issues.folio.org/browse/FAT-7648) - data export for consortia
=> FAT-7648 - data export for consortia 

acquisitions/src/main/resources/thunderjet/mod-finance/features/ledger-fiscal-year-preview-rollover.feature
https://issues.folio.org/browse/FAT-8986
=> FAT-8986. Karate test ledger-fiscal-year-preview-rollover.feature

acquisitions/src/main/resources/thunderjet/mod-orders/features/moving_expended_value_to_newly_created_encumbrance.feature
=> [MODORDERS-943] - Encumbrance status becomes "Unreleased" after changing fund distribution

mod-search/src/test/resources/samples/test-data/authorities/CorporateAuthority.json, mod-search/src/test/resources/samples/test-data/authorities/MeetingAuthority.json, mod-search/src/test/resources/samples/test-data/authorities/PersonalAuthority.json, mod-search/src/test/resources/samples/test-data/authorities/sourceFiles/AuthoritySourceFIle.json, mod-search/src/test/resources/samples/test-data/authorities/sourceFiles/AuthoritySourceFIleSecond.json, mod-search/src/test/resources/samples/test-data/authorities/sourceFiles/AuthoritySourceFIleThird.json, mod-search/src/test/resources/spitfire/mod-search/set-up/create-test-data.feature, mod-search/src/test/resources/spitfire/mod-search/set-up/tenant-init.feature
Fix Karate test  [spitfire/mod-search] SearchApiTest {1} spitfire/mod-search/set-up/tenant-init.feature
https://issues.folio.org/browse/FAT-8131
=> fix(spitfire/mod-search) fix set-up/tenant-init.feature test

acquisitions/src/main/resources/thunderjet/mod-orders/features/moving_expended_value_to_newly_created_encumbrance.feature
=> [FAT-9149] - Resolved moving expended amount when editing fund distribution for POL test

mod-search/src/test/resources/spitfire/mod-search/browse/contributor-browse.feature
Fix spitfire/mod-search/browse/contributor-browse.feature
Added "contributorTypeId": [] empty array in expected data 
(https://issues.folio.org/browse/FAT-7537)
=> fix(spitfire/mod-search) fix browse/contributor-browse.feature test

mod-search/src/test/resources/spitfire/mod-search/search/resource-job-ids-search.feature
Fix  spitfire/mod-search/search/resource-job-ids-search.feature
Change status into COMPLETED
https://jenkins-aws.indexdata.com/job/Testing/job/Scheduled%20Karate%20Tests/968/cucumber-html-reports/report-feature_361_3779954613.html
=> fix(spitfire/mod-search) fix search/resource-job-ids-search.feature test

mod-search/src/test/resources/spitfire/mod-search/browse/contributor-browse.feature, mod-search/src/test/resources/spitfire/mod-search/search/resource-job-ids-search.feature
Fix browse/contributor-browse.feature
Added         "contributorTypeId": [],
https://issues.folio.org/browse/FAT-7537
=> fix(spitfire/mod-search) fix browse/contributor-browse.feature

mod-users-bl/src/main/resources/volaris/mod-users-bl/features/users-bl.feature
To fix the issue caused in FAT-9194
Update the user's first name check from Admin to Karate.
=> [FAT-9194] - Updated username from Admin to Karate 

mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/items.feature
[MODBULKOPS-151](https://issues.folio.org/browse/MODBULKOPS-151) - Columns for all item note types
=> MODBULKOPS-151 - Columns for all item note types

mod-quick-marc/src/main/resources/karate-config.js
upgraded timeout interval
Closes: FAT-9233
https://issues.folio.org/browse/FAT-9212
=> fix(spitfire/mod-quick-marc)(fix setup.feature):

mod-data-export/src/test/resources/firebird/dataexport/features/job-profiles.feature
[MDEXP-109](https://issues.folio.org/browse/MDEXP-109) - Return list of the job profiles used in completed jobs
=> MDEXP-109 - Return list of the job profiles used in completed jobs

mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/holdings.feature
[MODBULKOPS-149](https://issues.folio.org/browse/MODBULKOPS-149) - Separate holdings notes by note type
=> MODBULKOPS-149 - Separate holdings notes by note type

mod-ldp/src/main/resources/thor/mod-ldp/features/databaseConnection.feature
Correct db connection info for mod-ldp test
=> mod-ldp - Fix tenant connection settings

mod-consortia/src/main/resources/thunderjet/mod-consortia/features/consortia-system-users-verification.feature, mod-consortia/src/main/resources/thunderjet/mod-consortia/features/user-tenant-associations.feature
https://issues.folio.org/browse/MODCON-122
https://issues.folio.org/browse/MODCON-121
https://issues.folio.org/browse/MODCON-125
Increased size 83 -> 89 and reverted barcode check
=> [MODCON - 121/122] - Increased size of permissions after 9 new permissions

mod-search/src/test/resources/spitfire/mod-search/browse/call-number-browse.feature
Fix call-number-browse.feature match failure 
change totalRecords count 
https://issues.folio.org/browse/FAT-9630
=> fix(call-number-browse): fix total records count 

mod-kb-ebsco-java/src/main/resources/karate-config.js
Fix time elapsed issue
Enhance time interval 
https://issues.folio.org/browse/FAT-9722
=> fix(mod-kb-ebsco-java): fix time elapsed issue

edge-oai-pmh/src/main/resources/firebird/edge-oai-pmh/features/edge-oai-pmh.feature
[FAT-7626](https://issues.folio.org/browse/FAT-7626) - Karate test fail: [firebird/edge-oai-omh] EdgeOaiPmhApiTest {2}  firebird/edge-oai-pmh/features/edge-oai-pmh.feature
Change versions, path.
=> FAT-7626 - Karate test fail: [firebird/edge-oai-omh] EdgeOaiPmhApiTest {2}  firebird/edge-oai-pmh/features/edge-oai-pmh.feature

edge-oai-pmh/src/main/resources/firebird/edge-oai-pmh/features/edge-oai-pmh.feature, edge-oai-pmh/src/main/resources/firebird/edge-oai-pmh/features/init_data/update-configuration.feature
[FAT-7626](https://issues.folio.org/browse/FAT-7626) - Karate test fail: [firebird/edge-oai-omh] EdgeOaiPmhApiTest {2}  firebird/edge-oai-pmh/features/edge-oai-pmh.feature
Update mod config.
=> FAT-7626 Fixed config

edge-fqm/pom.xml, edge-fqm/src/main/resources/corsair/edge-fqm/edge-fqm-junit.feature, edge-fqm/src/main/resources/corsair/edge-fqm/features/edge-entity-types.feature, edge-fqm/src/main/resources/corsair/edge-fqm/features/edge-query.feature, edge-fqm/src/main/resources/karate-config.js, edge-fqm/src/main/resources/logback-test.xml, edge-fqm/src/test/java/org/folio/EdgeFqmTest.java, mod-fqm-manager/src/main/resources/corsair/mod-fqm-manager/features/query.feature, pom.xml
=> EDGFQM-13: Add edge-fqm integration tests

mod-circulation/src/main/resources/vega/mod-circulation/features/loans.feature
[FAT-9644](https://issues.folio.org/browse/FAT-9644)
=> FAT-9644: Fix test to avoid attempting to call mod-circulation-item

mod-search/src/test/resources/samples/test-data/authorities/corporate-authority.json
fix LCCN identifierTypeId.
Replace previous identifierTypeId with existing valid LCCN identifierTypeId.
https://issues.folio.org/browse/FAT-9647
=> fix(identifier-type): fix LCCN identifierTypeId.

acquisitions/src/main/resources/karate-config.js, acquisitions/src/main/resources/thunderjet/mod-finance/reusable/createRestrictedFund.feature, acquisitions/src/main/resources/thunderjet/mod-orders/features/open-order-with-restricted-locations.feature, acquisitions/src/main/resources/thunderjet/mod-orders/orders.feature, acquisitions/src/test/java/org/folio/OrdersApiTest.java
https://issues.folio.org/browse/MODORDERS-969
Added test verifies that desired validations are present
=> [MODORDERS-969] - Opening and editing POs with location-restricted funds

edge-fqm/src/main/resources/corsair/edge-fqm/features/edge-entity-types.feature, edge-fqm/src/main/resources/corsair/edge-fqm/features/edge-query.feature, edge-fqm/src/main/resources/karate-config.js
Fix expected response code in edge-fqm test. Also update API key in edge-fqm config file.
=> Fix edge-fqm response code

mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/items.feature
to cover the issue described in https://issues.folio.org/browse/FAT-9972
=> FAT-9972: ModBulkOperationsApiTest items.feature fix

edge-fqm/src/main/resources/karate-config.js
Use the correct pre-generated API key for edge-fqm-manager. See https://folio-project.slack.com/archives/C03SY8T46EM/p1703666350738529?thread_ts=1703177675.754229&cid=C03SY8T46EM for more details.
=> [EDGFQM-13] Update edge-fqm api key

acquisitions/src/main/resources/thunderjet/cross-modules/cross-modules-junit.feature, acquisitions/src/main/resources/thunderjet/cross-modules/cross-modules.feature, acquisitions/src/main/resources/thunderjet/mod-invoice/invoice-junit.feature, acquisitions/src/main/resources/thunderjet/mod-invoice/invoice.feature
https://issues.folio.org/browse/MODINVOICE-93
=> MODINVOICE-93. Update karate tests with new permission

acquisitions/src/main/resources/thunderjet/cross-modules/cross-modules-junit.feature, acquisitions/src/main/resources/thunderjet/cross-modules/cross-modules.feature, acquisitions/src/main/resources/thunderjet/mod-invoice/invoice-junit.feature, acquisitions/src/main/resources/thunderjet/mod-invoice/invoice.feature
https://issues.folio.org/browse/MODINVOICE-93
=> [MODINVOICE-93] Add support of invoice cancel permission

mod-fqm-manager/src/main/resources/corsair/mod-fqm-manager/features/entity-types.feature, mod-fqm-manager/src/main/resources/corsair/mod-fqm-manager/features/query.feature, mod-fqm-manager/src/main/resources/corsair/mod-fqm-manager/features/util/add-query-data.feature, mod-fqm-manager/src/main/resources/corsair/mod-fqm-manager/fqm-junit.feature
=> MODFQMMGR-93: new entity type pol

acquisitions/src/main/resources/thunderjet/cross-modules/features/check-order-re-encumber-after-preview-rollover.feature
=> Added retry to Check order re-encumber after preview rollover

teams-assignment.json
https://issues.folio.org/browse/RANCHER-1168
=> remove slack notofication for thor team

mod-batch-print/pom.xml, mod-batch-print/src/main/resources/karate-config.js, mod-batch-print/src/main/resources/logback-test.xml, mod-batch-print/src/main/resources/odin/mod-batch-print/batch-print-junit.feature, mod-batch-print/src/main/resources/odin/mod-batch-print/features/batch-print.feature, mod-batch-print/src/main/resources/odin/mod-batch-print/features/samples/mail.json, mod-batch-print/src/main/resources/odin/mod-batch-print/features/samples/print-entry-updated.json, mod-batch-print/src/main/resources/odin/mod-batch-print/features/samples/print-entry.json, mod-batch-print/src/test/java/org/folio/BatchPrintApiTests.java, pom.xml, teams-assignment.json
MODBATPRNT-3  To test integration of mod-batch-print module
Create test case for all endpoints positive case and also check some error handling with invalid request
=> MODBATPRNT-3 Add integration tests for mod-batch-print

teams-assignment.json
https://issues.folio.org/browse/RANCHER-1124
=> RANCHER-1124 modify team assignment template

mod-data-export/src/test/resources/firebird/dataexport/features/consortia/tenant.feature
=> FAT-10792 align data-export consortia test with schema changes

mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/holdings.feature
=> FAT-9973 align bulk-edit holdings test with schema changes

acquisitions/src/main/resources/thunderjet/mod-finance/features/ledger-fiscal-year-skip-previous-year-encumbrance.feature
=> Increased retry timeout

mod-consortia/src/main/resources/thunderjet/mod-consortia/features/consortia-user-type-update.feature
https://issues.folio.org/browse/MODUSERS-421
added two user one with system user type with same username, both should be stored. Other type users shouldn't
=> [MODUSERS-421] - Disable username uniqueness validation for system users

mod-data-export/src/test/resources/firebird/dataexport/features/export.feature
https://issues.folio.org/browse/FAT-11409
data export feature Karate tests failure
pauses were added for the cases, that exceeded Read timed-out and retry attempts
=> FAT-11409: Karate test fail. export feature

data-import/src/main/resources/folijet/data-import/samples/holding.json
The main purpose is  to fix this test - Karate test fail: [folijet/mod-inventory] ModInventoryTests {2}  folijet/mod-inventory/features/inventoryFeatureTest.feature
Extra Holdings fields removed.
JIRA: https://issues.folio.org/browse/FAT-9975
=> Karate test failing fixed.

mod-data-export/src/test/resources/firebird/dataexport/features/consortia/export.feature
=> FAT-11484 increase retry interval for consortium data-export

mod-fqm-manager/src/main/resources/corsair/mod-fqm-manager/features/query.feature, mod-fqm-manager/src/main/resources/corsair/mod-fqm-manager/features/util/add-query-data.feature
Add test for handling deleted records in mod-fqm-manager
=> MODFQMMGR-125: Add deleted record test

mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/holdings.feature, mod-data-export/src/test/resources/firebird/dataexport/features/consortia/consortium.feature, mod-data-export/src/test/resources/firebird/dataexport/features/consortia/export.feature, mod-data-export/src/test/resources/firebird/dataexport/features/delete-job-execution.feature, mod-data-export/src/test/resources/firebird/dataexport/features/export-for-authority.feature, mod-data-export/src/test/resources/firebird/dataexport/features/export-for-cql.feature, mod-data-export/src/test/resources/firebird/dataexport/features/export-for-holdings.feature, mod-data-export/src/test/resources/firebird/dataexport/features/export.feature, mod-data-export/src/test/resources/firebird/dataexport/features/get-job-execution.feature, mod-data-export/src/test/resources/firebird/dataexport/features/quick-export.feature
=> FAT-11717 increase data-exeport retry intervals

acquisitions/src/main/resources/thunderjet/mod-orders/features/independent-acquisitions-unit-for-ordering-and-receiving.feature
https://issues.folio.org/browse/MODORDERS-1010
Rename all field occurrences.
=> [MODORDERS-1010] - Change "caption" to "Display summary" for checkin and receiving collections

mod-consortia/src/main/resources/thunderjet/mod-consortia/features/tenant.feature
=> FAT-11718 increase interval for mod-consortia test

mod-source-record-manager/src/main/resources/folijet/mod-source-record-manager/features/job-execution.feature
=> FAT-11415: Karate test fixing.

mod-oai-pmh/src/test/java/org/folio/ModOaiPmhTests.java, mod-oai-pmh/src/test/resources/firebird/oaipmh/oaipmh-listRecords-sourceInventory.feature, mod-oai-pmh/src/test/resources/global/init_data/mod_inventory_init_data_single.feature, mod-oai-pmh/src/test/resources/samples/c375/holding-C375198.json, mod-oai-pmh/src/test/resources/samples/c375/holding2-C375198.json, mod-oai-pmh/src/test/resources/samples/c375/holding_not-suppressed-C375207.json, mod-oai-pmh/src/test/resources/samples/c375/holding_not-suppressed-updated-C375208.json, mod-oai-pmh/src/test/resources/samples/c375/holding_not-suppressed-updated-no-electr-acc-C375212.json, mod-oai-pmh/src/test/resources/samples/c375/holding_suppressed-C375198.json, mod-oai-pmh/src/test/resources/samples/c375/instance-C375198.json, mod-oai-pmh/src/test/resources/samples/c375/instance-suppressed-C375203.json, mod-oai-pmh/src/test/resources/samples/c375/instance-updated-C375938.json, mod-oai-pmh/src/test/resources/samples/c375/instance-updated-C375974.json, mod-oai-pmh/src/test/resources/samples/c375/item-C375209.json, mod-oai-pmh/src/test/resources/samples/c375/item-C375940.json, mod-oai-pmh/src/test/resources/samples/c375/item-updated-C375209.json, mod-oai-pmh/src/test/resources/samples/c375/item-updated-C375940.json, mod-oai-pmh/src/test/resources/samples/c375/item-updated-suppressed-C375212.json
[MODOAIPMH-501](https://issues.folio.org/browse/MODOAIPMH-501) - Karate test: ListRecords - Source Inventory - updated inventory records included in incremental harvest
=> MODOAIPMH-501 - Karate test: ListRecords - Source Inventory - updated inventory records included in incremental harvest

mod-source-record-manager/src/main/resources/folijet/mod-source-record-manager/features/job-execution.feature
=> FAT-11415: srm Karate test fixing.

acquisitions/src/main/resources/karate-config.js, acquisitions/src/main/resources/thunderjet/mod-orders/features/piece-audit-history.feature, acquisitions/src/main/resources/thunderjet/mod-orders/features/piece-batch-job.feature, acquisitions/src/main/resources/thunderjet/mod-orders/features/piece-status-transitions.feature, acquisitions/src/main/resources/thunderjet/mod-orders/features/poline-claiming-interval-checks.feature, acquisitions/src/main/resources/thunderjet/mod-orders/orders-junit.feature, acquisitions/src/main/resources/thunderjet/mod-orders/orders.feature, acquisitions/src/test/java/org/folio/OrdersApiTest.java
[MODORDERS-978](https://issues.folio.org/browse/MODORDERS-978) - Implement karate scenarios for Claiming feature functionality
=> [MODORDERS-978] - Scenarios for Claiming feature functionality

mod-source-record-manager/src/main/resources/folijet/mod-source-record-manager/features/job-execution.feature
To fix srm FAT tests.
Change assert to the match.
=> FAT-11415: srm tests fixing.

data-import/src/main/resources/folijet/data-import/features/data-import-multiple-records-from-marc-bib.feature
=> FAT-6493: data-import tests fixing.

data-import/src/main/resources/folijet/data-import/features/data-import-delete-logs.feature
fix karate test
assert correct value in response of job logs
=> FAT-9179 assert correct value in response of job logs

mod-lists/src/main/resources/corsair/mod-lists/features/delete.feature
Adds tests for the soft-deletion recently introduced into mod-lists.
=> [FAT-11792] Add Karate tests for mod-lists list soft deletion

data-import/src/main/resources/folijet/data-import/features/data-import-integration.feature, data-import/src/main/resources/folijet/data-import/features/data-import-multiple-records-from-marc-bib.feature, data-import/src/main/resources/folijet/data-import/features/import-edi-invoice.feature, data-import/src/main/resources/folijet/data-import/global/default-import-instance-holding-item.feature
=> FAT-6493: Fixing data-import FAT tests.

mod-fqm-manager/src/main/resources/corsair/mod-fqm-manager/features/query.feature
Update field name to fix failing query test
=> Update field name in failing query test

acquisitions/src/main/resources/samples/mod-orders/orderLines/multi-location-order-line.json, acquisitions/src/main/resources/thunderjet/mod-finance/reusable/createRestrictedFund.feature, acquisitions/src/main/resources/thunderjet/mod-orders/features/open-order-with-restricted-locations.feature
https://folio-org.atlassian.net/browse/MODORDERS-1020
Modify existing test to adopt it to modified location-fund-restrictions and make it more strict by checking the error parameter
=> [MODORDERS-1020] - Adjust Restricted Location + Fund validation rules

mod-inventory/src/main/resources/folijet/mod-inventory/features/inventoryFeatureTest.feature, mod-inventory/src/main/resources/folijet/mod-inventory/features/utils.feature, mod-inventory/src/main/resources/folijet/mod-inventory/inventory-junit.feature, mod-inventory/src/main/resources/folijet/mod-inventory/samples/record.json, mod-inventory/src/main/resources/folijet/mod-inventory/samples/snapshot.json
Modify test for instance soft delete to check if source record deleted
- Check record **state** to be DELETED
- Check to **suppressDiscovery** true
- Check **deleted** true
- Check **leaderRecordStatus** true
=> [MODINV-961] Modify test for instance soft delete to check if source record deleted

acquisitions/src/main/resources/thunderjet/mod-orders/features/piece-audit-history.feature, acquisitions/src/main/resources/thunderjet/mod-orders/features/piece-batch-job.feature, acquisitions/src/main/resources/thunderjet/mod-orders/features/unreceive-piece-and-check-order-line.feature
Add proper retries to Thunderjet tests
=> Stabilize Thunderjet karate tests

mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/holdings.feature, mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/instances.feature, mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/items.feature, mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/users-negative-scenarios.feature, mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/users-positive-scenarios.feature, mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/mod-bulk-operations-junit.feature
=> Increase pauses for bulk edit tests

mod-dcb/src/test/java/org/folio/ModDCBTest.java, pom.xml
=> Enable mod-dcb

acquisitions/src/main/resources/samples/mod-orders/orderLines/multi-location-order-line.json, acquisitions/src/main/resources/thunderjet/mod-orders/features/open-order-with-restricted-locations.feature
https://folio-org.atlassian.net/browse/MODORDERS-1020
Fixed based on scenario:
-    Fund A in POL     - Loc1 [createRestrictedFund.feature]
-    Fund B in POL     - not exists
-    Locations in POL  - Loc2 [multi-location-order-line.json]
-    Result:           - Fail (Fund A doesn't have valid location)
=> [MODORDERS-1021] - Fixed test for restricted Location + Fund validation

acquisitions/src/main/resources/samples/mod-gobi/unlisted-print-serial.json, acquisitions/src/main/resources/thunderjet/mod-gobi/features/gobi-api-tests.feature
[https://folio-org.atlassian.net/browse/MODGOBI-202](https://folio-org.atlassian.net/browse/MODGOBI-202)
Provide a fix to failing test of the previous branch for this ticket
=> [MODGOBI-202] Create additional karate tests for mod-gobi module

mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/items.feature
=> MODBULKOPS-203 fix tests after adding new column

mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/items.feature
=> MODBULKOPS-203 decrease timeouts for bulk-edit item tests

acquisitions/src/main/resources/thunderjet/cross-modules/features/cancel-invoice-linked-to-order.feature
[MODFISTO-475](https://folio-org.atlassian.net/browse/MODFISTO-475) - Wrong encumbrance calculation when paying a credit
Added a new scenario to the test `cancel-invoice-linked-to-order`.
[Related PR in mod-finance-storage](https://github.com/folio-org/mod-finance-storage/pull/395).
=> [MODFISTO-475] Cancel a paid invoice with a single credit

mod-data-export/src/test/resources/firebird/dataexport/features/consortia/export.feature, mod-data-export/src/test/resources/firebird/dataexport/features/delete-job-execution.feature, mod-data-export/src/test/resources/firebird/dataexport/features/export-for-authority.feature, mod-data-export/src/test/resources/firebird/dataexport/features/export-for-holdings.feature
=> Karate for authority-holdings exports

mod-data-export/src/test/resources/firebird/dataexport/features/delete-job-execution.feature, mod-data-export/src/test/resources/firebird/dataexport/features/export-for-cql.feature, mod-data-export/src/test/resources/firebird/dataexport/features/export.feature, mod-data-export/src/test/resources/firebird/dataexport/features/job-profiles.feature
=> Karate for data-exports refactoring

edge-rtac/src/main/resources/core_platform/edge-rtac/features/rtac.feature, edge-rtac/src/main/resources/core_platform/edge-rtac/features/samples/holdings/holdings-entity-request.json, edge-rtac/src/main/resources/core_platform/edge-rtac/features/samples/instance/instance-entity-request.json, edge-rtac/src/main/resources/core_platform/edge-rtac/features/samples/item/item-entity-request.json, edge-rtac/src/main/resources/core_platform/edge-rtac/features/util/initData.feature, edge-rtac/src/main/resources/core_platform/edge-rtac/rtac-junit.feature, edge-rtac/src/main/resources/karate-config.js, edge-rtac/src/main/resources/logback-test.xml, edge-rtac/src/test/java/org/folio/EdgeRtacTests.java
After added new fields on rtac response, so updated edge-rtac responses. 
- Added new match asserts in order to check new fields
=> EDGRTAC-81: Fix edge rtac scenarios

mod-fqm-manager/src/main/resources/corsair/mod-fqm-manager/features/query.feature, mod-fqm-manager/src/main/resources/corsair/mod-fqm-manager/features/util/add-query-data.feature, mod-fqm-manager/src/main/resources/corsair/mod-fqm-manager/fqm-junit.feature
=> MODFQMMGR-198: new test for new entity type and operators

data-import/src/main/resources/folijet/data-import/features/data-import-integration.feature, mod-data-export/src/test/resources/firebird/dataexport/features/consortia/export.feature, mod-data-export/src/test/resources/firebird/dataexport/features/export-for-authority.feature, mod-data-export/src/test/resources/firebird/dataexport/features/export-for-cql.feature, mod-data-export/src/test/resources/firebird/dataexport/features/export-for-holdings.feature, mod-data-export/src/test/resources/firebird/dataexport/features/export.feature, mod-data-export/src/test/resources/firebird/dataexport/features/job-profiles.feature
=> MDEXP-739 fix tests

mod-data-export/src/test/resources/firebird/dataexport/features/job-profiles.feature
=> MDEXP-680 support new default profiles

mod-circulation/src/main/resources/vega/mod-circulation/features/util/initData.feature
Covers: [FAT-12226](https://folio-org.atlassian.net/browse/FAT-12226)
Fix "Failed to apply rules" Karate tests failure
=> FAT-12226 Fix - Failed to apply rules

mod-circulation/src/main/resources/vega/mod-circulation/features/tlr-requests.feature
Covers: [FAT-12226](https://folio-org.atlassian.net/browse/FAT-12226)
Fix "Failed to apply rules" Karate tests failure
=> FAT-12226 Fix Failed to apply rules

acquisitions/src/main/resources/samples/mod-orders/routingLists/a1d13648-347b-4ac9-8c2f-5bc47248b87e.json, acquisitions/src/main/resources/thunderjet/mod-orders/features/routing-lists-api.feature, acquisitions/src/main/resources/thunderjet/mod-orders/orders.feature, acquisitions/src/test/java/org/folio/OrdersApiTest.java
[https://folio-org.atlassian.net/browse/MODORDERS-1006](https://folio-org.atlassian.net/browse/MODORDERS-1006)
Added tests to verify routing list api:
* Make sure all api methods are working correctly
=> [MODORDERS-1006] Create Routing Lists API

acquisitions/src/main/resources/thunderjet/mod-finance/reusable/createRestrictedFund.feature
https://folio-org.atlassian.net/browse/MODORDERS-1046
Update tests to fit new structure
=> [MODORDERS-1046] - Retrieve holdings from member tenants for Restrict by Locations feature

edge-inn-reach/src/main/resources/karate-config.js, edge-inn-reach/src/main/resources/volaris/edge-inn-reach/edge-inn-reach-junit.feature, edge-inn-reach/src/test/java/org/folio/EdgeInnReachApiTest.java
To fix the failed issue reported in https://poc-report-portal.ci.folio.org/ui/#junit5-integration/launches/all/228/96884/96886/log?item0Params=filter.eq.hasStats%3Dtrue%26filter.eq.hasChildren%3Dfalse%26filter.in.issueType%3Dti001
Removed the underscore from tenant name.
=> FAT-12663 - Fixed the issue with underscore test tenant names.

edge-oai-pmh/src/main/resources/firebird/edge-oai-pmh/features/edge-oai-pmh.feature, mod-oai-pmh/src/test/resources/firebird/oaipmh/oaipmh-listRecords-additional.feature, mod-oai-pmh/src/test/resources/samples/c375/instance-updated-C375938.json, mod-oai-pmh/src/test/resources/samples/c375/instance-updated-C375974.json
=> fix: oai-pmh tests after RMB OL upgrade

data-import/src/main/resources/folijet/data-import/features/data-import-integration.feature, data-import/src/main/resources/folijet/data-import/samples/samples_for_upload/default-marc-bib-rules.json
Feature [folijet/data-import] DataImportApiTest {3} folijet/data-import/features/data-import-integration.feature
[FAT - 12652](https://folio-org.atlassian.net/browse/FAT-12652)
fix issues
=> FAT - 12652 Feature [folijet/data-import] DataImportApiTest {3} folijet/data-import/features/data-import-integration.feature

mod-quick-marc/pom.xml, mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/marc-bib-update.feature, mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/setup/setup.feature, mod-quick-marc/src/test/java/org/folio/QuickMarcSimulation.scala
Implement test for Gatling execution
[FAT-12636](https://folio-org.atlassian.net/browse/FAT-12636)
implement marc bib update for gatling execution
Ran on spitfire dev rancher
Gatling console reports:
Html gatling report generated:
Regular karate tests with junit still run without errors:
=> feat(quick-marc): Implement test for Gatling execution

mod-data-export/src/test/resources/firebird/dataexport/features/mapping-profiles.feature, mod-data-export/src/test/resources/samples/mapping-profile/mapping_profile_invalid_suppression.json
[MDEXP-726](https://folio-org.atlassian.net/browse/MDEXP-726) - Extend mapping profile schema
=> MDEXP-726 - Extend mapping profile schema

data-import/src/main/resources/folijet/data-import/features/data-import-integration.feature, mod-source-record-manager/src/main/resources/folijet/mod-source-record-manager/features/job-execution.feature, mod-source-record-manager/src/main/resources/karate-config.js, mod-source-record-storage/src/main/resources/folijet/mod-source-record-storage/features/get-source-storage-records.feature, mod-source-record-storage/src/main/resources/karate-config.js
Feature [folijet/mod-source-record-manager] ModSourceRecordManagerTest {3} folijet/mod-source-record-manager/features/job-execution.feature
[FAT-12653 ](https://folio-org.atlassian.net/browse/FAT-12653)
=> FAT-12653 Feature [folijet/mod-source-record-manager] ModSourceRecordManagerTest {3} folijet/mod-source-record-manager/features/job-execution.feature

mod-data-export/src/test/resources/firebird/dataexport/features/delete-job-execution.feature, mod-data-export/src/test/resources/firebird/dataexport/features/job-profiles.feature
=> Fix data-export tests

mod-oai-pmh/src/test/resources/firebird/oaipmh/oaipmh-listRecords-additional.feature, mod-oai-pmh/src/test/resources/firebird/oaipmh/oaipmh-listRecords-sourceInventory.feature
Fix optimistic locking for oai-pmh
=> Update instance version oai-pmh

acquisitions/src/main/resources/thunderjet/mod-orders/features/title-instance-creation.feature, acquisitions/src/main/resources/thunderjet/mod-orders/orders.feature, acquisitions/src/test/java/org/folio/OrdersApiTest.java
[[MODORDERS-1081] Create instance when user adds receiving title to package order line](https://folio-org.atlassian.net/browse/MODORDERS-1081)
=> [MODORDERS-1081] Create instance when user adds receiving title to package order line

mod-reading-room/pom.xml, mod-reading-room/src/main/resources/karate-config.js, mod-reading-room/src/main/resources/logback-test.xml, mod-reading-room/src/main/resources/volaris/mod-reading-room/features/reading-room.feature, mod-reading-room/src/main/resources/volaris/mod-reading-room/features/samples/reading-room/reading-room-entity-request.json, mod-reading-room/src/main/resources/volaris/mod-reading-room/features/samples/service-point/service-point-entity-request.json, mod-reading-room/src/main/resources/volaris/mod-reading-room/features/util/initData.feature, mod-reading-room/src/main/resources/volaris/mod-reading-room/reading-room-init.feature, mod-reading-room/src/main/resources/volaris/mod-reading-room/reading-room-junit.feature, mod-reading-room/src/test/java/org/folio/ModReadingRoomApiTest.java, pom.xml, teams-assignment.json
Integration tests setup for mod-reading-room - https://folio-org.atlassian.net/browse/FAT-12779
A module is created for mod-reading-room in folio-integration-tests, the AfterAll and BeforeAll methods are working fine on running the module in rancher environment, contains scenarios on post, get, put and delete endpoints of mod-reading-room
=> FAT-12779 mod-reading-room setup

README.md, acquisitions/pom.xml
https://folio-org.atlassian.net/browse/FAT-12699
updated doc to avoid confusion to run tests
=> Updated to run gatling test

data-import/src/main/resources/folijet/data-import/features/data-import-integration.feature, mod-di-converter-storage/src/main/resources/folijet/mod-di-converter-storage/features/jobProfiles.feature, mod-di-converter-storage/src/main/resources/karate-config.js
[FAT-13223](https://folio-org.atlassian.net/browse/FAT-13223) Karate test fail: [folijet/data-import] DataImportApiTest {folijet/data-import/features/data-import-integration.feature}
[FAT-13224](https://folio-org.atlassian.net/browse/FAT-13224) Karate test fail: [folijet/mod-di-converter-storage] ModDataImportConverterStorageTest {3} folijet/mod-di-converter-storage/features/jobProfiles.feature
move modify before match
add test for validation
=> FAT-13223 Karate test fail: [folijet/data-import] DataImportApiTest {folijet/data-import/features/data-import-integration.feature}

mod-dcb/src/main/resources/karate-config.js, mod-dcb/src/main/resources/volaris/mod-dcb/features/cancelling-flow-for-borrower-flow.feature, mod-dcb/src/main/resources/volaris/mod-dcb/features/cancelling-flow-for-borrowing-pickup-flow.feature, mod-dcb/src/main/resources/volaris/mod-dcb/features/cancelling-flow-for-pickup-flow.feature, mod-dcb/src/main/resources/volaris/mod-dcb/features/cancelling-lending-flow.feature, mod-reading-room/src/main/resources/volaris/mod-reading-room/features/patron-permission.feature, mod-reading-room/src/main/resources/volaris/mod-reading-room/features/reading-room.feature, mod-reading-room/src/main/resources/volaris/mod-reading-room/features/samples/PatronGroup/create-patronGroup-request.json, mod-reading-room/src/main/resources/volaris/mod-reading-room/features/samples/User/create-user-request.json, mod-reading-room/src/main/resources/volaris/mod-reading-room/features/samples/access-log/access-log-entity-request.json, mod-reading-room/src/main/resources/volaris/mod-reading-room/features/samples/patron-permission/patron-permission-entity-request.json, mod-reading-room/src/main/resources/volaris/mod-reading-room/features/util/initData.feature, mod-reading-room/src/main/resources/volaris/mod-reading-room/reading-room-init.feature, mod-reading-room/src/test/java/org/folio/ModReadingRoomApiTest.java
purpose of this pr is : https://folio-org.atlassian.net/browse/FAT-12970
added positive and negative scenarios on patron permissions and access log 
=> FAT-12970 scenarios on patron permissions and access log

data-import/src/main/resources/folijet/data-import/samples/samples_for_upload/default-marc-bib-rules.json
[FAT-13491](https://folio-org.atlassian.net/browse/FAT-13491) Karate test fail: [folijet/data-import] DataImportApiTest folijet/data-import/features/data-import-integration.feature
update marc rules file
=> FAT-13491 Karate test fail: [folijet/data-import] DataImportApiTest folijet/data-import/features/data-import-integration.feature

mod-circulation/pom.xml, mod-circulation/src/main/resources/karate-config.js, mod-circulation/src/main/resources/vega/mod-circulation/features/loans.feature, mod-circulation/src/main/resources/vega/mod-circulation/features/util/initData.feature, mod-circulation/src/test/java/org/folio/CheckOutSimulation.scala
[FAT-12626](https://folio-org.atlassian.net/browse/FAT-12626)
Tested against Vega's Rancher environment
=> FAT-12626 Check out performance test

mod-di-converter-storage/src/main/resources/folijet/mod-di-converter-storage/features/jobProfiles.feature
Check error when creating job profile with standalone modify action profile
Implemented karate test for scenario https://foliotest.testrail.io//index.php?/cases/view/468244
=> [FAT-13540] Check error when creating job profile with standalone modify action profile

mod-quick-marc/src/main/resources/karate-config.js, mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/quick-marc-authority-records.feature, mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/quick-marc-bib-records.feature, mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/setup/setup.feature
=> FAT-13236 Fix mod-quick-marc tests psmagin Moments ago

mod-linked-data/pom.xml, mod-linked-data/src/main/resources/citation/mod-linked-data/features/create-resource.feature, mod-linked-data/src/main/resources/citation/mod-linked-data/features/samples/instance-expected-response.json, mod-linked-data/src/main/resources/citation/mod-linked-data/features/samples/instance-request.json, mod-linked-data/src/main/resources/citation/mod-linked-data/features/samples/work-expected-response.json, mod-linked-data/src/main/resources/citation/mod-linked-data/features/samples/work-request.json, mod-linked-data/src/main/resources/citation/mod-linked-data/features/util/post-resource.feature, mod-linked-data/src/main/resources/citation/mod-linked-data/linked-data-junit.feature, mod-linked-data/src/main/resources/karate-config.js, mod-linked-data/src/main/resources/logback-test.xml, mod-linked-data/src/test/java/org/folio/ModLinkedDataTest.java, pom.xml
Add integration tests for "create resource" feature of mod-linked-data
=> MODLD-373: Add initial tests for "create resource" feature of mod-linked-data

edge-fqm/src/main/resources/corsair/edge-fqm/features/edge-query.feature, mod-lists/src/main/resources/corsair/mod-lists/features/delete.feature, mod-lists/src/main/resources/corsair/mod-lists/features/export.feature
=> test longer retry

mod-lists/src/main/resources/corsair/mod-lists/lists-junit.feature
=> [FAT-13971] Add additional permissions for lists

mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/holdings.feature
[MODBULKOPS-227](https://folio-org.atlassian.net/browse/MODBULKOPS-227) - Holdings record's column names cleanup
* Fixed tests
=> MODBULKOPS-227 - Holdings record's column names cleanup

mod-inventory/src/main/resources/folijet/mod-inventory/features/consortia/consortia-inventory-junit.feature, mod-inventory/src/main/resources/folijet/mod-inventory/features/consortia/destroy-consortia.feature, mod-inventory/src/main/resources/folijet/mod-inventory/features/consortia/features/update-ownership.feature, mod-inventory/src/main/resources/karate-config.js, mod-inventory/src/test/java/org/folio/ConsortiaInventoryTest.java, mod-inventory/src/test/java/org/folio/ModInventoryTests.java
Add Karate test for changing ownership of Items on a shared Instance
1. Set up tenants for consortia and users for those tenants (Central, University and College). 
2. Create local Instance on University. Add 2 Holdings for that Instance. Create an Item for each of the Holdings.
3. Share the Instance
4. Add 1 Holdings for that Instance on College tenant
5. Send request to Update ownership for one of the Items specifying College as a targetTenantId and HoldingId created at step 4.
6. Verify that shared Instance has Holdings along with an appropriate Item on the College tenant 
7. Verify that shared Instance still has all the Holdings on the University tenant, but the moved Item is no longer there
=> [FAT-13773] Add Karate test for changing ownership of Items on a shared Instance

edge-oai-pmh/src/main/resources/firebird/edge-oai-pmh/features/edge-oai-pmh.feature, edge-oai-pmh/src/main/resources/samples/008_tag.json
[FAT-14296](https://folio-org.atlassian.net/browse/FAT-14296) - Karate test fail: [firebird/edge-oai-omh] EdgeOaiPmhApiTest {2}  firebird/edge-oai-pmh/features/edge-oai-pmh.feature
=> FAT-14296 - Karate test fail: [firebird/edge-oai-omh] EdgeOaiPmhApiTest {2}  firebird/edge-oai-pmh/features/edge-oai-pmh.feature

acquisitions/src/main/resources/thunderjet/mod-orders/features/bind-piece.feature, acquisitions/src/main/resources/thunderjet/mod-orders/reusable/create-circulation-policy.feature
[[MODORDERS-1131] Fix piece, item, title relationship in bind piece features](https://folio-org.atlassian.net/browse/MODORDERS-1131)
=> [MODORDERS-1131] Fix piece, item, title relationship in bind piece features

acquisitions/src/main/resources/thunderjet/mod-finance/features/budget-expense-classes.feature
MOFISTO-481
MODFIN-372
related prs
https://github.com/folio-org/mod-finance-storage/pull/414
https://github.com/folio-org/mod-finance/pull/251
changed expended Percentage based on new calculation, after excluding credit amount
=> [MODFIN-372/MODFISTO-481] - changed calculation of expendedPercentage

mod-data-export/src/test/resources/global/inventory_data_setup_util.feature, mod-data-export/src/test/resources/global/mod_inventory_init_data.feature, mod-data-export/src/test/resources/samples/holding.json, mod-data-export/src/test/resources/samples/holding_default.json, mod-data-export/src/test/resources/samples/holdings_source.json, mod-data-export/src/test/resources/samples/marc_consortia_record.json
[FAT-14297](https://folio-org.atlassian.net/browse/FAT-14297) - Karate test fail: [firebird/data-export] ModDataExportApiTest {12}  firebird/dataexport/features/consortia-export.feature
Add holdings sourceId.
=> FAT-14297 - Karate test fail: [firebird/data-export] ModDataExportApiTest {12}  firebird/dataexport/features/consortia-export.feature

mod-oai-pmh/src/test/resources/global/init_data/mod_inventory_init_data.feature, mod-oai-pmh/src/test/resources/samples/c375/holding-C375198.json, mod-oai-pmh/src/test/resources/samples/c375/holding2-C375198.json, mod-oai-pmh/src/test/resources/samples/c375/holding_not-suppressed-C375207.json, mod-oai-pmh/src/test/resources/samples/c375/holding_not-suppressed-updated-C375208.json, mod-oai-pmh/src/test/resources/samples/c375/holding_not-suppressed-updated-no-electr-acc-C375212.json, mod-oai-pmh/src/test/resources/samples/c375/holding_suppressed-C375198.json, mod-oai-pmh/src/test/resources/samples/holding.json
[FAT-14378](https://folio-org.atlassian.net/browse/FAT-14378) - Karate test fail: firebird/oaipmh/oaipmh-listRecords-additional.feature
Add holdings sourceId.
=> FAT-14378 - Karate test fail: firebird/oaipmh/oaipmh-listRecords-additional.feature

mod-search/src/test/resources/samples/test-data/holdings.json, mod-search/src/test/resources/spitfire/mod-search/filters/facet-search.feature
Add required sourceId in data setup
=> FAT-13946 mod-search: fix data setup

acquisitions/src/main/resources/thunderjet/mod-orders/features/bind-piece.feature, acquisitions/src/main/resources/thunderjet/mod-orders/reusable/create-circulation-policy.feature
https://folio-org.atlassian.net/browse/FAT-14355
fixed failing circulation policy and bind-piece feature and made some improvements
=> fixed karate tests for bind-piece feature

edge-oai-pmh/src/main/resources/firebird/edge-oai-pmh/features/init_data/create-holding.feature, edge-oai-pmh/src/main/resources/firebird/edge-oai-pmh/features/init_data/init-edge-oai-pmh.feature
[FAT-14365](https://folio-org.atlassian.net/browse/FAT-14365) - Karate test fail: [firebird/edge-oai-omh] EdgeOaiPmhApiTest {2}  firebird/edge-oai-pmh/features/edge-oai-pmh.feature
Fixed holdings source id.
Verified on rancher-firebird:
=> FAT-14365 - Karate test fail: [firebird/edge-oai-omh] EdgeOaiPmhApiTest {2}  firebird/edge-oai-pmh/features/edge-oai-pmh.feature

common-consortia/src/main/resources/common-consortia/affiliation.feature, mod-inventory/src/main/resources/folijet/mod-inventory/features/consortia/consortia-inventory-junit.feature, mod-inventory/src/main/resources/folijet/mod-inventory/features/consortia/destroy-consortia.feature, mod-inventory/src/main/resources/folijet/mod-inventory/features/consortia/features/update-ownership.feature, mod-inventory/src/main/resources/folijet/mod-inventory/samples/holdings_source.json
Adjust update-holdings-ownership test after implementation of endpoint
Add affiliation during test setting
=> [MODINV-1031] Adjust update-holdings-ownership test after implementation of endpoint

mod-circulation/src/main/resources/vega/mod-circulation/circulation-junit.feature, mod-circulation/src/main/resources/vega/mod-circulation/features/loans.feature, mod-circulation/src/main/resources/vega/mod-circulation/features/parallel-checkout.feature, mod-circulation/src/main/resources/vega/mod-circulation/features/requests.feature, mod-circulation/src/main/resources/vega/mod-circulation/features/samples/holdings-entity-request.json, mod-circulation/src/main/resources/vega/mod-circulation/features/samples/source-record-entity-request.json, mod-circulation/src/main/resources/vega/mod-circulation/features/util/initData.feature
Karate test fail: [vega/mod-circulation] ModCirculationTests {3} vega/mod-circulation/features/parallel-checkout.feature
Karate test fail: [vega/mod-circulation] ModCirculationTests {2} vega/mod-circulation/features/root.feature
fix missing required field source id
[FAT-14370](https://folio-org.atlassian.net/browse/FAT-14370)
[FAT-14143](https://folio-org.atlassian.net/browse/FAT-14143)
=> FAT-14370: Karate test fail: [vega/mod-circulation] ModCirculationTests {3} vega/mod-circulation/features/parallel-checkout.feature

mod-patron-blocks/src/main/resources/vega/mod-patron-blocks/features/samples/holdings-record-entity.json, mod-patron-blocks/src/main/resources/vega/mod-patron-blocks/features/samples/source-record-entity-request.json, mod-patron-blocks/src/main/resources/vega/mod-patron-blocks/features/util/initData.feature, mod-patron-blocks/src/main/resources/vega/mod-patron-blocks/patron-blocks-junit.feature
Karate test fail: [vega/mod-patron-blocks] ModPatronBlocksTests {3} vega/mod-patron-blocks/features/automatedPatronBlocks.feature
fix missing holding source id
[FAT-14382](https://folio-org.atlassian.net/browse/FAT-14382)
=> FAT-14382: Karate test fail: [vega/mod-patron-blocks] ModPatronBlocksTests {3} vega/mod-patron-blocks/features/automatedPatronBlocks.feature

mod-feesfines/src/main/resources/vega/mod-feesfines/features/automateFeeFines.feature, mod-feesfines/src/main/resources/vega/mod-feesfines/features/samples/holdings-entity-request.json, mod-feesfines/src/main/resources/vega/mod-feesfines/features/samples/source-record-entity-request.json, mod-feesfines/src/main/resources/vega/mod-feesfines/features/util/initData.feature, mod-feesfines/src/main/resources/vega/mod-feesfines/feesfines-junit.feature
fix missing holding source id
[FAT-14373](https://folio-org.atlassian.net/browse/FAT-14373)
[FAT-14374](https://folio-org.atlassian.net/browse/FAT-14374)
=> FAT-14373: Karate test fail: [vega/mod-feesfines] FeesFinesApiTests {6} vega/mod-feesfines/features/actualCostFeeFine.feature

acquisitions/src/test/java/org/folio/CrossModulesApiTest.java, acquisitions/src/test/java/org/folio/InvoicesApiTest.java
Karate tests are failing becuase of not complete credit feature because this contians multiple tickets  
Disabled 
https://folio-org.atlassian.net/browse/FAT-14405
https://folio-org.atlassian.net/browse/FAT-14406
https://folio-org.atlassian.net/browse/FAT-14407
=> disabled karate tests temporarily till completion of all credit features MODFIN-371/MODFISTO-482

mod-audit/src/main/resources/global/initTest.feature
To fix the failed test cases for mod-audit.
Source Id needs to be passed for holding creation. 
=> FAT-14368 - Fix for holding source id.

mod-consortia/src/main/resources/thunderjet/mod-consortia/consortia-junit.feature
karate test failing because of removed users
reverted back
=> reverted back removed user

mod-circulation/src/main/resources/vega/mod-circulation/features/requests.feature, mod-circulation/src/main/resources/vega/mod-circulation/features/tlr-requests.feature, mod-circulation/src/main/resources/vega/mod-circulation/features/util/initData.feature
https://jenkins-aws.indexdata.com/job/folioRancher/job/folioQualityGates/job/folioCiQualityGates/182/cucumber-html-reports/report-feature_261_4221679472.html
=> FAT-14143: fix source id call

mod-linked-data/src/main/resources/citation/mod-linked-data/features/samples/instance-expected-response.json, mod-linked-data/src/main/resources/citation/mod-linked-data/features/samples/instance-request.json, mod-linked-data/src/main/resources/citation/mod-linked-data/features/search-work.feature, mod-linked-data/src/main/resources/citation/mod-linked-data/features/util/search-resource.feature, mod-linked-data/src/main/resources/citation/mod-linked-data/linked-data-junit.feature, mod-linked-data/src/main/resources/karate-config.js, mod-linked-data/src/test/java/org/folio/ModLinkedDataTest.java
Integration tests for indexing work & instances in mod-search
=> MODLD-418: Integration tests for indexing work & instances in mod-search

acquisitions/src/main/resources/samples/mod-orders/routingLists/template-config.json, acquisitions/src/main/resources/thunderjet/mod-orders/features/routing-list-print-template.feature
https://folio-org.atlassian.net/browse/MODORDERS-1145
Related mod-orders PR: https://github.com/folio-org/mod-orders/pull/979
=> MODORDERS-1145. Add Instance Title to Context for template request

mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/items.feature
=> FAT-14939 fix bulk-edit tests

mod-linked-data/src/main/resources/citation/mod-linked-data/features/samples/instance-expected-response.json, mod-linked-data/src/main/resources/citation/mod-linked-data/features/samples/instance-request.json, mod-linked-data/src/main/resources/citation/mod-linked-data/features/samples/work-expected-response.json, mod-linked-data/src/main/resources/citation/mod-linked-data/features/samples/work-request.json, mod-linked-data/src/main/resources/citation/mod-linked-data/features/search-work.feature, mod-linked-data/src/main/resources/citation/mod-linked-data/features/util/search-resource.feature, mod-linked-data/src/main/resources/citation/mod-linked-data/linked-data-junit.feature
=> MODLD-433: Update karate tests for changes made for MODLD-353, MODLD-375 & MSEARCH-786

mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/users-negative-scenarios.feature
[MODBULKOPS-161](https://folio-org.atlassian.net/browse/MODBULKOPS-161) - Karate Test: Bulk edit User records - tests using expiration date in the past
=> MODBULKOPS-161 - Karate Test: Bulk edit User records - tests using expiration date in the past

data-import/src/main/resources/folijet/data-import/features/data-import-integration.feature
fix karate test [FAT-15291](https://folio-org.atlassian.net/browse/FAT-15291)
=> FAT-15291 Karate test fail: [folijet/data-import] DataImportApiTest folijet/data-import/features/data-import-integration.feature

acquisitions/src/main/resources/thunderjet/mod-finance/features/ledger-fiscal-year-rollover-cash-balance.feature, acquisitions/src/main/resources/thunderjet/mod-gobi/features/find-holdings-by-location-and-instance.feature
https://folio-org.atlassian.net/browse/FAT-15420
using newly created tenant login
=> [FAT-15420] - fix login of mod-gobi test

acquisitions/src/main/resources/thunderjet/mod-finance/features/ledger-fiscal-year-rollover-cash-balance.feature
=> reverted unnecessary changes

edge-fqm/src/main/resources/corsair/edge-fqm/features/edge-entity-types.feature, edge-fqm/src/main/resources/corsair/edge-fqm/features/edge-query.feature, mod-fqm-manager/src/main/resources/corsair/mod-fqm-manager/features/entity-types.feature, mod-fqm-manager/src/main/resources/corsair/mod-fqm-manager/features/query.feature, mod-lists/src/main/resources/corsair/mod-lists/features/get-list-contents.feature, mod-lists/src/main/resources/corsair/mod-lists/features/get-lists.feature
Temporarily disable failing corsair tests
=> Temporarily disable failing corsair tests

data-import/src/main/resources/folijet/data-import/features/import-edi-invoice.feature, data-import/src/main/resources/folijet/data-import/features/instance-identifier-match.feature, data-import/src/main/resources/folijet/data-import/samples/profiles/authority-mapping-update.json, data-import/src/main/resources/folijet/data-import/samples/profiles/order-import-mapping-profile.json
Fix tests failures after implementation of MODDICONV-388
Removed 'deleted' property from import profiles
=> [FAT-15545] Remove 'deleted' property from import profiles

mod-circulation/src/main/resources/vega/mod-circulation/features/print-events.feature
https://folio-org.atlassian.net/browse/FAT-15570
Getting Invalid token issue, trying the approach of removing testAdmin in print-events.feature
=> FAT-15570 removed testAdmin headers

mod-circulation/src/main/resources/vega/mod-circulation/features/print-events.feature
FAT-15618
changed user login from callOnce to call
=> FAT-15618 in Background user login is changed

mod-linked-data/src/main/resources/citation/mod-linked-data/features/create-bib-apI/samples/instance-expected-response.json, mod-linked-data/src/main/resources/citation/mod-linked-data/features/create-bib-srs/samples/expected-search-response.json
=> MODLD-451, MODLD-356: Update Karate tests

mod-circulation/src/main/resources/vega/mod-circulation/features/print-events.feature
To fix failures in printEventLog features.
Clear the header before loginwithexpiry call.
=> FAT-15570 - Trying to fix failed cases.

common/src/main/resources/common/destroy-data.feature
=> Increase destroy timeout

edge-fqm/src/main/resources/corsair/edge-fqm/features/edge-entity-types.feature, mod-fqm-manager/src/main/resources/corsair/mod-fqm-manager/features/entity-types.feature
Usernames don't get to have value sources anymore
=> [FAT-15780] [FAT-15781] Use locations instead of users for values tests

mod-linked-data/src/main/resources/citation/mod-linked-data/features/create-bib-apI/inventory-outbound.feature, mod-linked-data/src/main/resources/citation/mod-linked-data/features/create-bib-apI/samples/instance-expected-response.json, mod-linked-data/src/main/resources/citation/mod-linked-data/features/create-bib-srs/create-bib-srs.feature, mod-linked-data/src/main/resources/citation/mod-linked-data/features/update-instance-api/util/verify.feature
Change 'instanceMetadata' to 'folioMetadata'
=> MODLD-457: Change 'instanceMetadata' to 'folioMetadata'

mod-circulation/src/main/resources/vega/mod-circulation/features/print-events.feature
https://folio-org.atlassian.net/browse/FAT-15901
Removed out of scope scenarios for print-event feature and fixed the material type issue
=> FAT-15901 Fixing Scenario failures in print-events.feature

mod-inventory/src/main/resources/folijet/mod-inventory/features/consortia/consortia-inventory-junit.feature, mod-inventory/src/main/resources/folijet/mod-inventory/features/consortia/features/update-ownership.feature, mod-inventory/src/main/resources/folijet/mod-inventory/samples/locations-consortiaonline.json
Adjust update holdings ownership tests after adding targetLocationId field
Check that holdingsRecord creates with new location
=> [MODINV-1060] Adjust update holdings ownership tests after adding targetLocationId field

mod-reading-room/src/main/resources/volaris/mod-reading-room/features/reading-room.feature, mod-reading-room/src/main/resources/volaris/mod-reading-room/features/samples/access-log/access-log-entity-request.json, mod-reading-room/src/main/resources/volaris/mod-reading-room/reading-room-init.feature
The purpose of the PR is to implement [FAT-15863](https://folio-org.atlassian.net/browse/FAT-15863)
=> FAT-15863 Adding Karate scenarios for get access Log API

edge-rtac/src/main/resources/core_platform/edge-rtac/features/rtac.feature
[FAT-15971](https://folio-org.atlassian.net/browse/FAT-15971)
- Add scenario to test enhanced the single rtac response endpoint
=> Test enhance the response from an endpoint

edge-patron/src/main/resources/vega/edge-patron/features/lc-user-registration.feature, edge-patron/src/main/resources/vega/edge-patron/features/samples/user/create-inactive-user-request.json
https://folio-org.atlassian.net/browse/FAT-15263
=> FAT-15263: fixed karate for LOC registration API's

edge-dcb/src/main/resources/karate-config.js, edge-dcb/src/main/resources/volaris/edge-dcb/edge-dcb-junit.feature, mod-dcb/src/main/resources/volaris/mod-dcb/features/borrowing-flow.feature, mod-dcb/src/main/resources/volaris/mod-dcb/features/lending-flow.feature
The purpose of the PR is to fix FAT-16053
=> FAT-16053 Fixing failed test case

mod-fqm-manager/src/main/resources/corsair/mod-fqm-manager/features/entity-types.feature
=> [MODFQMMGR-442] Update Karate tests for new FQM entity-types response

mod-template-engine/src/main/resources/vega/mod-template-engine/features/samples/template-request-entity.json, mod-template-engine/src/main/resources/vega/mod-template-engine/features/templateRequest.feature
https://folio-org.atlassian.net/browse/FAT-16231
=> FAT-16231 fixed failed Scenario because of template update

acquisitions/src/main/resources/thunderjet/mod-orders/features/item-and-holding-operations-for-order-flows.feature
- <https://folio-org.atlassian.net/browse/FAT-16265>
- Add retries to wait for 404 after the holdings are removed
=> [FAT-1626]. Add retries until the expected condition is met

acquisitions/src/main/resources/thunderjet/mod-orders/features/item-and-holding-operations-for-order-flows.feature
- <https://folio-org.atlassian.net/browse/FAT-16265>
- Increase retry interval to await the 404 status code
=> [FAT-16265-2]. Increase retry interval

acquisitions/src/main/resources/global/inventory.feature, acquisitions/src/main/resources/global/variables.feature, acquisitions/src/main/resources/thunderjet/mod-orders/features/item-and-holding-operations-for-order-flows.feature
- <https://folio-org.atlassian.net/browse/FAT-16265>
- Use a different global holding id for the failing test
=> [FAT-16265-3]. Create a new global holding id

mod-fqm-manager/src/main/resources/corsair/mod-fqm-manager/features/query.feature, mod-fqm-manager/src/main/resources/corsair/mod-fqm-manager/fqm-junit.feature
=> adding permisison

acquisitions/src/main/resources/thunderjet/mod-orders/features/independent-acquisitions-unit-for-ordering-and-receiving.feature
- <https://folio-org.atlassian.net/browse/FAT-16455>
- Add missing purchase order and poLine creation
- Add correct poLineId in the request payload of the checkIn 
- Update status code assertion to user status code 400 instead 403
=> [FAT-16455]. Fix checkIn tests

acquisitions/src/main/resources/thunderjet/cross-modules/features/check-encumbrances-after-order-line-exchange-rate-update.feature, acquisitions/src/test/java/org/folio/CrossModulesApiTest.java
- <https://folio-org.atlassian.net/browse/MODORDERS-1185>
- Supplementary encumbrance exchange rate tests
=> [MODORDERS-1185]. Encumbrance amount does not update when exchange rate is edited on open order

acquisitions/src/main/resources/thunderjet/consortia/consortia-orders-junit.feature, acquisitions/src/main/resources/thunderjet/consortia/features/pieces-api-test-for-cross-tenant-envs.feature, common-consortia/src/main/resources/common-consortia/initData.feature
[[MODORDERS-1174] Filter pieces based on user affiliations](https://folio-org.atlassian.net/browse/MODORDERS-1174)
- Add a new scenario for fetching filtered pieces based on user affiliations
=> [MODORDERS-1174] Filter pieces based on user affiliations

acquisitions/src/main/resources/thunderjet/cross-modules/features/rollover-with-no-settings.feature, acquisitions/src/main/resources/thunderjet/mod-orders/reusable/validate-order-line-encumbrance-links.feature, acquisitions/src/test/java/org/folio/CrossModulesApiTest.java
- <https://folio-org.atlassian.net/browse/MODORDERS-1162>
- Add supplementary Karate tests
- <https://github.com/folio-org/mod-finance-storage/pull/424>
- <https://github.com/folio-org/mod-orders/pull/1022>
=> [MODORDERS-1162]. Order line encumbrance link not updated when re-encumber is false and order type not rolled over

acquisitions/src/main/resources/karate-config.js, acquisitions/src/main/resources/thunderjet/cross-modules/features/cancel-invoice-with-encumbrance.feature, acquisitions/src/main/resources/thunderjet/cross-modules/features/check-paymentstatus-after-reopen.feature, acquisitions/src/main/resources/thunderjet/cross-modules/features/rollover-with-closed-order.feature, acquisitions/src/main/resources/thunderjet/cross-modules/features/unopen-approve-invoice-reopen.feature, acquisitions/src/main/resources/thunderjet/mod-orders/features/close-order-when-fully-paid-and-received.feature, acquisitions/src/main/resources/thunderjet/mod-orders/features/open-approve-and-pay-order-with-50-lines.feature, acquisitions/src/main/resources/thunderjet/mod-orders/features/reopen-order-creates-encumbrances.feature, acquisitions/src/main/resources/thunderjet/mod-orders/features/reopen-order-with-50-lines.feature, acquisitions/src/main/resources/thunderjet/mod-orders/reusable/close-order-remove-lines.feature, acquisitions/src/main/resources/thunderjet/mod-orders/reusable/close-order.feature, acquisitions/src/main/resources/thunderjet/mod-orders/reusable/create-audit-order-line.feature, acquisitions/src/main/resources/thunderjet/mod-orders/reusable/create-circulation-policy.feature, acquisitions/src/main/resources/thunderjet/mod-orders/reusable/create-holdings.feature, acquisitions/src/main/resources/thunderjet/mod-orders/reusable/create-instance.feature, acquisitions/src/main/resources/thunderjet/mod-orders/reusable/create-order-line.feature, acquisitions/src/main/resources/thunderjet/mod-orders/reusable/create-order.feature, acquisitions/src/main/resources/thunderjet/mod-orders/reusable/create-piece-with-holding.feature, acquisitions/src/main/resources/thunderjet/mod-orders/reusable/create-piece.feature, acquisitions/src/main/resources/thunderjet/mod-orders/reusable/create-title.feature, acquisitions/src/main/resources/thunderjet/mod-orders/reusable/get-order-line-title-id.feature, acquisitions/src/main/resources/thunderjet/mod-orders/reusable/get-order-line.feature, acquisitions/src/main/resources/thunderjet/mod-orders/reusable/receive-piece-with-holding.feature, acquisitions/src/main/resources/thunderjet/mod-orders/reusable/receive-piece.feature, acquisitions/src/main/resources/thunderjet/mod-orders/reusable/unopen-order.feature, acquisitions/src/main/resources/thunderjet/mod-orders/reusable/user-init-data.feature, common/src/main/resources/common/delete-resource.feature
[[MODORDERS-1143] Paying an invoice reopens the order](https://folio-org.atlassian.net/browse/MODORDERS-1143)
- Update existing test to verify preventing order reopen when playing invoice
=> [MODORDERS-1143] Paying an invoice reopens the order

mod-circulation/src/main/resources/karate-config.js, mod-circulation/src/main/resources/logback-test.xml, mod-circulation/src/main/resources/vega/mod-circulation/circulation-junit.feature, mod-circulation/src/main/resources/vega/mod-circulation/features/print-events.feature
https://folio-org.atlassian.net/browse/FAT-16537
=> FAT-16537 modified print request scenarios

mod-circulation/src/main/resources/logback-test.xml, mod-circulation/src/main/resources/vega/mod-circulation/features/print-events.feature
=> Fat 16537 refactoring print event feature file

acquisitions/src/main/resources/karate-config.js, acquisitions/src/main/resources/thunderjet/cross-modules/features/rollover-and-pay-invoice-using-past-fiscal-year.feature, acquisitions/src/test/java/org/folio/CrossModulesApiTest.java
- <https://folio-org.atlassian.net/browse/MODINVOICE-555>
- Add supplementary tests
- Add more commonly used reusable functions to `acquistions/src/main/resources/karate-config.js`
- All cross-modules tests are green:
- <https://github.com/folio-org/mod-invoice/pull/505>
- <https://github.com/folio-org/mod-invoice/pull/405>
=> [MODINVOICE-555]. Order line status NOT updated when paying against previous Fiscal Year 

mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/mod-bulk-operations-junit.feature
[MODBULKOPS-314](https://folio-org.atlassian.net/browse/MODBULKOPS-314) - Central tenant edit permissions handling
=>  MODBULKOPS-314 - update permissions

mod-circulation/src/main/resources/logback-test.xml, mod-circulation/src/main/resources/vega/mod-circulation/circulation-junit.feature, mod-circulation/src/main/resources/vega/mod-circulation/features/print-events.feature
https://folio-org.atlassian.net/browse/FAT-16537
=> Fat 16537 added scenario and fetching print details

acquisitions/src/main/resources/thunderjet/mod-orders/features/open-order-with-resolution-statuses.feature, acquisitions/src/main/resources/thunderjet/mod-orders/orders.feature, acquisitions/src/test/java/org/folio/OrdersApiTest.java, mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/mod-bulk-operations-junit.feature
https://folio-org.atlassian.net/browse/MODORDERS-1170
=> MODORDERS-1170. Orders app: Order not auto-closing as complete despite not receiving/payment requirements

data-import/src/main/resources/folijet/data-import/samples/instance.json
Fix test related to api version update
Remove publicationPeriod field
=> [FAT-16969] Remove publicationPeriod field

mod-bulk-operations/src/main/resources/samples/holdings/instances.json, mod-bulk-operations/src/main/resources/samples/instances/instances.json
=> Remove publicationPeriod from bulk edit karate

acquisitions/src/main/resources/thunderjet/cross-modules/cross-modules-junit.feature, acquisitions/src/main/resources/thunderjet/cross-modules/cross-modules.feature, acquisitions/src/main/resources/thunderjet/mod-invoice/invoice-junit.feature, acquisitions/src/main/resources/thunderjet/mod-invoice/invoice.feature, acquisitions/src/main/resources/thunderjet/mod-orders/orders-junit.feature, acquisitions/src/main/resources/thunderjet/mod-orders/orders.feature
=> Align acq permissions with clean up changes

mod-consortia/src/main/resources/thunderjet/mod-consortia/features/consortia-system-users-verification.feature
https://folio-org.atlassian.net/browse/MODCON-163
- Increased permission
=> [MODCON-163] - Fix test to include new permissions

acquisitions/src/main/resources/thunderjet/mod-invoice/features/check-invoice-lines-with-vat-adjustments.feature, acquisitions/src/main/resources/thunderjet/mod-invoice/features/invoice-with-lock-totals-calculated-totals.feature
- <https://folio-org.atlassian.net/browse/MODINVOICE-554>
- Update affected Karate tests
- <https://github.com/folio-org/mod-invoice/pull/509>
- <https://github.com/folio-org/folio-integration-tests/pull/1563>
- <https://github.com/folio-org/mod-invoice/pull/512>
=> [MODINVOICE-554-2]. Change invoice total and adjustments total calculation

mod-notify/src/main/resources/vega/mod-notify/notify-junit.feature
Adding "notify.users.item.post" permission.
=> FAT-16870 - Adding "notify.users.item.post" permission.

mod-source-record-storage/src/main/resources/folijet/mod-source-record-storage/source-record-storage.feature
=> MODDATAIMP-1100 Drop space from src userPermissions table value

acquisitions/src/main/resources/thunderjet/consortia/features/pieces-api-test-for-cross-tenant-envs.feature, acquisitions/src/main/resources/thunderjet/cross-modules/features/pay-invoice-and-delete-piece.feature, acquisitions/src/main/resources/thunderjet/mod-orders/features/moving_expended_value_to_newly_created_encumbrance.feature, acquisitions/src/main/resources/thunderjet/mod-orders/features/piece-deletion-restriction.feature
https://folio-org.atlassian.net/browse/MODORDERS-1195
- Increased quantity or changed checkinIteam to true
- Improvements
=> [MODORDERS-1195] - Fix test related to restriction for last piece deletion

data-import/src/main/resources/folijet/data-import/features/get-completed-job-execution-for-key.feature, data-import/src/main/resources/folijet/data-import/features/get-completed-job-execution.feature, data-import/src/main/resources/folijet/data-import/global/import-record.feature, mod-source-record-storage/src/main/resources/folijet/mod-source-record-storage/source-record-storage.feature
[MODDATAIMP-1100](https://folio-org.atlassian.net/browse/MODDATAIMP-1100)
data-import karate tests falls into infinity loop, breaking CI Quality Gates pipeline
Reduce retry count in DI feature files for faster failure feedback
=> MODDATAIMP-1100 Reduce retry count in DI feature files for faster failure feedback

acquisitions/src/main/resources/thunderjet/mod-ebsconet/features/get-ebsconet-order-line.feature, acquisitions/src/main/resources/thunderjet/mod-ebsconet/features/update-ebsconet-order-line-empty-locations.feature, acquisitions/src/main/resources/thunderjet/mod-ebsconet/features/update-ebsconet-order-line.feature
=> Fix mod-ebsconet tests

edge-rtac/src/main/resources/karate-config.js
[FAT-16010](https://folio-org.atlassian.net/browse/FAT-16010)
- Update karate config
=> Fix edge-rtac config

edge-fqm/src/main/resources/corsair/edge-fqm/features/edge-entity-types.feature, mod-fqm-manager/src/main/resources/corsair/mod-fqm-manager/fqm-junit.feature, mod-lists/src/main/resources/corsair/mod-lists/lists-junit.feature
- mod-fqm-manager/mod-lists permission changes
- edge-fqm response change
=> [FAT-17175][FAT-17178][FAT-17242] Assorted corsair fixes

mod-users-bl/src/main/resources/volaris/mod-users-bl/features/configurePermissions.feature
=> FAT-17243 add new mod-users-bl permissions

mod-linked-data/src/main/resources/citation/mod-linked-data/features/suppress-flags/samples/create-instance-request.json, mod-linked-data/src/main/resources/citation/mod-linked-data/features/suppress-flags/samples/create-work-request.json, mod-linked-data/src/main/resources/citation/mod-linked-data/features/suppress-flags/suppress-flags.feature, mod-linked-data/src/main/resources/citation/mod-linked-data/features/util/crud-resource.feature, mod-linked-data/src/main/resources/citation/mod-linked-data/linked-data-junit.feature, mod-linked-data/src/main/resources/karate-config.js, mod-linked-data/src/test/java/org/folio/ModLinkedDataTest.java
Cover a scenario with Suppress flag update for Inventory instance
Testing through API
=> MODLD-566: Tests for Suppress Flags feature

acquisitions/src/main/resources/thunderjet/mod-orders/features/check-order-total-fields-calculated-correctly.feature
- <https://folio-org.atlassian.net/browse/MODORDERS-1204>
- Update supplementary Karate tests
- All other mod-orders Karate tests ran green:
- <https://github.com/folio-org/mod-orders/pull/1046>
=> [MODORDERS-1204]. Update total expended amount calculation for Purchase order to only Paid invoices

mod-di-converter-storage/src/main/resources/folijet/mod-di-converter-storage/features/jobProfiles.feature
[MODDICONV-394](https://folio-org.atlassian.net/browse/MODDICONV-394) Disallow usage of Update MARC Bib next to Update Instance actions
=> MODDICONV-394 Disallow usage of Update MARC Bib next to Update Instance actions

mod-di-converter-storage/src/main/resources/folijet/mod-di-converter-storage/features/jobProfiles.feature
=> revert MODDICONV-394 changes

teams-assignment.json
=> MODLD-588: team assignment added

acquisitions/src/main/resources/thunderjet/mod-invoice/features/batch-voucher-uploaded.feature
Update karate test to test ticket https://folio-org.atlassian.net/browse/MODINVOICE-566
=> MODINVOICE-566. Error When Run Batch Voucher Export Manually

mod-search/src/test/resources/samples/test-data/instances.json, mod-search/src/test/resources/spitfire/mod-search/browse/contributor-browse.feature, mod-search/src/test/resources/spitfire/mod-search/browse/subject-browse.feature, mod-search/src/test/resources/spitfire/mod-search/filters/sort-by-option-search.feature, mod-search/src/test/resources/spitfire/mod-search/search/single-property-search.feature
Implement cases for search/browse with diacritics
[FAT-15219](https://folio-org.atlassian.net/browse/FAT-15219)
=> feat(mod-search): Search/browse with diacritics

mod-linked-data/src/main/resources/citation/mod-linked-data/features/suppress-flags/suppress-flags.feature, mod-linked-data/src/main/resources/citation/mod-linked-data/features/util/search-resource.feature
=> FAT-17500: mod-linked-data: Increase retry timeout

mod-linked-data/src/main/resources/citation/mod-linked-data/features/create-bib-api/samples/instance-expected-response.json, mod-linked-data/src/main/resources/citation/mod-linked-data/features/create-bib-api/samples/instance-request.json, mod-linked-data/src/main/resources/citation/mod-linked-data/features/create-bib-api/samples/inventory-expected-response.json, mod-linked-data/src/main/resources/citation/mod-linked-data/features/create-bib-api/search-outbound.feature
=> MODLD-583: Use correct LCCN format in tests

acquisitions/src/main/resources/thunderjet/consortia/features/update-unaffiliated-pol-locations.feature
- <https://folio-org.atlassian.net/browse/EUREKA-561>
- Remove a test scenario that is no longer supported by the code
=> [EUREKA-561]. Remove redundant & unsupported test scenario

mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/init-data/init-data-for-instances.feature, mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/init-data/mod-inventory-storage-util.feature, mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/instances.feature, mod-bulk-operations/src/main/resources/samples/instances/statistical-code-types.json, mod-bulk-operations/src/main/resources/samples/instances/statistical-codes.json
Add karate tests for statistical codes, [MODBULKOPS-389](https://folio-org.atlassian.net/browse/MODBULKOPS-389)
=> MODBULKOPS-389 Added stat codes tests

mod-password-validator/src/test/resources/samples/password_check.json, mod-password-validator/src/test/resources/spitfire/passwordvalidator/features/validate.feature, mod-password-validator/src/test/resources/spitfire/passwordvalidator/test-rule-failure-on-password-check.feature
[FAT-17738](https://folio-org.atlassian.net/browse/FAT-17738)
- add new scenarios for /password/check
=> FAT-17738: Test new endpoint to check password

acquisitions/src/main/resources/global/finances.feature, acquisitions/src/main/resources/thunderjet/consortia/order-utils/finances.feature
2025 update
Updated test data with new dates and codes for the new year.
=> Updated dates and codes for the new year

edge-patron/src/main/resources/vega/edge-patron/features/lc-user-registration.feature, edge-patron/src/main/resources/vega/edge-patron/features/samples/user/create-lc-user-request.json, edge-patron/src/main/resources/vega/edge-patron/features/samples/user/create-user-request.json, edge-patron/src/main/resources/vega/edge-patron/features/util/lc-initData.feature, edge-patron/src/main/resources/vega/edge-patron/patron-junit.feature
https://folio-org.atlassian.net/browse/FAT-16860
=> FAT-16860: added karate test for LOC user registration in edge-patron

mod-linked-data/src/main/resources/citation/mod-linked-data/features/create-bib-api/inventory-outbound.feature, mod-linked-data/src/main/resources/citation/mod-linked-data/features/create-bib-api/samples/instance-expected-response.json, mod-linked-data/src/main/resources/citation/mod-linked-data/features/create-bib-api/samples/instance-request.json, mod-linked-data/src/main/resources/citation/mod-linked-data/features/create-bib-api/samples/inventory-expected-response.json, mod-linked-data/src/main/resources/citation/mod-linked-data/features/create-bib-api/search-outbound.feature, mod-linked-data/src/main/resources/citation/mod-linked-data/features/import-bib/samples/expected-search-response.json
=> MODLD-619: Fix Punctuation story related tests

edge-patron/src/main/resources/vega/edge-patron/features/lc-user-registration.feature
https://folio-org.atlassian.net/browse/FAT-16860
=> FAT-16860: fixed karate typo issue for patron registration in edge-patron

mod-fqm-manager/src/main/resources/corsair/mod-fqm-manager/fqm-junit.feature, mod-lists/src/main/resources/corsair/mod-lists/lists-junit.feature
=> Add missed permissions to FQM tests

mod-inventory/src/main/resources/folijet/mod-inventory/features/consortia/features/update-ownership.feature
Update status codes in error response for update-ownership feature
Change the expected response status code from 200 to 400 in affected tests
[FAT-18107](https://folio-org.atlassian.net/browse/FAT-18107)
=> FAT-18107 Update statuses in error response for update-ownership.feature

data-import-large-scale-tests/src/main/resources/karate-config.js
=> RANCHER-1284 env switch

acquisitions/src/main/resources/global/inventory.feature, acquisitions/src/main/resources/thunderjet/mod-gobi/features/gobi-api-tests.feature, acquisitions/src/main/resources/thunderjet/mod-organizations/reusable/create-organization.feature
https://folio-org.atlassian.net/browse/FAT-18199
https://folio-org.atlassian.net/browse/FAT-18198
https://folio-org.atlassian.net/browse/FAT-18124
- Update tests based on recent changes 
- Fix incorrect cases
=> [FAT-18199] - Fix karate fails related to 18199, 18198, 18124

acquisitions/src/main/resources/thunderjet/mod-data-export-spring/features/claims-export.feature, acquisitions/src/main/resources/thunderjet/mod-data-export-spring/features/root.feature
fail on scheduled karate test
- Improve filtering
=> [FAT-17701-2] - Fix filter jobs process

mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/holdings.feature, mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/instances.feature, mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/items.feature, mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/users-negative-scenarios.feature, mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/users-positive-scenarios.feature
[MODBULKOPS-301](https://folio-org.atlassian.net/browse/MODBULKOPS-301) - Handling errors and warnings while committing changes
Add offset and errorType parameters.
=> MODBULKOPS-301 Added parameters to /errors

acquisitions/src/main/resources/thunderjet/mod-orders/features/pieces-batch-update-status.feature
https://folio-org.atlassian.net/browse/FAT-18200
- login testUser for each scenario to avoid login timout
=> [FAT-18200] - Login in every scenario

mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/holdings.feature, mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/instances.feature, mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/items.feature, mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/users-negative-scenarios.feature, mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/users-positive-scenarios.feature
[MODBULKOPS-301](https://folio-org.atlassian.net/browse/MODBULKOPS-301) - Handling errors and warnings while committing changes
Add missing "param".
=> MODBULKOPS-301 - Handling errors and warnings while committing changes

acquisitions/src/main/resources/thunderjet/mod-orders/features/check-order-total-fields-calculated-correctly.feature
[MODORDERS-1248](https://folio-org.atlassian.net/browse/MODORDERS-1248) - Total expended value on order details pane contains invoice total value instead of invoice line total
Added a new test to check invoice lines related to a different order are ignored when calculating the total expended amount.
[mod-orders PR](https://github.com/folio-org/mod-orders/pull/1089)
=> [MODORDERS-1248] New test checking order total expended amount

acquisitions/src/main/resources/thunderjet/mod-orders/features/pieces-batch-update-status.feature
Login timeout issue
- Disabling scenario for now until piece create batch api implementation
=> [FAT-18200] - Disable scenario until batch piece create api available

edge-fqm/src/main/resources/corsair/edge-fqm/features/edge-entity-types.feature, mod-fqm-manager/src/main/resources/corsair/mod-fqm-manager/features/entity-types.feature
Update entity type names in tests to fix:
[FAT-18284](https://folio-org.atlassian.net/browse/FAT-18284)
[FAT-18288](https://folio-org.atlassian.net/browse/FAT-18288)
=> [FAT-18288] [FAT-18284] Update entity type names in tests

mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/holdings.feature, mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/instances.feature, mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/items.feature, mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/users-negative-scenarios.feature, mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/users-positive-scenarios.feature
=> FAT-18285 adjust bulk edit errors response expectations

acquisitions/src/main/resources/karate-config.js, acquisitions/src/main/resources/thunderjet/mod-orders/features/pieces-batch-update-status.feature, acquisitions/src/main/resources/thunderjet/mod-orders/reusable/create-pieces-batch.feature
It was slow  due to creation of piece one by one
- Use new create piece batch API
=> [FAT-18200] - re-enable scenario with new piece batch api

mod-linked-data/src/main/resources/citation/mod-linked-data/features/create-bib-api/samples/inventory-expected-response.json
Change tests based on the changes made for MODLD-647
=> FAT-18244: Change tests based on the changes made for MODLD-647

data-import/src/main/resources/folijet/data-import/features/data-import-integration.feature, data-import/src/main/resources/karate-config.js
Fix FAT-945
Add check for Holdings to updated to keep test consistent with test case logic
https://folio-org.atlassian.net/browse/FAT-17578
=> [FAT-17578] Fix FAT-945

mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/instances.feature, mod-bulk-operations/src/main/resources/samples/instances/statistical-code-types.json
=> FAT-17771 fix bulk-edit instance tests

mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/instances.feature
Reverts folio-org/folio-integration-tests#1700
=> Revert "FAT-17771 fix bulk-edit instance tests"

edge-oai-pmh/src/main/resources/firebird/edge-oai-pmh/features/edge-oai-pmh.feature
[MODOAIPMH-587](https://folio-org.atlassian.net/browse/MODOAIPMH-587) - Include FOLIO location in addition to Discovery Display Name
Add check for $s subfield (must be location name).
=> MODOAIPMH-587 - Include FOLIO location in addition to Discovery Display Name

acquisitions/src/main/resources/thunderjet/mod-finance/features/finance-data.feature
- https://folio-org.atlassian.net/browse/MODFIN-403
- Update validation finance data
- Add retry for logs after adding in_progress updates
=> [MODFIN-403] - Update finance-data validation

edge-oai-pmh/src/main/resources/firebird/edge-oai-pmh/features/edge-oai-pmh.feature, edge-oai-pmh/src/main/resources/firebird/edge-oai-pmh/features/init_data/create-instance.feature, edge-oai-pmh/src/main/resources/firebird/edge-oai-pmh/features/init_data/init-edge-oai-pmh.feature, edge-oai-pmh/src/main/resources/global/variables.feature
[MODOAIPMH-581](https://folio-org.atlassian.net/browse/MODOAIPMH-581) - add karate tests based on this story
Add 1 instance with LINKED_DATA source, corresponding SRS record and check harvest.
=> MODOAIPMH-581 Added record with LINKED_DATA source

mod-copycat/src/main/resources/folijet/mod-copycat/copycat-junit-eureka.feature, mod-copycat/src/main/resources/folijet/mod-copycat/eureka-features/copycat-profiles.feature, mod-copycat/src/main/resources/karate-config.js, mod-copycat/src/test/java/org/folio/ModCopycatEurekaTest.java, mod-copycat/src/test/java/org/folio/ModCopycatTest.java, mod-ldp/src/test/java/org/folio/ModLdpApiTest.java
In this PR, the functionality of the mod-copycat module was adopted to work against Eureka
=> FAT-18503 -  Thor modules refactoring

common/src/main/resources/common/eureka/application.feature, common/src/main/resources/common/eureka/destroy-data.feature, common/src/main/resources/common/eureka/samples/entitlement-entity.json, common/src/main/resources/common/eureka/setup-users.feature, mod-notify/src/main/resources/karate-config.js
modified search application file to get all appIds
remove unnecessary code in mod-notify karate-config.js 
adopted entitlement-entity.json
fix path in destroy-data.feature
fix scenario in setup-users.feature
=> Adopted functional of common module to new env 

acquisitions/src/main/resources/thunderjet/mod-finance/features/finance-data.feature
https://folio-org.atlassian.net/browse/MODFIN-415
Adjusted validation messages
added case for fundStatus
=> [MODFIN-415] - Update finance-data validation messages and error hand

mod-calendar/src/main/resources/bama/mod-calendar/calendar-junit-eureka.feature, mod-calendar/src/main/resources/bama/mod-calendar/eureka-features/calendar-create.feature, mod-calendar/src/main/resources/bama/mod-calendar/eureka-features/calendar-dates-all.feature, mod-calendar/src/main/resources/bama/mod-calendar/eureka-features/calendar-dates-surrounding.feature, mod-calendar/src/main/resources/bama/mod-calendar/eureka-features/calendar-edit.feature, mod-calendar/src/main/resources/bama/mod-calendar/eureka-features/calendar-search.feature, mod-calendar/src/main/resources/bama/mod-calendar/features/samples/createCalendar.json, mod-calendar/src/main/resources/bama/mod-calendar/features/samples/createComplexCalendar.json, mod-calendar/src/main/resources/bama/mod-calendar/features/samples/editCalendar.json, mod-calendar/src/main/resources/karate-config.js, mod-calendar/src/test/java/org/folio/ModCalendarEurekaTest.java, mod-calendar/src/test/java/org/folio/ModCalendarTest.java
In this PR, the functionality of the mod-calendar module was adopted to work against Eureka
=> FAT-18507 - Bama modules refactoring

mod-search/src/test/resources/spitfire/mod-search/set-up/create-test-data.feature
mod-search: fix test initialization
=> FAT-19097 mod-search: fix test initialization

mod-inventory/src/main/resources/folijet/mod-inventory/features/setForDeletion.feature, mod-inventory/src/main/resources/folijet/mod-inventory/features/utils.feature, mod-inventory/src/main/resources/folijet/mod-inventory/inventory-junit.feature, mod-inventory/src/test/java/org/folio/ModInventoryTests.java
Integration test for Set for Deletion feature
API testing
=> MODINV-1139: [Folijet] Make changes to PUT instances endpoint to update MARC with "deleted" markers

teams-assignment.json
=> teamsAssignment update for LSDI

mod-calendar/src/main/resources/karate-config.js, mod-copycat/src/main/resources/karate-config.js, mod-notify/src/main/resources/karate-config.js, mod-notify/src/test/java/org/folio/ModNotifyEurekaTests.java
- Configs of modules(mod-copycat, mod-calendar and mod-notify) were fixed
- mod-notify tests were disabled
=> FAT-18503  - Config variables fix

mod-copycat/src/main/resources/folijet/mod-copycat/eureka-features/copycat-profiles.feature
=> FAT-18503 - Copycat scenario fix

mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/holdings.feature, mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/items.feature
=> MODBULKOPS-455 fix tests

mod-linked-data/src/main/resources/citation/mod-linked-data/features/create-bib-api/samples/work-expected-response.json
=> FAT-19191 / MODLD-669: Update fingerprint for Classification resource

common/src/main/resources/common/eureka/setup-users.feature
change entitlement creation params
=> change entitlement creation params

mod-linked-data/src/main/resources/citation/mod-linked-data/features/create-bib-api/samples/work-expected-response.json
Reorder Dewey and LC classification due to fingerprint change
=> FAT-19191: Reorder Dewey and LC classification due to fingerprint change

mod-batch-print/src/main/resources/odin/mod-batch-print/batch-print-junit-eureka.feature, mod-calendar/src/main/resources/bama/mod-calendar/calendar-junit-eureka.feature, mod-copycat/src/main/resources/folijet/mod-copycat/copycat-junit-eureka.feature, mod-copycat/src/main/resources/karate-config.js
* In this PR modules logic was adopted to work with new applications search logic
=> FAT-18502 - modules fix

data-import/src/main/resources/folijet/data-import/data-import-junit-eureka.feature, mod-source-record-manager/src/test/java/org/folio/ModSourceRecordManagerEurekaTest.java, mod-source-record-storage/src/test/java/org/folio/ModSourceRecordStorageEurekaTest.java
- mod-source-record-storage, mod-source-record-manager tests enabled
=> FAT-18346 - Enabling tests for modules

edge-dcb/src/main/resources/volaris/edge-dcb/edge-dcb-junit.feature, mod-dcb/src/main/resources/volaris/mod-dcb/mod-dcb-junit.feature
=> Added missing permission circulation.loans.collection.get

common/src/main/resources/common/eureka/capabilities.feature, common/src/main/resources/common/eureka/setup-users.feature
add retry mechanism for /capabilities
=> Wait for capabilities

common/src/main/resources/common/eureka/capabilities.feature, common/src/main/resources/common/eureka/refresh.feature, mod-circulation/src/main/resources/karate-config.js
=> refresh token

mod-fqm-manager/src/main/resources/corsair/mod-fqm-manager/features/consortia/consortia-fqm.feature, mod-fqm-manager/src/main/resources/corsair/mod-fqm-manager/features/consortia/consortium.feature, mod-fqm-manager/src/main/resources/corsair/mod-fqm-manager/features/consortia/cross_tenant_et.feature, mod-fqm-manager/src/main/resources/corsair/mod-fqm-manager/features/consortia/tenant.feature, mod-fqm-manager/src/main/resources/corsair/mod-fqm-manager/features/consortia/util/initData.feature, mod-fqm-manager/src/main/resources/corsair/mod-fqm-manager/features/consortia/util/tenant-and-admin-setup.feature, mod-fqm-manager/src/main/resources/corsair/mod-fqm-manager/features/validate-column-helper.feature, mod-fqm-manager/src/main/resources/corsair/mod-fqm-manager/features/validate-entity-columns.feature, mod-fqm-manager/src/main/resources/corsair/mod-fqm-manager/fqm-junit.feature, mod-fqm-manager/src/test/java/org/folio/ModFqmManagerTest.java
=> MODFQMMGR-399:Add first ECS data and test to karate test repository

acquisitions/src/main/resources/thunderjet/cross-modules/cross-modules.feature, acquisitions/src/main/resources/thunderjet/mod-finance/finance.feature, acquisitions/src/main/resources/thunderjet/mod-orders/orders.feature
Fix to run `.feature` files (not junit) with BusyBee and uppercut.
- Updated acq feature files (not junit) for BusyBee
- Fixed case for 3 file names
=> Updated acq feature files for BusyBee

edge-oai-pmh/src/main/resources/firebird/edge-oai-pmh/features/edge-oai-pmh.feature
=> FAT-19351 adjust karate after MODINVSTOR-1224 changes

mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/quick-marc-handle-literal-dollar.feature, mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/quick-marc-tags-order.feature, mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/setup/samples/parsed-records/marc-authority-record.json, mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/setup/samples/parsed-records/marc-bib-record.json, mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/setup/samples/parsed-records/marc-holding-record.json, mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/setup/setup.feature, mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/quick-marc-junit.feature, mod-quick-marc/src/test/java/org/folio/QuickMarcApiTest.java
[FAT-1264](https://folio-org.atlassian.net/browse/FAT-12649) quick-marc scenarios for tag positions and $ changes
=> FAT-12649: Create quick-marc scenarios for tag positions and {dollar} changes.

edge-dcb/src/test/java/org/folio/EdgeDcbApiTest.java, edge-inn-reach/src/test/java/org/folio/EdgeInnReachApiTest.java, mod-audit/src/test/java/org/folio/ModAuditApiTest.java, mod-dcb/src/test/java/org/folio/ModDCBTest.java, mod-email/src/test/java/org/folio/EmailApiTests.java, mod-event-config/src/test/java/org/folio/ModEventConfigTests.java, mod-inn-reach/src/test/java/org/folio/InnReachApiTest.java, mod-notify/src/test/java/org/folio/ModNotifyTests.java, mod-password-validator/src/test/java/org.folio/ModPasswordValidatorApiTest.java, mod-reading-room/src/test/java/org/folio/ModReadingRoomApiTest.java, mod-sender/src/test/java/org/folio/ModSenderTests.java, mod-tags/src/test/java/org/folio/ModTagsApiTest.java, mod-template-engine/src/test/java/org/folio/ModTemplateEngineTests.java, mod-users-bl/src/test/java/org/folio/ModUsersBLTests.java, mod-users/src/test/java/org/folio/ModUsersTests.java
This PR includes disabling tests for Volaris team
=> FAT-19626-clean-up-volaris-master

mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/setup/setup.feature
[FAT-12649](https://folio-org.atlassian.net/browse/FAT-12649) Fix mod-quick-marc test: add retry for CreateMarcBibRecord util scenario.
Issue:
<kbd>
</kbd>
=> Fix mod-quick-marc test

data-import/src/test/java/org/folio/DataImportApiTest.java, mod-di-converter-storage/src/test/java/org/folio/ModDataImportConverterStorageTest.java, mod-inventory/src/test/java/org/folio/ConsortiaInventoryTest.java, mod-inventory/src/test/java/org/folio/ModInventoryTests.java, mod-source-record-manager/src/test/java/org/folio/ModSourceRecordManagerTest.java, mod-source-record-storage/src/test/java/org/folio/ModSourceRecordStorageTest.java
This PR includes disabling tests for Folijet team
=> FAT-18346 - Folijet-clean-up-master

edge-fqm/src/test/java/org/folio/EdgeFqmTest.java, mod-fqm-manager/src/test/java/org/folio/ModFqmManagerTest.java, mod-lists/src/test/java/org/folio/ModListsTest.java
This PR includes disabling tests for Corsair team
=> FAT-18502 - Corsair-clean-up-master

mod-oai-pmh/src/test/resources/firebird/oaipmh/oaipmh-enhancement.feature, mod-oai-pmh/src/test/resources/firebird/oaipmh/oaipmh-listRecords-sourceInventory.feature, mod-oai-pmh/src/test/resources/global/variables.feature, mod-oai-pmh/src/test/resources/samples/configuration/behavior.json, mod-oai-pmh/src/test/resources/samples/configuration/behavior_value.json
[FAT-19580](https://folio-org.atlassian.net/browse/FAT-19580) - Karate test fail: firebird/oaipmh/oaipmh-enhancement.feature
Set records source to Source records storage before test.
=> FAT-19580 - Karate test fail: firebird/oaipmh/oaipmh-enhancement.feature

mod-calendar/src/test/java/org/folio/ModCalendarTest.java, mod-copycat/src/test/java/org/folio/ModCopycatTest.java
This PR includes disabling tests for Bama & Thor teams
=> Bama & Thor - clean-up-master

mod-linked-data/src/main/resources/citation/mod-linked-data/eureka/features/create-bib-api/create-resource.feature, mod-linked-data/src/main/resources/citation/mod-linked-data/eureka/features/create-bib-api/samples/instance-expected-response.json, mod-linked-data/src/main/resources/citation/mod-linked-data/eureka/features/create-bib-api/samples/instance-request.json, mod-linked-data/src/main/resources/citation/mod-linked-data/eureka/features/create-bib-api/samples/inventory-expected-response.json, mod-linked-data/src/main/resources/citation/mod-linked-data/eureka/features/create-bib-api/samples/work-expected-response.json, mod-linked-data/src/main/resources/citation/mod-linked-data/eureka/features/create-bib-api/search-outbound.feature, mod-linked-data/src/main/resources/citation/mod-linked-data/eureka/features/import-bib/samples/expected-search-response.json, mod-linked-data/src/main/resources/citation/mod-linked-data/eureka/linked-data-junit.feature
- mod-linked data samples & validations was adjusted with latest changes from master
- removed one duplicated capability and one not existing capability
=> FAT-18504 - mod-linked-data fix

mod-linked-data/src/main/resources/karate-config.js
fix wrong paths in karate-config.js
=>  modules refactoring citation 1 fix

edge-oai-pmh/src/main/resources/firebird/edge-oai-pmh/features/init_data/create-electronic-access-relationship.feature, mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/holdings.feature, mod-data-export/src/test/resources/firebird/dataexport/features/export-deleted-authorities.feature, mod-data-export/src/test/resources/karate-config.js
=> Fat 18341 firebird clean up2

acquisitions/src/main/resources/thunderjet/mod-orders/features/poline_change_instance_connection.feature, acquisitions/src/main/resources/thunderjet/mod-orders/features/productIds-field-error-when-attempting-to-update-unmodified-order.feature
https://folio-org.atlassian.net/browse/MODORDERS-1265
=> [MODORDERS-1265]. Remove ISBN validation/normalization logic

mod-inn-reach/src/main/resources/karate-config.js
Changing default mock server url for Volaris tests.
=> VOLARIS: Changing mock server default url

common/src/main/resources/common/eureka/setup-users.feature
Show missing capabilities to help troubleshooting
Tracking existing capabilities and return capabilities that do not exists in the "expected" list
=> Enhance capability retrieval by tracking found and missing permissions

README.md, common/src/main/resources/common/eureka/setup-users.feature
Making logging more informative.
=> Logging extending for Entitlements Setup

data-import/src/main/resources/folijet/data-import/features/data-import-delete-logs.feature, data-import/src/main/resources/folijet/data-import/features/get-completed-job-execution.feature, data-import/src/main/resources/folijet/data-import/global/check-job-log-entries.feature
- align retry clause and remove pause for data-import-delete-logs.feature
=> Implement dynamic job log entry checks and error handling in data import features

data-import/src/main/resources/folijet/data-import/features/data-import-delete-logs.feature, data-import/src/main/resources/folijet/data-import/features/data-import-orders.feature, data-import/src/main/resources/folijet/data-import/features/get-completed-job-execution-for-key.feature, data-import/src/main/resources/folijet/data-import/features/get-completed-job-execution.feature, data-import/src/main/resources/folijet/data-import/global/check-job-log-entries.feature
Refactor data import tests to replace hardcoded pauses with dynamic retries
=> FAT-13900 Fix Orders Feature

mod-search/src/test/resources/spitfire/mod-search/filters/filter-search.feature, mod-search/src/test/resources/spitfire/mod-search/search/single-property-search.feature
[MODINVSTOR-1382](https://folio-org.atlassian.net/browse/MODINVSTOR-1382) Update Karate tests for mod-search module to search Instances by createdDate/updatedDate metadata. 
<kbd>
</kbd>
=> Update Karate tests for mod-search module to search Instances by createdDate/updatedDate metadata.

mod-inn-reach/src/main/resources/volaris/mod-inn-reach/mod-inn-reach-junit.feature
Rollback change for inventory storage data creation
Jira issue: https://folio-org.atlassian.net/browse/FAT-19828
=> FAT-19828: Add removed inventory data init for inn-reach tests

mod-source-record-storage/src/main/resources/folijet/mod-source-record-storage/features/get-source-storage-records.feature, mod-source-record-storage/src/main/resources/folijet/mod-source-record-storage/source-record-storage.feature
provide the newly introduced permission for suppress from discovery endpoint
[MODSOURCE-917](https://issues.folio.org/browse/MODSOURCE-917)
=> MODSOURCE-917 - Provide new permission for suppress from discovery endpoint

acquisitions/src/main/resources/thunderjet/consortia/init-consortia-orders.feature, acquisitions/src/main/resources/thunderjet/consortia/reusable/updateHridSettings.feature
Fixed some issues with updating HRID settings. There might be others, but we don't have a way to run this test.
Fixed permissions and expected HTTP code; changed path to be more consistent with other usage.
=> [MODORDERS-1310] Fixed updating HRID settings

acquisitions/src/main/resources/thunderjet/consortia/features/open-orders-in-member-tenant.feature
[MODORDERS-1310](https://folio-org.atlassian.net/browse/MODORDERS-1310) - Make Local order matching ECS aware such that shadows will be created for shared instances before local instances will be created.
Still trying to fix the test without being able to run it.
Using only member locations, as using a central location when opening an order in a member tenant is not supported.
=> [MODORDERS-1310] Using member locations only

mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/items.feature
=> Increase timeouts in bulk edit items tests

mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/mod-bulk-operations-junit.feature
=> increase TTL for mod-bulk-ops tests

acquisitions/src/main/resources/thunderjet/edge-orders/features/gobi.feature, acquisitions/src/main/resources/thunderjet/mod-orders/features/change-location-when-receiving-piece.feature
- Fix broken Edge-orders GOBI and Orders tests
- Merge and rename Edge-orders GOBI feature scenarios
- Add `retry until` to **Change location when receiving a piece** feature
=> Fix Edge-Orders GOBI & Orders Tests

acquisitions/src/main/resources/thunderjet/mod-invoice/features/should_populate_vendor_address_on_get_voucher_by_id.feature, acquisitions/src/main/resources/thunderjet/mod-orders/features/MODORDERS-538-piece-against-non-package-mixed-pol-manual-piece-creation-is-true.feature, acquisitions/src/main/resources/thunderjet/mod-orders/features/receive-piece-against-package-pol.feature
Fix recent failures:
https://jenkins.ci.folio.org/job/folioScheduledTesting/job/runNightlyKarateEurekaTests/518/cucumber-html-reports/overview-features.html
=> Fix Thunderjet recent karate failures

acquisitions/src/main/resources/thunderjet/mod-orders/features/pieces-batch-update-status.feature
Test PR https://github.com/folio-org/mod-orders/pull/1147
=> UIREC-450. Internal and external note fields not populated when user sets new piece to "Claim sent"

acquisitions/src/main/resources/thunderjet/mod-orders/features/open-order-instance-link.feature
https://folio-org.atlassian.net/browse/FAT-20575
Increase pause timeout for configuration cache TTL in instance link feature
=> [FAT-20575] Increase pause timeout for configuration cache TTL in instance link feature

acquisitions/src/main/resources/thunderjet/mod-finance/features/budget-expense-classes.feature, acquisitions/src/main/resources/thunderjet/mod-finance/features/group-expense-classes.feature
- <https://folio-org.atlassian.net/browse/MODFIN-433>
- Update Budget and Group expense classes features with an additional grouping to verify
- Simplify and refactor steps by making them more compact and easier to read
- Test locally with Eureka CLI deployed with combined profile
> mod-finance folder
=> [MODFIN-433]. Include totals without expense class for expense-classes-totals

acquisitions/src/main/resources/thunderjet/mod-orders/features/auto-populate-fund-code.feature, acquisitions/src/main/resources/thunderjet/mod-orders/features/change-location-when-receiving-piece.feature, acquisitions/src/main/resources/thunderjet/mod-orders/features/fund-codes-in-open-order-error.feature, acquisitions/src/main/resources/thunderjet/mod-orders/orders.feature, acquisitions/src/test/java/org/folio/OrdersApiTest.java
Karate test for story https://folio-org.atlassian.net/browse/MODORDERS-981
=> MODORDERS-981. Populate the fundCode dynamically using the fundId if it is missing

mod-fqm-manager/src/main/resources/corsair/mod-fqm-manager/features/consortia/consortia-fqm.feature, mod-fqm-manager/src/main/resources/corsair/mod-fqm-manager/fqm-junit.feature, mod-lists/src/main/resources/corsair/mod-lists/features/consortia/consortia-list.feature
Add holdings notes permissions
=> MODFQMMGR-127 - Add holdings notes permissions

mod-lists/src/main/resources/corsair/mod-lists/features/consortia/instance-export.feature
=> MODFQMMGR-888 adjust tests for export consortia lists

mod-linked-data/src/main/resources/citation/mod-linked-data/features/create-bib-api/samples/work-expected-response.json, mod-linked-data/src/main/resources/citation/mod-linked-data/features/create-bib-api/samples/work-request.json
Update tests to match the modified API payload schema.
See https://folio-org.atlassian.net/browse/MODLD-820 for more.
Fix the given request and expected responses included in the tests.
=> MODLD-820: Update tests with modified request and response structure

mod-linked-data/src/main/resources/citation/mod-linked-data/features/authority/samples/work_with_authority.json, mod-linked-data/src/main/resources/citation/mod-linked-data/features/create-bib-api/samples/instance-request.json, mod-linked-data/src/main/resources/citation/mod-linked-data/features/create-bib-api/samples/work-request.json, mod-linked-data/src/main/resources/citation/mod-linked-data/features/lccn-pattern-validation/samples/invalid-instance-request.json, mod-linked-data/src/main/resources/citation/mod-linked-data/features/lccn-pattern-validation/samples/valid-instance-request.json, mod-linked-data/src/main/resources/citation/mod-linked-data/features/lccn-pattern-validation/samples/work-request.json, mod-linked-data/src/main/resources/citation/mod-linked-data/features/suppress-flags/samples/create-instance-request.json, mod-linked-data/src/main/resources/citation/mod-linked-data/features/suppress-flags/samples/create-work-request.json, mod-linked-data/src/main/resources/citation/mod-linked-data/features/update-instance-api/samples/update-instance-request.json, mod-linked-data/src/main/resources/citation/mod-linked-data/features/validation/lccn/deduplication/samples/duplicate-lccn-instance-request.json, mod-linked-data/src/main/resources/citation/mod-linked-data/features/validation/lccn/deduplication/samples/instance-request.json, mod-linked-data/src/main/resources/citation/mod-linked-data/features/validation/lccn/deduplication/samples/work-request.json
Fixes FAT-21633, FAT-21634, FAT-21635, FAT-21636, FAT-21637, FAT-21638
Include profile ID in the API request in accordance with the changes made for MODLD-803
- N/A
- N/A
=> MODLD-803: Include profileId in API requests

mod-circulation-item/pom.xml, mod-circulation-item/src/main/resources/karate-config.js, mod-circulation-item/src/main/resources/logback-test.xml, mod-circulation-item/src/main/resources/volaris/mod-circulation-item/features/circulation-item-flow.feature, mod-circulation-item/src/main/resources/volaris/mod-circulation-item/features/samples/create-dcb-circulation-item.json, mod-circulation-item/src/main/resources/volaris/mod-circulation-item/features/samples/create-location.json, mod-circulation-item/src/main/resources/volaris/mod-circulation-item/global/variables.feature, mod-circulation-item/src/main/resources/volaris/mod-circulation-item/mod-circulation-item-junit.feature, mod-circulation-item/src/main/resources/volaris/mod-circulation-item/reusable/pre-requisites.feature, mod-circulation-item/src/test/java/org/folio/ModCirculationItemTest.java, pom.xml, teams-assignment.json
https://folio-org.atlassian.net/browse/MODCITEM-44
=> MODCITEM-44: added karate test module for mod-circulation-item

mod-fqm-manager/src/main/resources/corsair/mod-fqm-manager/features/consortia/consortia-fqm.feature, mod-fqm-manager/src/main/resources/corsair/mod-fqm-manager/fqm-junit.feature, mod-lists/src/main/resources/corsair/mod-lists/features/consortia/consortia-list.feature, mod-lists/src/main/resources/corsair/mod-lists/lists-junit.feature
=> MODFQMMGR-858 fix permissions for fqm/lists tests

acquisitions/src/main/resources/thunderjet/mod-orders/features/piece-sequence-numbers.feature, acquisitions/src/main/resources/thunderjet/mod-orders/orders.feature
[[MODORDERS-1356] BE - Create Sequence field in receiving](https://folio-org.atlassian.net/browse/MODORDERS-1356)
Add new scenario to cover all piece creation scenarios
=> [MODORDERS-1356] BE - Create Sequence field in receiving

edge-fqm/src/main/resources/corsair/edge-fqm/edge-fqm-junit.feature
=> MODFQMMGR-858 add missed permissions

mod-linked-data/src/main/resources/citation/mod-linked-data/features/authority/samples/authority_person_update.json
Include sourceVersion in PUT request payload to avoid opti…
=> FAT-21885: Include sourceVersion in PUT request payload to avoid optimistic lock exception

data-import-large-scale-tests/src/main/resources/karate-config.js
The test cluster is overloaded
Moving LSDI tests to other cluster to check performance
[FAT-21663](https://folio-org.atlassian.net/browse/FAT-21663)
=> FAT-21663: Moving LSDI tests to other cluster

acquisitions/src/main/resources/thunderjet/mod-mosaic/features/create-order-2-from-default-template.feature, acquisitions/src/main/resources/thunderjet/mod-mosaic/init-mosaic.feature
- <https://folio-org.atlassian.net/browse/MODMO-19>
- Replace POST and DELETE /mosaic/configuration endpoints with a single PUT one
- Remove redundant prerequisite permissions
- Test on Eureka environment deployed locally
> mod-mosaic folder
=> [MODMO-19]. Update mosaic configuration endpoints & assertion
