gulfstream/src/test/java/org/folio/GulfstreamTests.java
gulfstream/src/test/resources/domain/oaipmh/oaipmh-q3-marc_withholdings.feature
gulfstream/src/test/resources/karate-config.js

1. Scenario – request instance records identifiers
Given instance record source=FOLIO or MARC
And instance create/update/delete date fits OAI-PMH request parameters (from/until)
And instance record can be exposed according to suppressed and deleted records support rules
When OAI-PMH request verb=ListIdentifiers
And metadataPrefix = marc21 or oai_dc
Then the record’s identifier is present in ListIdentifiers response
2. Scenario – request identifiers of instance records with holdings and items
Given instance record source= FOLIO or MARC
And instance create/update/delete date or its holdings/items create/update/delete date fits OAI-PMH request parameters (from/until)
And instance record can be exposed according to suppressed and deleted records support rules
When OAI-PMH request …

MODOAIPMH-70: Integration tests

---

mod-data-export/src/test/java/org/folio/ModDataExportApiTest.java
mod-data-export/src/test/resources/domain/dataexport/features/job-profiles.feature
mod-data-export/src/test/resources/domain/dataexport/features/mapping-profiles.feature
mod-data-export/src/test/resources/global/variables.feature
mod-data-export/src/test/resources/karate-config.js
mod-data-export/src/test/resources/samples/job_profile.json
mod-data-export/src/test/resources/samples/mapping_profile.json

**PURPOSE:**
https://issues.folio.org/browse/FAT-128
**APPROACH**
Add CRUD tests for profiles, method order in class, and samples.
Verified on testing, screenshot from testRail.

FAT-128 Add API tests for profiles

---

edge-dematic/src/main/resources/domain/edge-dematic/edge-dematic-junit.feature
edge-dematic/src/main/resources/domain/edge-dematic/features/lookup-asr-requests.feature
edge-dematic/src/main/resources/domain/edge-dematic/features/lookup-new-asr-items.feature
edge-dematic/src/main/resources/domain/edge-dematic/features/update-asr-item-being-retrieved.feature
edge-dematic/src/main/resources/domain/edge-dematic/features/update-asr-item-status-available.feature
edge-dematic/src/main/resources/global/prepare-test-data.feature
edge-dematic/src/main/resources/karate-config.js

[FAT-148](https://issues.folio.org/browse/FAT-148) - API Tests for edge-dematic
Verified on [folio-testing](https://folio-testing.dev.folio.org)
1. lookup asr requests
2. lookup new asr items
3. update asr item being retrieved
4. update asr item status available

FAT-148 - API Tests for edge-dematic

---

pom.xml

Resolves [FAT-200](https://issues.folio.org/browse/FAT-200)
Make mod-calendar, mod-event-config, mod-notify, mod-sender, mod-template-engine visible in the cucumber report
Add modules to the common pom file.

FAT-200 Add modules to pom

---

quick-marc/src/main/resources/domain/mod-quick-marc/features/setup/setup.feature
quick-marc/src/test/java/org/folio/QuickMarcApiTest.java

Fix tests failure https://issues.folio.org/browse/FOLIO-3117
* updated record type from MARC to MARC_BIB

FOLIO-3117 - Folio integration tests for mod-quick-marc fails

---

quick-marc/src/main/resources/domain/mod-quick-marc/features/setup/samples/record.json
quick-marc/src/main/resources/domain/mod-quick-marc/features/setup/setup.feature
quick-marc/src/main/resources/domain/mod-quick-marc/quick-marc-junit.feature

Fixed test for mod-quick-marc
- fixed test data (006 field) for record.json
- added permission for getting titles (precedingSucceedingTitlesClient) in mod-inventory
- added sleep for waiting while all modules is started
https://issues.folio.org/browse/FOLIO-3117

FOLIO-3117 Folio integration tests for mod-quick-marc fails

---

quick-marc/src/main/resources/domain/mod-quick-marc/features/quick-marc-record-status.feature

Changed message for exception if qmRecordId is null
Modified message in test data
https://issues.folio.org/browse/MODQM-127

MODQM-127 MARC record does NOT open after saving an invalid field

---

acquisitions/src/main/resources/domain/mod-invoice/features/voucher-numbers.feature
acquisitions/src/main/resources/domain/mod-invoice/invoice.feature
acquisitions/src/test/java/org/folio/InvoicesApiTest.java

[MODINVOSTO-120](https://issues.folio.org/browse/MODINVOSTO-120) - Cannot set voucher "Starting number" or reset sequence
Simply test setting the start number and a syntax error.

[MODINVOSTO-120] Test the voucher number start

---

mod-oai-pmh/src/test/java/org/folio/ModOaiPmhTests.java
testrail-integration/src/main/java/org/folio/test/TestBase.java

[FAT-924](https://issues.folio.org/browse/FAT-924) - folio-integration-tests: Bump karate from 0.9.6 to >= 1.0.1

[FAT-924] - fix cucumber report generation as xml

---

mod-circulation/src/main/resources/domain/mod-circulation/features/loans.feature

[FAT-1003](https://issues.folio.org/browse/FAT-1003)
_Create Karate test for Loans: When an loaned item is checked in at a service point that serves its location and no request exists, change the item status to Available (circ-13)_

FAT-1003 Created Karate test for Loans

---

mod-circulation/src/main/resources/domain/mod-circulation/circulation-junit.feature
mod-circulation/src/main/resources/domain/mod-circulation/features/loans.feature

Increase mod-circulation coverage by integration tests
Created karate test for Loans: When an item that had the status of restricted that was checked out is checked in, set the item status to Available
https://issues.folio.org/browse/FAT-1009

FAT-1009 Loans: Item with Restricted status should change status to Available after it is checked in

---

mod-circulation/src/main/resources/domain/mod-circulation/features/loans.feature

[FAT-1011](https://issues.folio.org/browse/FAT-1011)
_Create Karate test for Loans: When an item that had the status of in process that was checked out is checked in, set the item status to Available_

Fat 1011: When an item that had the status of in process that was checked out is checked in, set the item status to Available

---

acquisitions/src/main/resources/domain/mod-orders/features/change-location-when-receiving-piece.feature
acquisitions/src/main/resources/domain/mod-orders/orders.feature
acquisitions/src/test/java/org/folio/OrdersApiTest.java

[MODORDERS-616](https://issues.folio.org/browse/MODORDERS-616) - New holdingId is not saved into piece when location is changed during receiving
Added a new test for this case, checking the piece's holding id is the one of the holding with the new location.

[MODORDERS-616] Test changing location when receiving a piece

---

mod-circulation/src/main/resources/vega/mod-circulation/features/requests.feature
mod-circulation/src/main/resources/vega/mod-circulation/features/util/initData.feature

[FAT-1031](https://issues.folio.org/browse/FAT-1031)
_Given an item Id, a user Id, and a pickup location, attempt to create a hold request when the applicable request policy disallows holds_

FAT-1031: Given an item Id, a user Id, and a pickup location, attempt to create a hold request when the applicable request policy disallows holds

---

mod-circulation/src/main/resources/vega/mod-circulation/circulation-junit.feature
mod-circulation/src/main/resources/vega/mod-circulation/features/requests.feature
mod-circulation/src/main/resources/vega/mod-circulation/features/root.feature

[FAT-1032](https://issues.folio.org/browse/FAT-1032)
_Given an item Id, a user Id, and a pickup location, attempt to create a recall request when the applicable request policy disallows recalls_

FAT-1032: Given an item Id, a user Id, and a pickup location, attempt to create a recall request when the applicable request policy disallows recalls

---

mod-circulation/src/main/resources/vega/mod-circulation/circulation-junit.feature
mod-circulation/src/main/resources/vega/mod-circulation/features/requests.feature
mod-circulation/src/main/resources/vega/mod-circulation/features/root.feature
mod-circulation/src/main/resources/vega/mod-circulation/features/util/initData.feature

[FAT-1034](https://issues.folio.org/browse/FAT-1034)
_Requests: Given an item Id, a user Id, and a pickup location, attempt to create a hold request when the applicable request policy allows holds, but item is of status "Available", "Recently returned", "In process (not requestable)", "Declared lost", "Lost and paid", "Aged to lost", "Claimed returned", "Missing from ASR", "Long missing", "Retrieving from ASR", "Withdrawn", "Order closed", "Intellectual item", "Unavailable", or "Unknown" (should fail)_
- Learned necessary sent requests and then necessary received responses

FAT-1034 Attempt to create a hold request when request policy allows it but item status does not (should fail)

---

acquisitions/src/main/resources/karate-config.js
acquisitions/src/main/resources/thunderjet/cross-modules/cross-modules-junit.feature
acquisitions/src/main/resources/thunderjet/cross-modules/cross-modules.feature
acquisitions/src/main/resources/thunderjet/cross-modules/features/pay-invoice-with-new-expense-class.feature
acquisitions/src/test/java/org/folio/CrossModulesApiTest.java
mod-circulation/src/main/resources/vega/mod-circulation/circulation-junit.feature
mod-circulation/src/main/resources/vega/mod-circulation/features/requests.feature
mod-circulation/src/main/resources/vega/mod-circulation/features/root.feature
mod-circulation/src/main/resources/vega/mod-circulation/features/util/initData.feature
mod-notes/src/main/resources/karate-config.js
mod-notes/src/main/resources/spitfire/mod-notes/features/note-links.feature
mod-notes/src/main/resources/spitfire/mod-notes/features/note-types.feature
mod-notes/src/main/resources/spitfire/mod-notes/features/notes.feature
mod-notes/src/main/resources/spitfire/mod-notes/features/samples/note-links.json
mod-notes/src/main/resources/spitfire/mod-notes/features/samples/note-put.json
mod-notes/src/main/resources/spitfire/mod-notes/features/setup/get-default-note-type.feature
mod-notes/src/main/resources/spitfire/mod-notes/features/setup/setup-test-note-type.feature
mod-notes/src/main/resources/spitfire/mod-notes/features/setup/setup-test-note.feature
mod-notes/src/test/java/org/folio/ModNotesTest.java

[FAT-1035](https://issues.folio.org/browse/FAT-1035)
_Given an item Id, a user Id, and a pickup location, attempt to create a recall request when the applicable request policy allows recalls, but item is of status "Available", "Recently returned", "Missing", "In process (not requestable)", "Declared lost", "Lost and paid", "Aged to lost", "Claimed returned", "Missing from ASR", "Long missing", "Retrieving from ASR", "Withdrawn", "Order closed", "Intellectual item", "Unavailable", or "Unknown" (should fail)"_

FAT-1035: Attempt to create a recall request when request policy allows it but item status does not (should fail)

---

mod-kb-ebsco-java/src/main/resources/spitfire/mod-kb-ebsco-java/features/packages.feature
mod-kb-ebsco-java/src/main/resources/spitfire/mod-kb-ebsco-java/features/setup/destroy.feature
mod-quick-marc/src/main/resources/karate-config.js
mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/quick-marc-records.feature
mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/setup/setup.feature
mod-quick-marc/src/test/java/org/folio/QuickMarcApiTest.java

If quick marc feature falls and attempts are over, it start it again
- Fix endless feature calling
- Wait for all modules to be launched JUST once
- kb-ebsco Ignore not found error while deleting
https://issues.folio.org/browse/FAT-1181

FAT-1181 Quick marc - endless waiting

---

mod-circulation/src/main/resources/vega/mod-circulation/circulation-junit.feature
mod-circulation/src/main/resources/vega/mod-circulation/features/requests.feature

Increase mod-circulation coverage by integration tests, decrease tech debt
Created karate test for Requests: Given an item Id, a user Id, and a pickup location, attempt to create a hold request when the applicable request policy allows holds and item status is not "Available", "Recently returned", "In process (not requestable)", "Declared lost", "Lost and paid", "Aged to lost", "Claimed returned", "Missing from ASR", "Long missing", "Retrieving from ASR", "Withdrawn", "Order closed", "Intellectual item", "Unavailable", or "Unknown"
https://issues.folio.org/browse/FAT-1037

FAT-1037 Hold request successfully created when request policy and item status allow it

---

acquisitions/src/main/resources/thunderjet/cross-modules/cross-modules.feature
acquisitions/src/main/resources/thunderjet/cross-modules/features/change-poline-fd-and-pay-invoice.feature
acquisitions/src/test/java/org/folio/CrossModulesApiTest.java

[MODORDERS-645](https://issues.folio.org/browse/MODORDERS-645) - Invoice payment fails if order line fund distribution is changed before invoice approval
Added a new cross-module test.

[MODORDERS-645] Remove and add order line fund distribution before invoice approval

---

mod-search/src/test/resources/falcon/mod-search/filters/sort-by-option-search.feature
mod-search/src/test/resources/falcon/mod-search/search/authority-single-property-search.feature
mod-search/src/test/resources/falcon/mod-search/set-up/create-test-data.feature
mod-search/src/test/resources/samples/test-data/authorities/CorporateAuthority.json
mod-search/src/test/resources/samples/test-data/authorities/MeetingAuthority.json
mod-search/src/test/resources/samples/test-data/authorities/PersonalAuthority.json

This merge request adds new integration tests to authority search and fixes failed tests after updating authority search.
- Fix the `keyword` search tests for authority
- Add tests non-title fields
- Fix sorting by authority `authRefType` because `Other` option has been removed

FAT-1150 Fix integration tests for authority search

---

edge-patron/src/main/resources/karate-config.js
edge-rtac/src/main/resources/karate-config.js

I had to guess a bit on the exact configuration of this file.  I'm assuming here that it's the third branch of the environment if/else code that needs to be modified.  I tried using the exact code used by edge-dematic and edge-caiasoft in that branch, but found that this caused all tests in the module to fail.  Tests also fail in edge-dematic and edge-caiasoft when using that branch as well, so I changed the code to use the test URL and the same credentials it uses for the testing branch.

FAT-1480: Prokopovych edge module tests should use testing environment

---

mod-bulk-edit/src/main/resources/samples/user/expected-users-preview-after-identifiers-job.json
mod-bulk-edit/src/main/resources/samples/user/expected-users-preview-after-update-job.json

The user "active" field behaves weirdly in snapshot env. After the update job that changes the field from false to true, the value of the field is set from true to false back by the system automatically, and after several seconds the value turns back to be true. It breaks the consistency within tests. In testing env it works as expected but for now lets omit this field verification and will put attention to this in the scope of [FAT-1645](https://issues.folio.org/browse/FAT-1645)
JYI the filed value is still verified against the identifiers job and expected CSV file after the update job has been done. In the scope of the mentioned ticket, the additional verification with JSON comparing should be moved back.

FAT-1592: Remove active filed verificiation

---

testrail-integration/pom.xml

Upgrade Vert.x from 3.9.3 to 4.2.7 fixing Netty:
* HTTP Request Smuggling https://nvd.nist.gov/view/vuln/detail?vulnId=CVE-2021-21295
* Denial of Service (DoS) https://nvd.nist.gov/view/vuln/detail?vulnId=CVE-2021-37136
* Denial of Service (DoS) https://nvd.nist.gov/view/vuln/detail?vulnId=CVE-2021-37137
Upgrade jackson-databind from 2.11.3 to 2.13.2.1 fixing Denial of Service (DoS)
https://nvd.nist.gov/view/vuln/detail?vulnId=CVE-2020-36518
Upgrade commons-lang3 from 3.10 to latest 3.12.0 fixing bugs.

Upgrade Vert.x (Netty), jackson-databind, commons-lang3

---

mod-search/src/test/resources/samples/test-data/instances.json
mod-search/src/test/resources/spitfire/mod-search/browse/authority-browse.feature
mod-search/src/test/resources/spitfire/mod-search/browse/call-number-browse.feature
mod-search/src/test/resources/spitfire/mod-search/browse/subject-browse.feature

Fix failed karate tests after implemting previous/next values for browsing by subjects, call-numbers and authority-record heading types.

MSEARCH-342 Add prev/next values validation for mod-search tests

---

pom.xml

Fixing
* Spring4Shell Remote Code Execution https://nvd.nist.gov/vuln/detail/CVE-2022-22965
* Privilege Escalation https://nvd.nist.gov/vuln/detail/CVE-2021-22118
* Improper Input Validation https://nvd.nist.gov/view/vuln/detail?vulnId=CVE-2021-22060
* Improper Output Neutralization for Logs https://nvd.nist.gov/view/vuln/detail?vulnId=CVE-2021-22096

Upgrade Spring from 5.2.11.RELEASE to 5.3.19 (CVE-2022-22965)

---

mod-circulation/src/main/resources/vega/mod-circulation/circulation-junit.feature
mod-circulation/src/main/resources/vega/mod-circulation/features/loans.feature

[FAT-1001](https://issues.folio.org/browse/FAT-1001)
_When an existing loan is aged to lost update agedToLostDate and aged to lost policy specifies delayed billing,update lostItemHasBeenBilled,dateLostItemShouldBeBilled_

FAT-1001: Fix time interval issue to get aged-to-lost loan

---

mod-search/src/test/resources/spitfire/mod-search/browse/authority-browse.feature
mod-search/src/test/resources/spitfire/mod-search/filters/facet-search.feature
mod-search/src/test/resources/spitfire/mod-search/filters/sort-by-option-search.feature
mod-search/src/test/resources/spitfire/mod-search/search/authority-single-property-search.feature
mod-search/src/test/resources/spitfire/mod-search/set-up/create-test-data.feature
teams-assignment.json

Edit tests after:
- Authority browsing fix: [MSEARCH-342](https://github.com/folio-org/mod-search/pull/252)
- Revert non-title authority fields and add new headingTypeExt: [MSEARCH-346](https://github.com/folio-org/mod-search/pull/249)

FAT-1722 mod-search: Fix Karate test failures

---

acquisitions/src/main/resources/thunderjet/mod-orders/features/parallel-update-order-lines-different-orders.feature
acquisitions/src/main/resources/thunderjet/mod-orders/reusable/get-order-line.feature
acquisitions/src/test/java/org/folio/OrdersApiTest.java
testrail-integration/src/main/java/org/folio/test/TestBase.java

[MODFISTO-304](https://issues.folio.org/browse/MODFISTO-304) - Lock budgets to update totals
Used one of the tests initially created for MODFISTO-260, which updates order lines from different orders. With the MODFISTO-304 fix, it doesn't fail anymore.
This required a change to TestBase, to specify thread count (as was done in the MODFISTO-260 PR).

[MODFISTO-304] Parallel update order line different orders

---

data-import/src/main/resources/karate-config.js

Fix karate pipline failure after implementing new build env approach
Removed overriding url and admin token.  Removing the lines below doesn't affect to running on other envs.
[FAT-964](https://issues.folio.org/browse/FAT-964)

FAT-964 Investigate causes for data-import-integration karate tests failure on autorun

---

mod-bulk-edit/src/main/resources/firebird/bulk-edit/features/bulk-edit-items-status.feature
mod-bulk-edit/src/main/resources/firebird/bulk-edit/features/bulk-edit-items.feature

[FAT-1688] : https://issues.folio.org/browse/FAT-1688
Karate tests for Bulk-Edit (Items) should be implemented to cover main business flow.
The test should cover scenario of:
1. updating item permanent location
2. updating item temporary location
3. removing item permanent location
4. removing item temporary location
5. any combination of the above.
1. (precondition) create several items -> upload file with identifiers -> verify preview -> download csv file with items (supported identifiers include: item barcode, item UUID, item HRID, item former identifier, item accession number and holdings HRID)
2. (precondition) create several items -> (precondition) prepare edited csv file -> upload edited csv file -> (validation) retrieve items and verify that items are updated.
3. (precondition) …

[FAT-1688]: Bulk-Edit (Items) API tests

---

mod-data-export/src/test/resources/firebird/dataexport/data-export-basic-junit.feature
mod-data-export/src/test/resources/karate-config.js

FAT-1601 ( https://issues.folio.org/browse/FAT-1601 ) 
Fix api karate tests failures for mod-data-export module 
1. Permission added : | 'inventory.instances.collection.get' | 
2. Module added : | 'mod-inventory' |
Output :

FAT 1601 ( Fix api karate tests failures for mod-data-export module )

---

mod-data-export/src/test/java/org/folio/ModDataExportApiTest.java
mod-data-export/src/test/resources/firebird/dataexport/features/export-for-authority.feature
mod-data-export/src/test/resources/firebird/dataexport/features/export-for-cql.feature
mod-data-export/src/test/resources/firebird/dataexport/features/export-for-holdings.feature
mod-data-export/src/test/resources/firebird/dataexport/features/export.feature

[FAT-2131] : https://issues.folio.org/browse/FAT-2131
Purpose/Overview:
Karate tests for ModDataExportApiTest were failed
after the dependency version were upgraded specifically for - 
<karate.junit.version>1.2.0</karate.junit.version>
<junit.version>5.8.2</junit.version> (edited) 
Couple of reason they failed - 
1. Issue with escaping the special character in the endpoint (question mark sign)
2. The test case scenarios had to be reordered so that the data export jobs were not effected.
Acceptance criteria:
Karate tests are passed on corresponding Jenkins job

[FAT-2131] https://issues.folio.org/browse/FAT-2131

---

pom.xml

Upgrade logback-classic from 1.2.3 to 1.2.11 fixing
a remote execution vulnerability:
https://nvd.nist.gov/vuln/detail/CVE-2021-42550

logback-classic 1.2.11 (CVE-2021-42550)

---

acquisitions/src/main/resources/thunderjet/mod-orders/features/reopen-order-creates-encumbrances.feature

[MODORDERS-706](https://issues.folio.org/browse/MODORDERS-706) - Create encumbrances if needed when reopening an order
This is a fix to PR #608.
Added a check that the encumbrance link was added when reopening the order.

[MODORDERS-706] Check encumbrance link after reopening

---

mod-login-saml/src/main/resources/core_platform/mod-login-saml/features/samlCallback.feature

As okapi now has access-control-allow-credentials=true by default.

Update header response check FOLIO-3554

---

acquisitions/src/main/resources/thunderjet/mod-finance/features/ledger-fiscal-year-rollover.feature

Check planned budget status after rollover.
[MODFISTO-338](https://issues.folio.org/browse/MODFISTO-338)

[MODFISTO-338] Update planned budget status to active during FY rollover

---

acquisitions/src/main/resources/thunderjet/mod-finance/features/current-budget-for-fund.feature

When we call createFund feature in the "current budget for fund" main scenario we should specify "code" param if not code will be retrieved from response.
[FAT-2408](https://issues.folio.org/browse/FAT-2408)

[FAT-2408] -  Missed param when call createFund function

---

acquisitions/src/main/resources/thunderjet/mod-finance/features/fiscal-year-totals.feature

After [MODFISTO-283](https://issues.folio.org/browse/MODFISTO-283) overEncumbrance calculation logic was changed but tests not updated. 
- Update with a new ammount overEncumbrance matching line
[FAT-2406](https://issues.folio.org/browse/FAT-2406)

[FAT-2406] - Set a new ammount due to changing calculation logic

---

acquisitions/src/main/resources/thunderjet/mod-gobi/gobi-junit.feature
acquisitions/src/main/resources/thunderjet/mod-gobi/gobi.feature

To fix test failing when destroy tenant
- Removing initialization data for tenant (deprecated approach)
[FAT-2100](https://issues.folio.org/browse/FAT-2100)

[FAT-2100] - Fixed destroy tenant of mod-gobi

---

mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/quick-marc-bib-records.feature
mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/setup/samples/setup-records/instance-links.json
mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/setup/setup.feature
mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/quick-marc-junit.feature

Cover new quickMarc bib record response field related to instance-authority linking
Cover instance-authority linking/unlinking on PUT quickMarc
- add authorityId field to linked fields
- add test for link/unlink marc bib fields
[MODQM-272](https://issues.folio.org/browse/MODQM-272)

MODQM-272 Update all bib-auth links on update record

---

mod-bulk-edit/src/main/resources/karate-config.js

[FAT-1645](https://issues.folio.org/browse/FAT-1645) - Bulk-edit(Users) move tests run to test tenant
Fix karate config and remove redundant login.
Verified on snapshot (only users):
Verified on jenkins testing env (all features):

FAT-1645 - Bulk-edit(Users) move tests run to test tenant

---

pom.xml
testrail-integration/pom.xml

Upgrade cucumber-reporting from 5.7.1 to 5.7.3, this indirectly upgrades jsoup from 1.15.1 to 1.15.3 fixing cross-site scripting (XSS) https://nvd.nist.gov/vuln/detail/CVE-2022-36033
Upgrade graal-sdk from 21.2.0 to 21.3.3.1 fixing 18 vulnerabilities https://security.snyk.io/package/maven/org.graalvm.sdk:graal-sdk/21.2.0
Upgrade commons-codec from 1.11 to 1.15 fixing Information Exposure https://app.snyk.io/vuln/SNYK-JAVA-COMMONSCODEC-561518
Upgrade snakeyaml from 1.29 to 1.33 fixing Denial of Service (DoS) https://nvd.nist.gov/vuln/detail/CVE-2022-25857
https://nvd.nist.gov/vuln/detail/CVE-2022-38749
Upgrade jackson-databind from 2.13.0 to 2.13.4.2 fixing Denial of Service (DoS) https://nvd.nist.gov/vuln/detail/CVE-2022-42003
Upgrade Vert.x from unsupported version 4.2.7 to supported …

FAT-3206: Upgrade vulnerable dependencies

---

pom.xml

https://issues.folio.org/browse/FAT-3206 = #746 upgraded graal-sdk from 21.2.0 to 21.3.3.1 fixing 18 vulnerabilities.
It was forgotten to also upgrade org.graalvm.js:js-scriptengine and org.graalvm.js:js from 21.2.0 to 21.3.3.1. This makes folio-integration-test hang.
Fix: Also upgrade graal's js-scriptengine and js.

FAT-3213: Fix graal upgrade

---

mod-calendar/src/main/resources/bama/mod-calendar/features/calendar-create.feature

This fixes [FAT-3244](https://issues.folio.org/browse/FAT-3244), [FAT-3245](https://issues.folio.org/browse/FAT-3245), and [FAT-3246](https://issues.folio.org/browse/FAT-3246).  3245 and 3246 were false negatives from 3244.
This issue was due to the change of the calendar API's multi-delete endpoint, a change which was made after these tests were written.  Since the calendars were not deleted successfully, all tests afterwards failed.

FAT-3244: Fix calendar deletion endpoint

---

mod-circulation/src/main/resources/vega/mod-circulation/features/requests.feature

Implement Karate test for Scenario: "When patron has exceeded their Patron Group Limit for 'Maximum number of overdue recalls', patron is not allowed to request items per Conditions settings"
JIRA: https://issues.folio.org/browse/FAT-1048

FAT-1048: When patron has exceeded their Patron Group Limit for 'Maximum number of overdue recalls', patron is not allowed to request items

---

data-import/src/main/resources/folijet/data-import/features/data-import-integration.feature

to handle intermittent error: 
> did not evaluate to 'true': response.entries[0].holdingsActionStatus == 'UPDATED' 
that appears due to holdingsActionStatus == null at the moment of data retrieving by test
[FAT-2302](https://issues.folio.org/browse/FAT-2302)

FAT-2302 - Review Karate test fails, then subsequent succeeds

---

mod-circulation/src/main/resources/vega/mod-circulation/features/requests.feature

Implement Karate tests for Scenario: "When patron has exceeded their Patron Group Limit for 'Maximum number of overdue recalls', patron is not allowed to request items per Conditions settings"
JIRA: https://issues.folio.org/browse/FAT-1048

FAT-1048: Deleted unnecessary retry configuration

---

acquisitions/src/main/resources/thunderjet/mod-orders/features/open-order-with-different-po-line-currency.feature

https://issues.folio.org/browse/FAT-3382
I have used the setScale method of BigDecimal
- http://www.c-jump.com/bcc/c157c/Week05/W05_0380_roundingmodehalfup.htm [ROUND_UP]
- http://www.c-jump.com/bcc/c157c/Week05/W05_0390_roundingmodehalfeve.htm [ROUND_HALF_EVEN]
- https://www.java67.com/2020/04/4-examples-to-round-floating-point-numbers-in-java.html

[FAT-3382] - fixed failed karate test with open-order-with-different-po-line-currency.feature

---

data-import/src/main/resources/folijet/data-import/features/data-import-integration.feature
data-import/src/main/resources/folijet/data-import/global/default-import-instance-holding-item.feature
data-import/src/main/resources/folijet/data-import/global/inventory_data_setup_util.feature
data-import/src/main/resources/folijet/data-import/global/mod_inventory_init_data.feature
data-import/src/main/resources/folijet/data-import/samples/location/locations.json

after locations movement from reference data to sample data in the inventory-storage the "FAT-1204 Import MARC file, match on location, update Holdings and Item locations" test keep fails because of used location absence.
Add used "ORWIG ETHNO CD (KU/CC/DI/O)" location to test data initialization.
[FAT-3397](https://issues.folio.org/browse/FAT-3397)

FAT-3397 - Review Karate test fails, then subsequent succeeds - Part 2

---

acquisitions/src/main/resources/thunderjet/mod-finance/features/ledger-fiscal-year-preview-rollover-need-close-budgets.feature

[MODFISTO-362](https://issues.folio.org/browse/MODFISTO-362)

[MODFISTO-362] Expense class code and status are not shown in test rollover results .csv file

---

acquisitions/src/main/resources/thunderjet/mod-orders/features/order-event.feature
acquisitions/src/main/resources/thunderjet/mod-orders/features/order-line-event.feature

https://issues.folio.org/browse/MODORDSTOR-323
After implementation of transactional outbox pattern logic to fetch outbox events from DB and send them to Kafka invoked each 2 sec. So we need to update karate tests accordingly

[MODFISTO-318]. Fixing karate tests after transactional outbox implementation

---

acquisitions/src/main/resources/thunderjet/cross-modules/features/cancel-invoice-linked-to-order.feature
acquisitions/src/main/resources/thunderjet/mod-invoice/reusable/cancel-invoice.feature
acquisitions/src/main/resources/thunderjet/mod-invoice/reusable/create-invoice-line.feature
acquisitions/src/main/resources/thunderjet/mod-orders/reusable/create-order-line.feature

[MODINVOICE-446](https://issues.folio.org/browse/MODINVOICE-446) - Encumbrance for Ongoing order remains "Released" after cancelling related invoice
Added a test to cancel an invoice for an ongoing order.
Also edited the whole `cancel-invoice-linked-to-order` feature to use more reusable code, and added 2 new reusable features.

[MODINVOICE-446] Cancel invoice for ongoing order

---

acquisitions/src/main/resources/thunderjet/mod-finance/features/budget-and-fund-optimistic-locking.feature
acquisitions/src/main/resources/thunderjet/mod-finance/finance.feature
acquisitions/src/test/java/org/folio/FinanceApiTest.java

[MODFIN-264](https://issues.folio.org/browse/MODFIN-264) - Optimistic locking ignored when changing expense class and adding group
Added a new test for optimistic locking and rollbacks for budget and fund updates.

[MODFIN-264] Budget and fund optimistic locking and rollback

---

mod-bulk-edit/src/main/resources/firebird/bulk-edit/features/bulk-edit-items-status.feature

[FAT-4208](https://issues.folio.org/browse/FAT-4208) - Karate test fail: [firebird/bulk-edit] ModBulkEditApiTest {2} firebird/bulk-edit/features/bulk-edit-items-status.feature
Verified against karate testing environment:

FAT-4208 - Karate test fail: [firebird/bulk-edit] ModBulkEditApiTest {2} firebird/bulk-edit/features/bulk-edit-items-status.feature

---

common/src/main/resources/common/setup-users.feature

Resolves FAT-4401
Daily integration tests runs fail consistently when adding permissions to test users. This is on test setup and not related to the actual functionality being tested. Integration tests run normally on local environments but fail consistently in CI. The hypothesis is that when a new tenant is created for a test, appropriate permissions are not posted to the tenant by okapi , but the test suite is asking to add permissions that don't exist yet. The hope is that the permissions arrive before the retry policy expires. Other avenues will be explored if this is not successful.

FAT-4401 add retry when adding permission to test user

---

acquisitions/src/main/resources/thunderjet/cross-modules/features/partial-rollover.feature
acquisitions/src/main/resources/thunderjet/cross-modules/features/rollover-with-closed-order.feature
acquisitions/src/main/resources/thunderjet/mod-finance/features/group-and-ledger-transfers-after-rollover.feature
acquisitions/src/main/resources/thunderjet/mod-finance/features/ledger-fiscal-year-preview-rollover.feature
acquisitions/src/main/resources/thunderjet/mod-finance/features/ledger-fiscal-year-rollover-MODFISTO-247.feature
acquisitions/src/main/resources/thunderjet/mod-finance/features/ledger-fiscal-year-rollover-cash-balance.feature
acquisitions/src/main/resources/thunderjet/mod-finance/features/ledger-fiscal-year-rollover-pol-and-system-currencies-are-different.feature
acquisitions/src/main/resources/thunderjet/mod-finance/features/ledger-fiscal-year-rollover.feature
acquisitions/src/main/resources/thunderjet/mod-finance/features/ledger-fiscal-year-rollovers-multiple.feature
acquisitions/src/main/resources/thunderjet/mod-finance/features/unopen-order-after-rollover-MODORDERS-542.feature
acquisitions/src/main/resources/thunderjet/mod-finance/finance-junit.feature
acquisitions/src/main/resources/thunderjet/mod-finance/finance.feature
acquisitions/src/main/resources/thunderjet/mod-orders/features/moving_expended_value_to_newly_created_encumbrance.feature
acquisitions/src/test/java/org/folio/FinanceApiTest.java

To test rollover following by [miro diagram](https://miro.com/app/board/uXjVOkZO8Qk=/) (Cash balance section)
- Implemented new test scenario
- Replace boolean field to rolloverBudgetValue enum
- Replaced pauses after rollover start scenario to retries
[MODFISTO-371](https://issues.folio.org/browse/MODFISTO-371)

[MODFISTO-371] - Add support to rollover cash balance during FY rollover

---

acquisitions/src/main/resources/thunderjet/mod-finance/features/ledger-totals.feature

[MODFIN-308](https://issues.folio.org/browse/MODFIN-308) - Maintain displaying "Available" as a negative number for group and ledger
Updated test to check available amount in summary.
Did not add a check for group totals, as this is already done in unit tests, it is easy to check manually, and the change was minimal.

[MODFIN-308] Summary available can now be negative

---

acquisitions/src/main/resources/thunderjet/mod-orders/features/moving_expended_value_to_newly_created_encumbrance.feature

Due to test failing after rewriting orders rollover processing in an async way
- Added retry to wait for end of overall rollover
[MODORDERS-865](https://issues.folio.org/browse/MODORDERS-865)

[MODORDERS-865] - Rewrite the orders rollover interaction in an asynchronous way

---

mod-inn-reach/src/main/resources/volaris/mod-inn-reach/mocks/general/mockserverInitialization.json

https://issues.folio.org/browse/FAT-5561
Add the missing mockserverInitialization.json file to the repository which can be used for mock server setup in rancher space.
Added the json file in the code repository.
Always have a backup of such configuration files in the code base.

FAT-5561 - Add the missing mockserverInitialization.json file

---

acquisitions/src/main/resources/thunderjet/cross-modules/cross-modules.feature
acquisitions/src/main/resources/thunderjet/cross-modules/features/update-encumbrance-links-with-fiscal-year.feature
acquisitions/src/main/resources/thunderjet/mod-finance/features/budget-expense-classes.feature
acquisitions/src/main/resources/thunderjet/mod-finance/features/group-expense-classes.feature
acquisitions/src/main/resources/thunderjet/mod-finance/reusable/createTransaction.feature
acquisitions/src/main/resources/thunderjet/mod-invoice/reusable/create-invoice.feature
acquisitions/src/test/java/org/folio/CrossModulesApiTest.java

[MODINVOICE-474](https://issues.folio.org/browse/MODINVOICE-474) - Update the encumbrance when using a past fiscal year
New cross-module feature. Updated other files to make it easier to create transactions and create an invoice with a fiscal year id.
Review together with the [mod-invoice PR](https://github.com/folio-org/mod-invoice/pull/409).

[MODINVOICE-474] Invoice line encumbrance links updated with fiscal year

---

acquisitions/src/main/resources/thunderjet/cross-modules/features/approve-invoice-using-different-fiscal-years.feature
acquisitions/src/main/resources/thunderjet/mod-invoice/features/set-invoice-fiscal-year-automatically.feature
acquisitions/src/main/resources/thunderjet/mod-invoice/invoice.feature
acquisitions/src/test/java/org/folio/InvoicesApiTest.java

[MODINVOICE-473](https://issues.folio.org/browse/MODINVOICE-473) - Save invoice fiscal year if it is undefined after any fund distribution change
- New test checking invoice fiscal year is set automatically
- Updated another test so it keeps running with the new constraints (new safeguards made requests fail too early)
Should be reviewed together with the related [mod-invoice PR](https://github.com/folio-org/mod-invoice/pull/410).

[MODINVOICE-473] Set invoice fiscal year automatically

---

data-import/src/main/resources/folijet/data-import/global/default-import-instance-holding-item.feature

$9 subfield in MARC bib is used for indicating authorityId, there were introduced changes not to populate authorityId in instance fields during data-import (https://issues.folio.org/browse/MODSOURMAN-974)
https://issues.folio.org/browse/FAT-5889

FAT-5889 - Remove check of the $9 mapping to authorityId

---

mod-source-record-manager/src/main/resources/folijet/mod-source-record-manager/source-record-manager.feature

defined mod-entities-links for modules deployment to provide mapping parameters by /mapping-metadata/type/{recordType} endpoint
https://issues.folio.org/browse/FAT-5839

FAT-5839 - Provided mod-entities-links for deployment before tests run

---

acquisitions/src/main/resources/thunderjet/mod-consortia/features/user-tenant-associations.feature

Resolves [FAT-5974](https://issues.folio.org/browse/FAT-5974) Karate test fail: [thunderjet/mod-consortia] ConsortiaApiTest {3} thunderjet/mod-consortia/features/tenant.feature
Related [FAT-6028](https://issues.folio.org/browse/FAT-6028) Cover Consortia User Tenant associations with karate tests

[FAT-5974] Karate test fail in [mod-consortia]

---

mod-search/src/test/resources/samples/test-data/items.json
mod-search/src/test/resources/spitfire/mod-search/browse/call-number-browse.feature

Reflect mod-search changes in tests
[MSEARCH-523](https://issues.folio.org/browse/MSEARCH-523)
- Remove call number typeId from one of items so it's inherited from holdings
- Add assertion that callNumberType is inherited from holdings in item

MSEARCH-523 Include call number type id from Holdings in Items record when not specified

---

mod-bulk-edit/src/main/resources/firebird/bulk-edit/bulk-edit-junit.feature
mod-bulk-edit/src/main/resources/firebird/bulk-edit/diku-bulk-edit-junit.feature
mod-bulk-edit/src/main/resources/firebird/bulk-edit/features/bulk-edit-items-status.feature
mod-bulk-edit/src/main/resources/firebird/bulk-edit/features/bulk-edit-items.feature
mod-bulk-edit/src/main/resources/firebird/bulk-edit/features/bulk-edit-users.feature
mod-bulk-edit/src/test/java/org/folio/ModBulkEditApiTest.java

Bulk operation logic is covered by bulk-operations tests. Bulk-edit tests can be ignored because they cover logic in mod-data-export-spring/mod-data-export-worker that isn't used for bulk operations anymore.
Using of @ignore annotation for legacy features.

FAT-6135 - Ignore legacy bulk-edit features

---

mod-circulation/src/main/resources/vega/mod-circulation/features/loans.feature

Resolves FAT-6711
When rules are updated directly in storage, it takes 3min for mod-circulation to update its cache
Update rules using PUT circulation/rules endpoint in mod-circulation instead of circulation-rules-storage endpoint in mod-circulation-storage

FAT-6711 Use another endpoint to update rules

---

mod-circulation/src/main/resources/vega/mod-circulation/circulation-junit.feature
mod-circulation/src/main/resources/vega/mod-circulation/features/parallelCheckOut.feature
mod-circulation/src/main/resources/vega/mod-circulation/features/samples/checkout-Lock-settings-request.json
mod-circulation/src/main/resources/vega/mod-circulation/features/samples/policies/loan-policy-entity-with-limit-request.json
mod-circulation/src/main/resources/vega/mod-circulation/features/util/initData.feature
mod-circulation/src/test/java/org/folio/ModCirculationTests.java

The purpose of the change is to test the fix of concurrency issue which is implemented as part of feature https://issues.folio.org/browse/UXPROD-3515 during checkout process.
we are setting the loan limit as 1 and checking out two items in parallel. The system should allow only one item to do checkout and other item will get the Limit exceeded error when the feature is enabled. 
Note : If the feature is not enabled, behavior is inconsistent.
**Evidence :** Please find the behavior of the checkout by barcode API with / without feature flag enabled.

FAT-6575 - Implement tests to check the concurrency issue during checkout

---

mod-circulation/src/main/resources/vega/mod-circulation/features/util/initData.feature

This error is being caused by a name collision between tests in root.feature and initData.feature.  Both are trying to create a material type with the name "Book."  But you cannot have two material types with identical names.  So I've changed the initData.feature test to use a random string as the material type name.  the root.feature test relies more on the name, which is present in sample data files, so changing it there would have ripple effects on other tests.

FAT-7004: renaming material type

---

data-import/src/main/resources/folijet/data-import/samples/samples_for_upload/default-marc-bib-rules.json

_To fix the Scenario: FAT-4701 check that default rules in karate tests matches what is in the SRM under test._
_Use the actual JSON response from SRM. We see that test Scenario: FAT-4701... is not failing anymore:_
https://jenkins-aws.indexdata.com/job/Testing/job/Karate%20tests/674
_[JIRA](https://issues.folio.org/browse/FAT-6493)_

FAT-6493: actualize match rules JSON according to SRM response

---

data-import/src/main/resources/folijet/data-import/features/get-completed-job-execution.feature

_Wait for complete of a job run._
_Increasing the total timeout for the job completeness polling._

FAT-6493: increase the total timeout for the job completeness polling

---

data-import/src/main/resources/folijet/data-import/features/data-import-integration.feature

_To fix FAT-1473 Test OCLC import doesn't duplicate control fields scenario._
_Actualize OCLC credentials._
Tested:

FAT-6493: actualize OCLC credentials

---

mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/holdings.feature
mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/items.feature

Fixing [FAT-7774](https://issues.folio.org/browse/FAT-7774) - Karate test fail: [firebird/mod-bulk-operations] ModBulkOperationsApiTest {2}  firebird/mod-bulk-operations/features/items.feature
Replacing '' to '#null' for some fields

FAT-7774 - Bulk Operation test failures

---

README.md
edge-inn-reach/src/main/resources/karate-config.js
edge-inn-reach/src/main/resources/volaris/edge-inn-reach/features/central-server.feature
mod-inn-reach/src/main/resources/karate-config.js
mod-inn-reach/src/main/resources/volaris/mod-inn-reach/features/central-server.feature

The purpose of this PR is to move centeralServerUrl to karate-config.js file which can be configured and changed easily.
In edge-inn-reach central-server.feature file there was need to replace the hardcoded value with configurable URL form karate.config.js file. This will be sufficient for both the central-server.feature file present in md/edge-inn-reach karate runs.

[RANCHER-971] - Moved mocked server url to karate-config.js file.

---

mod-circulation/src/main/resources/vega/mod-circulation/features/requests.feature
mod-circulation/src/main/resources/vega/mod-circulation/features/tlr-requests.feature

Fix error message spelling for pickup service point validation.
Resolves [FAT-7865](https://issues.folio.org/browse/FAT-7865).

FAT-7865: Fix error message spelling for pickup service point validation

---

mod-circulation-storage/src/main/resources/vega/mod-circulation-storage/features/request-policies.feature

Return only one error during request policy validation.
Resolves [FAT-7866](https://issues.folio.org/browse/FAT-7866).

FAT-7866: Return only one error during request policy validation

---

mod-oai-pmh/src/test/resources/global/init_data/postRecord.feature
mod-oai-pmh/src/test/resources/global/init_data/srs_init_data.feature
mod-oai-pmh/src/test/resources/samples/marc_record.json

Fix issue relating to creation of SRS records
The main problem comes from changes introduced in https://issues.folio.org/browse/MODSOURCE-530. To avoid of duplicate verification subfields from "999" were deleted, matchedId set as Id. This allows to avoid duplicate creation.

FAT-7778_FAT-7779 - SRS records creation failure

---

acquisitions/src/main/resources/global/inventory.feature
acquisitions/src/main/resources/global/variables.feature
acquisitions/src/main/resources/thunderjet/mod-orders/features/productIds-field-error-when-attempting-to-update-unmodified-order.feature

MODORDERS-658 isn't actual anymore. After implementing MODORDERS-927 productIds will be updated on PUT operation.
- Added 'Invalid ISBN' identifier type
- Updated scenario to follow MODORDERS-927 changes
[MODORDERS-927](https://issues.folio.org/browse/MODORDERS-927)

[MODORDERS-927] - Implement interception and update of invalid ISBNs during the POL update process

---

mod-audit/src/main/resources/global/initTest.feature

The purpose of this PR is to fix the failing test cases for mod-audit.
The personal data should be specified during user creation without which NPE was thrown.

[FAT-8556] - Added personal object details while creating the user.

---

edge-oai-pmh/src/main/resources/firebird/edge-oai-pmh/edge-oai-pmh-junit.feature

Prevent failures.
Extend pause before modules setup.

Extend pause before module setup edge-oai-pmh-junit.feature

---

acquisitions/src/main/resources/thunderjet/mod-finance/features/ledger-fiscal-year-preview-rollover.feature

Due to the fact that rollovers were not executed sequentially, it is likely that lock errors occurred. 
It was decided to initiate a rollover only after the completion of the previous one.

[FAT-9139] - Fixed randomly failed rollover preview test

---

mod-entities-links/src/main/resources/spitfire/mod-entities-links/features/samples/setup-records/authority.json
mod-entities-links/src/main/resources/spitfire/mod-entities-links/links-junit.feature

_Fix failing tests from scheduled build for mod-entities-links from_
_Adjust tests for Authority APIs and Instance linking to reflect the latest changes introduced in mod-entities-links, specifically those related to Authority APIs_
[_FAT-8301_](https://issues.folio.org/browse/FAT-8301)

FAT-8301: Fix and adjust authority tests

---

mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/users-positive-scenarios.feature

Bulk-Operations: make pause before users commit preview to let preview to be completed.

FAT-9186 - Make pause before users commit preview

---

mod-source-record-manager/src/main/resources/folijet/mod-source-record-manager/features/job-execution.feature

User was renamed that caused test failure. We just need to verify that it is not null

FAT-9193 Fixed verification of JobExecution metadata after user renaming

---

mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/users-positive-scenarios.feature
mod-search/src/test/resources/spitfire/mod-search/search/resource-job-ids-search.feature
mod-source-record-manager/src/main/resources/folijet/mod-source-record-manager/features/job-execution.feature

_Fix failed test case from scheduled run related to deletion of linked authority._
_Add timeout to wait for some time in order to allow authority delete event to be processed._
[_FAT-8312_](https://issues.folio.org/browse/FAT-8312)

FAT-8312: Add timeout to wait and handle deleted linked authority

---

mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/holdings.feature
mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/users-negative-scenarios.feature
mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/users-positive-scenarios.feature

[FAT-9629](https://issues.folio.org/browse/FAT-9629) - Karate test fail: [firebird/mod-bulk-operations] ModBulkOperationsApiTest

 FAT-9629 - update pauses

---

mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/setup/samples/setup-records/holdings.json
mod-search/src/test/resources/samples/test-data/holdings.json

Previously, during setup.feature in mod-quick-marc on the "Create MARC-HOLDINGS record" scenario tests failed due to the features introduced in the MODINVSTOR-1094. Also, the similar situation appeared in the create-test-data.feature in mod-search on the "Create inventory holdings" scenario. This commit solves these errors by deleting holdingsItems and bareHoldingsItems fields.
- Remove holdingsItems and bareHoldingsItems fields from the holdings.json file in mod-quick-marc and mod-search modules.
Closes FAT-9832

fix(holdings-items): remove holdingsItems field

---

mod-kb-ebsco-java/src/main/resources/karate-config.js
mod-kb-ebsco-java/src/main/resources/spitfire/mod-kb-ebsco-java/features/providers.feature

Fix Karate test fail
Changed the 'selected' filter to 'true' instead of false because there are no records with selected=false.
https://issues.folio.org/browse/FAT-9722

fix(mod-kb-ebsco-java): change selected filter to true

---

edge-fqm/src/main/resources/karate-config.js
mod-fqm-manager/src/main/resources/karate-config.js
mod-lists/src/main/resources/karate-config.js

This adds the corsair rancher environment as a preset option for mod-fqm-manager, mod-lists, and edge-fqm.
It can be used with something like:
```sh
mvn test -DargLine="-Dkarate.env=rancher" -pl common,testrail-integration,mod-lists
```

Add corsair rancher env

---

edge-fqm/src/main/resources/karate-config.js
mod-search/src/test/resources/samples/test-data/authorities/sourceFiles/AuthoritySourceFIle.json
mod-search/src/test/resources/samples/test-data/authorities/sourceFiles/AuthoritySourceFIleSecond.json
mod-search/src/test/resources/samples/test-data/authorities/sourceFiles/AuthoritySourceFIleThird.json

_Fix steps for creating Authority Source Files from initialization step in mod-search module._
_In order to fix failing steps to create authority source files apply latest changes to authority source file POST DTO_
[FAT-9771](https://issues.folio.org/browse/FAT-9647)
Test Run results:

FAT-9771: Apply changes to authority source file POST DTO

---

mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/setup/samples/setup-records/authority-source-file.json

Previously, during setup.feature in mod-quick-marc on the "Create Authority Source File" scenario tests failed due to incorrect form of the authority-source-file.json Also, consequently "Create MARC-AUTHORITY records" and "Create Instance-Authority links" scenarios failed. This commit solves these errors by refactoring authority-source-file.json.
- Remove **codes** array.
- Add **code**, **selectable** fields.
- Add **hridManagement** object.
Closes FAT-9755

fix(authority-source-file): refactor authority-source-file.

---

acquisitions/src/main/resources/thunderjet/mod-orders/features/unreceive-piece-and-check-order-line.feature
acquisitions/src/main/resources/thunderjet/mod-orders/orders.feature
acquisitions/src/main/resources/thunderjet/mod-orders/reusable/create-order-line.feature
acquisitions/src/test/java/org/folio/OrdersApiTest.java

[MODORDERS-984](https://issues.folio.org/browse/MODORDERS-984) - Receipt status remains "Fully received" after unreceiving piece
Added a test unreceiving pieces and checking the receipt status in the po line afterwards.
[mod-orders PR](https://github.com/folio-org/mod-orders/pull/814)

[MODORDERS-984] Test po line update after unreceiving a piece

---

mod-bulk-operations/src/main/resources/firebird/mod-bulk-operations/features/holdings.feature

https://issues.folio.org/browse/FAT-9973
mod bulk operations holdings feature Karate tests failure
removing of unsupported elements:
holding.holdingsItems
holding.bareHoldingsItems

FAT-9973: Karate test fail. mod bulk operations holdings features

---

mod-fqm-manager/src/main/resources/corsair/mod-fqm-manager/features/query.feature
mod-fqm-manager/src/main/resources/corsair/mod-fqm-manager/features/util/add-query-data.feature

[MODFQMMGR-119](https://issues.folio.org/browse/MODFQMMGR-119): Add tests for $empty FQL Operator

MODFQMMGR-119: Add tests for empty FQL Operator

---

common/src/main/resources/common/login.feature

Header name in mod-authtoken: https://github.com/folio-org/mod-authtoken/blob/c11c02504f3168f08266178e73ff25978da933be/src/main/java/org/folio/auth/authtokenmodule/MainVerticle.java#L23
How it uses: https://github.com/folio-org/mod-authtoken/blob/master/src/main/java/org/folio/auth/authtokenmodule/apis/FilterApi.java#L260

Add Authtoken-Refresh-Cache = true to invildate permissions cache during login

---

acquisitions/src/main/resources/thunderjet/mod-orders/features/reopen-order-with-50-lines.feature
mod-consortia/src/main/resources/thunderjet/mod-consortia/features/util/tenant-and-local-admin-setup.feature

Time to live of accessToken is 10 min, initial setup of 3 tenants with all modules requires more than 10 min that causes InvlaidTokenException
Solution: make relogin after each particular tenant setup

Stabilize Thunderjet consortia tests

---

data-import/src/main/resources/folijet/data-import/features/data-import-multiple-records-from-marc-bib.feature

fix flaky results in test
Order of objects in HTTP response can differ, asserting the presence of values a different way

order of response could differ causing flaky results

---

acquisitions/src/main/resources/thunderjet/mod-orders/features/open-order-failure-with-expenditure-restrictions.feature
acquisitions/src/main/resources/thunderjet/mod-orders/orders.feature
acquisitions/src/main/resources/thunderjet/mod-orders/reusable/create-order-line.feature
acquisitions/src/test/java/org/folio/OrdersApiTest.java

[MODORDERS-1049](https://folio-org.atlassian.net/browse/MODORDERS-1049) - 500 error appears when trying to open order more than one time
New test to open an order beyond restricted expenditures. Checks that inventory is not modified after failure and tries to open the order again after changing the amount.
Before [MODORDERS-1050](https://folio-org.atlassian.net/browse/MODORDERS-1050) is implemented this will check that the inventory rollback works when an unexpected error occurs while creating encumbrances.
[PR in mod-orders](https://github.com/folio-org/mod-orders/pull/847): Rollback inventory if open fails to create encumbrances

[MODORDERS-1049] New test opening an order beyond restricted expenditures

---

acquisitions/src/main/resources/thunderjet/mod-orders/features/open-order-success-with-expenditure-restrictions.feature
acquisitions/src/main/resources/thunderjet/mod-orders/orders.feature
acquisitions/src/test/java/org/folio/OrdersApiTest.java

[MODFISTO-472](https://folio-org.atlassian.net/browse/MODFISTO-472) - Change restricted expenditures calculations
Reversed a previous test to make sure restricted expenditures do not prevent opening an order.
[Related mod-finance-storage PR](https://github.com/folio-org/mod-finance-storage/pull/394)

[MODFISTO-472] Reversed test with restricted expenditures when opening an order

---

acquisitions/src/main/resources/thunderjet/mod-gobi/features/gobi-api-tests.feature

[MOGDOBI-206: Fix endpoint to load custom mappings](https://folio-org.atlassian.net/browse/MODGOBI-206)
Added tests to verify gobi integration:
* Make sure fetching all mappings return custom ones
* Modify the existing test due to the changes to the default mapping

[MODBOGI-206] Fix endpoint to load custom mappings

---

acquisitions/src/main/resources/thunderjet/cross-modules/cross-modules.feature
acquisitions/src/main/resources/thunderjet/cross-modules/features/pending-payment-update-after-encumbrance-deletion.feature
acquisitions/src/test/java/org/folio/CrossModulesApiTest.java

[MODORDERS-1043](https://folio-org.atlassian.net/browse/MODORDERS-1043) - Remove pending payment encumbrance links when encumbrances are deleted
New test to check behavior when removing encumbrances linked to pending payments.
See also: [mod-finance PR](https://github.com/folio-org/mod-finance/pull/238), [mod-orders PR](https://github.com/folio-org/mod-orders/pull/853).

[MODORDERS-1043] Pending payment update after encumbrance deletion

---

acquisitions/src/main/resources/thunderjet/cross-modules/features/check-encumbrances-after-order-is-reopened.feature

[MODORDERS-1055](https://folio-org.atlassian.net/browse/MODORDERS-1055) - orderStatus is not always updated when reopening an order
Updated existing test. The 2 encumbrances in the test are now released because the invoice is not approved, which means some additional changes were needed for the test to pass (especially with the encumbrance restrictions).
A separate test (`check-encumbrances-after-order-is-reopened-2`) already checks an encumbrance is not unreleased when an order with an approved invoice is reopened.
[Related mod-orders PR](https://github.com/folio-org/mod-orders/pull/859)

[MODORDERS-1055] Updated test to check encumbrances after reopening an order

---

acquisitions/src/main/resources/thunderjet/cross-modules/cross-modules-junit.feature
acquisitions/src/main/resources/thunderjet/cross-modules/cross-modules.feature
acquisitions/src/main/resources/thunderjet/cross-modules/features/pay-invoice-without-order-acq-unit-permission.feature
acquisitions/src/main/resources/thunderjet/mod-orders/reusable/create-order.feature
acquisitions/src/test/java/org/folio/CrossModulesApiTest.java

[MODINVOICE-516](https://folio-org.atlassian.net/browse/MODINVOICE-516) - Invoice transactions should not be changed when acquisition check was failed
Added a new test with the MODINVOICE-516 scenario.
[Related mod-orders PR](https://github.com/folio-org/mod-orders/pull/871)
[Related mod-invoice PR](https://github.com/folio-org/mod-invoice/pull/479)

[MODINVOICE-516] Pay invoice without order acq unit perm

---

acquisitions/src/main/resources/thunderjet/cross-modules/cross-modules.feature
acquisitions/src/main/resources/thunderjet/cross-modules/features/check-paymentstatus-after-reopen.feature
acquisitions/src/test/java/org/folio/CrossModulesApiTest.java

[MODORDERS-1071](https://folio-org.atlassian.net/browse/MODORDERS-1071) - PaymentStatus can be wrong after reopening an order
Added a new test: open an order, approve the invoice, close the order, reopen the order, check line paymentStatus.
[mod-orders PR](https://github.com/folio-org/mod-orders/pull/872)

[MODORDERS-1071] Check paymentStatus after reopen

---

acquisitions/src/main/resources/thunderjet/cross-modules/cross-modules.feature
acquisitions/src/main/resources/thunderjet/cross-modules/features/invoice-encumbrance-update-without-acquisition-unit.feature
acquisitions/src/main/resources/thunderjet/mod-invoice/reusable/create-invoice.feature
acquisitions/src/test/java/org/folio/CrossModulesApiTest.java

[MODORDERS-1073](https://folio-org.atlassian.net/browse/MODORDERS-1073) - Invoice encumbrance link not removed because of acquisition unit
New test matching MODORDERS-1073 case.
[mod-invoice PR](https://github.com/folio-org/mod-invoice/pull/481) - [mod-orders PR](https://github.com/folio-org/mod-orders/pull/873)

[MODORDERS-1073] Invoice encumbrance update without acquisition unit

---

acquisitions/src/main/resources/thunderjet/mod-orders/features/MODORDERS-538-piece-against-non-package-mixed-pol-manual-piece-creation-is-true.feature
acquisitions/src/main/resources/thunderjet/mod-orders/features/pe-mix-update-piece.feature
acquisitions/src/main/resources/thunderjet/mod-orders/orders.feature
acquisitions/src/test/java/org/folio/OrdersApiTest.java

[MODORDERS-1079](https://folio-org.atlassian.net/browse/MODORDERS-1079) - Could not edit holdings for piece created from P/E mix Po Line
- New test matching the ticket case
- Fixed another test to match the new logic
[mod-orders PR](https://github.com/folio-org/mod-orders/pull/882)

[MODORDERS-1079] P/E mix update piece

---

mod-fqm-manager/pom.xml
mod-fqm-manager/src/main/resources/corsair/mod-fqm-manager/features/query.feature
mod-fqm-manager/src/main/resources/karate-config.js
mod-fqm-manager/src/test/java/org/folio/QuerySimulation.scala
pom.xml

This PR adds karate-gatling to mod-fqm-manager, based on the work done for the acquisitions module. It sets the shared submodule dependency versions in the parent POM's `dependencyManagemenet` section, so that consuming modules don't need to set a version in their `dependencies`; the version is set to `${project.version}`, so that we're always using the version that matches the root project's POM.

MODFQMMGR-223 Add gatling to the mod-fqm-manager tests

---

mod-audit/pom.xml
mod-audit/src/main/resources/karate-config.js
mod-audit/src/test/java/org/folio/AuditSimulation.scala

Adding Gatling plugin for mod-audit module. Simulated scenarios for check-in/check-out by barcode API and monitor the API's around it.
Taken reference to Olamide's PR - https://github.com/folio-org/folio-integration-tests/pull/1300/files
Need to do full successful run for this new code change locally but its not passing. I have created a draft PR
Gatling report screen shots --

[FAT-12625] - Adding Gatling to mod-audit module.

---

acquisitions/src/main/resources/thunderjet/mod-orders/features/poline-claiming-interval-checks.feature

https://folio-org.atlassian.net/browse/MODORDSTOR-395

MODORDSTOR-395. Metadata for Create Title is not populated

---

acquisitions/src/main/resources/thunderjet/mod-finance/reusable/createRestrictedFund.feature
acquisitions/src/main/resources/thunderjet/mod-orders/features/open-order-with-restricted-locations.feature

Fix existing test for story https://folio-org.atlassian.net/browse/MODORDERS-1046
- Fix json syntax
- Fix assertion match failed: EQUALS
$ | not equal (STRING:STRING)
'[testtenant7901948301395903209.b32c5ce2-6738-42db-a291-2796b1c3c4c6]'
'[b32c5ce2-6738-42db-a291-2796b1c3c4c6]'

MODORDERS-1046. Retrieve holdings from member tenants for Restrict by Locations feature

---

acquisitions/src/main/resources/thunderjet/cross-modules/features/delete-encumbrance.feature
acquisitions/src/main/resources/thunderjet/mod-finance/features/budget-can-be-deleted-if-have-only-allocation-transactions-From-or-To.feature
acquisitions/src/main/resources/thunderjet/mod-finance/features/budget-can-not-be-deleted-if-have-other-than-allocation-transactions.feature
acquisitions/src/main/resources/thunderjet/mod-finance/features/budget-can-not-be-deleted-if-have-to-and-from-fund-in-allocation-transactions.feature
acquisitions/src/main/resources/thunderjet/mod-finance/features/budget-transfer-transactions.feature
acquisitions/src/main/resources/thunderjet/mod-finance/features/group-and-ledger-transfers-after-rollover.feature
acquisitions/src/main/resources/thunderjet/mod-finance/features/group-fiscal-year-totals.feature
acquisitions/src/main/resources/thunderjet/mod-finance/features/ledger-fiscal-year-preview-rollover.feature
acquisitions/src/main/resources/thunderjet/mod-finance/features/ledger-fiscal-year-rollover-pol-and-system-currencies-are-different.feature
acquisitions/src/main/resources/thunderjet/mod-finance/features/ledger-fiscal-year-rollover.feature
acquisitions/src/main/resources/thunderjet/mod-finance/features/ledger-fiscal-year-sequential-rollovers.feature
acquisitions/src/main/resources/thunderjet/mod-finance/features/ledger-totals.feature
acquisitions/src/main/resources/thunderjet/mod-orders/features/reopen-order-creates-encumbrances.feature

[MODFIN-352](https://folio-org.atlassian.net/browse/MODFIN-352) - Remove the old transaction API
Fixed the tests to remove the old transaction API in mod-finance.
[Related mod-finance PR](https://github.com/folio-org/mod-finance/pull/245)
[Related mod-finance-storage PR](https://github.com/folio-org/mod-finance-storage/pull/407)

[MODFIN-352] Fixed tests to remove old transaction API

---

mod-data-export/src/test/resources/firebird/dataexport/data-export-basic-junit.feature

[FAT-14264](https://folio-org.atlassian.net/browse/FAT-14264) test fail: [firebird/data-export] ModDataExportApiTest {13}  firebird/dataexport/features/export-deleted-marc-ids.feature
Added missing permission for user.

FAT-14264 - Karate test fail: [firebird/data-export] ModDataExportApiTest {13}  firebird/dataexport/features/export-deleted-marc-ids.feature

---

acquisitions/src/main/resources/thunderjet/mod-finance/features/budgets-totals-calculation.feature
acquisitions/src/main/resources/thunderjet/mod-finance/features/fiscal-year-totals.feature

[MODFISTO-484](https://folio-org.atlassian.net/browse/MODFISTO-484) - Wrong budget overEncumbrance calculation
- Fixed existing overEncumbrance expected values
- Added some cases that were previously failing
[mod-finance-storage PR](https://github.com/folio-org/mod-finance-storage/pull/415)

[MODFISTO-484] Fixed overEncumbrance checks

---

acquisitions/src/main/resources/thunderjet/cross-modules/features/cancel-invoice-linked-to-order.feature
acquisitions/src/main/resources/thunderjet/cross-modules/features/create-order-and-invoice-with-odd-penny.feature
acquisitions/src/main/resources/thunderjet/mod-finance/features/batch-transaction-api.feature
acquisitions/src/main/resources/thunderjet/mod-finance/features/budget-expense-classes.feature
acquisitions/src/main/resources/thunderjet/mod-finance/features/fiscal-year-totals.feature
acquisitions/src/main/resources/thunderjet/mod-finance/features/group-expense-classes.feature
acquisitions/src/main/resources/thunderjet/mod-finance/features/ledger-totals.feature
acquisitions/src/main/resources/thunderjet/mod-invoice/features/cancel-invoice.feature
acquisitions/src/main/resources/thunderjet/mod-invoice/features/exchange-rate-update-after-invoice-approval.feature
acquisitions/src/main/resources/thunderjet/mod-orders/features/check_total_encumbered_expended_calculated_correctly.feature
acquisitions/src/test/java/org/folio/CrossModulesApiTest.java
acquisitions/src/test/java/org/folio/InvoicesApiTest.java

[FAT-13846](https://folio-org.atlassian.net/browse/FAT-13846) - Update tests to separate credits from expenditures
- Updated amounts and totals wherever credits are used (otherwise the tests are still valid)
- Added some test cases with credits to check totals
- I did not check if the tests pass because the implementation is not complete. So there might be something to fix afterwards, but for now it can be used as a target to achieve with the implementation.

[FAT-13846] Updated tests to separate credits from expenditures

---

mod-inventory/src/main/resources/folijet/mod-inventory/features/consortia/features/update-ownership.feature

Verify holdings and items has new ids during update-ownership
Verify holdings and items has new ids during update-ownership

[MODINV-1053] Verify holdings and items has new ids during update-ownership

---

mod-inventory/src/main/resources/folijet/mod-inventory/features/consortia/features/update-ownership.feature
mod-inventory/src/main/resources/folijet/mod-inventory/features/inventoryFeatureTest.feature
mod-inventory/src/main/resources/folijet/mod-inventory/inventory-junit.feature

Add tests for update-ownership failure scenarios
Add tests for next scenarios:
- Disallow update ownership of holdings with linked boundwith items
- Disallow update ownership of boundwith items
- Handle update holding ownership request with invalid instance id
- Handle update item ownership request with invalid holdingsRecord id
- Handle update holding ownership request with not shared instance
- Handle update item ownership request with holdingsRecord related to not shared instance
- Handle update holding ownership request for non-consortium environment
- Handle update item ownership request for non-consortium environment

[FAT-14579] Add tests for update-ownership failure scenarios

---

edge-rtac/src/main/resources/core_platform/edge-rtac/features/rtac.feature
edge-rtac/src/main/resources/core_platform/edge-rtac/features/samples/holdings/holdings-entity-request.json
edge-rtac/src/main/resources/core_platform/edge-rtac/features/samples/source-record-entity-request.json
edge-rtac/src/main/resources/core_platform/edge-rtac/features/util/initData.feature

[ticket](https://folio-org.atlassian.net/browse/FAT-14366)
Fix edge-rtac scenarios because holding source id missing. 
- Add holding sources

Fix failing tests with sourceId

---

mod-consortia/src/main/resources/thunderjet/mod-consortia/consortia-junit.feature

Update required module list to fix this exception:
```log
10:36:53.575 [main] DEBUG com.intuit.karate - response time in milliseconds: 20358
1 < 500
1 < Content-Type: text/plain
Tenant operation failed for module mod-circulation-storage-17.3.0-SNAPSHOT.411: org.folio.util.pubsub.exceptions.ModuleRegistrationException: EventDescriptor was not registered for eventType: LOG_RECORD . Status code: 404
```
- Add `mod-pubsub` to the list of required modules

[MODCON-FIX-1]. Update required modules list to fix mod-circulation exception

---

mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/quick-marc-linking-records.feature
mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/setup/samples/setup-records/holdings.json
mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/setup/setup.feature
mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/quick-marc-junit.feature

Fix Karate test fail: quick-marc-linking-records
Update linking authority delete endpoint
https://folio-org.atlassian.net/browse/FAT-14613

fix(mod-quick-marc) fix quick-marc-linking-records feature

---

acquisitions/src/main/resources/thunderjet/mod-orders/reusable/create-order-line.feature

- Add missing arg comments on create-order-line reusable (for better long-term maintenance)
- Update a comment

[FAT-13426-2]. Add missing arg comments on create-order-line reusable

---

mod-inventory/src/main/resources/folijet/mod-inventory/features/inventoryFeatureTest.feature

Add targetLocationId field to update ownership test for non-consortium
Add targetLocationId field to update ownership test for non-consortium

[FAT-15956] Add targetLocationId field to update ownership test for non-consortium

---

acquisitions/src/main/resources/thunderjet/mod-orders/features/open-and-unopen-order.feature
acquisitions/src/test/java/org/folio/OrdersApiTest.java

- <https://folio-org.atlassian.net/browse/MODORDERS-1167>
- Add 2 test cases for One-Time and Ongoing order types verifying that both Payment and Receipt statuses revert to Pending after unopening

[MODORDERS-1167]. POL statuses remain "Ongoing" after unopen ongoing order

---

mod-inventory/src/main/resources/folijet/mod-inventory/features/inventoryFeatureTest.feature
mod-inventory/src/main/resources/folijet/mod-inventory/samples/record.json

Karate test fail: [folijet/mod-inventory] ModInventoryTests {2}  folijet/mod-inventory/features/inventoryFeatureTest.feature
Add hrId to MARC_BIB record creation
[FAT-16096](https://folio-org.atlassian.net/browse/FAT-16096)

FAT-16096 Add hrId to MARC_BIB record creation

---

mod-data-export/src/test/resources/samples/marc_bib_record.json
mod-data-export/src/test/resources/samples/marc_bib_record_deleted.json
mod-oai-pmh/src/test/resources/samples/marc_record.json

FAT-16090, FAT-16091, FAT-16093, FAT-16097, FAT-16098, FAT-16099 - Firebird regression (MODSOURMAN-1203)
[FAT-16090](https://folio-org.atlassian.net/browse/FAT-16090)
[FAT-16091](https://folio-org.atlassian.net/browse/FAT-16091)
[FAT-16093](https://folio-org.atlassian.net/browse/FAT-16093)
[FAT-16097](https://folio-org.atlassian.net/browse/FAT-16097)
[FAT-16098](https://folio-org.atlassian.net/browse/FAT-16098)
[FAT-16099](https://folio-org.atlassian.net/browse/FAT-16099)
To fix issue creating SRS record without required field externalIdsHolder.instanceHrid.
Adding value externalIdsHolder.instanceHrid in samples.

FAT-16090, FAT-16091, FAT-16093, FAT-16097, FAT-16098, FAT-16099 - Firebird regression (MODSOURMAN-1203)

---

mod-source-record-storage/src/main/resources/folijet/mod-source-record-storage/features/get-source-storage-records.feature
mod-source-record-storage/src/main/resources/folijet/mod-source-record-storage/features/samples/record.json
mod-source-record-storage/src/main/resources/folijet/mod-source-record-storage/features/samples/recordWith999field.json

Karate test fail: [folijet/mod-source-record-storage] ModSourceRecordStorageTest {2}  folijet/mod-source-record-storage/features/get-source-storage-records.feature
Add hrId to MARC_BIB record creation
[FAT-16101](https://folio-org.atlassian.net/browse/FAT-16101)

FAT-16101 Add instanceHrid to MARC_BIB record creation

---

acquisitions/src/main/resources/thunderjet/consortia/consortia-orders-junit.feature
acquisitions/src/main/resources/thunderjet/consortia/features/bind-pieces-ecs.feature
acquisitions/src/main/resources/thunderjet/consortia/variables/variablesCentral.feature
acquisitions/src/main/resources/thunderjet/mod-orders/features/bind-piece.feature
acquisitions/src/main/resources/thunderjet/mod-orders/reusable/create-circulation-policy.feature
acquisitions/src/main/resources/thunderjet/mod-orders/reusable/create-circulation-request.feature
acquisitions/src/main/resources/thunderjet/mod-orders/reusable/create-piece-with-holding.feature
acquisitions/src/main/resources/thunderjet/mod-orders/reusable/receive-piece-with-holding.feature
acquisitions/src/main/resources/thunderjet/mod-orders/reusable/user-init-data.feature
common/src/main/resources/common/resource-exists.feature

[[FAT-16037] Extend Karate coverage for Bind pieces in ECS mode
](https://folio-org.atlassian.net/browse/FAT-16037)
- Modify existing bind pieces tests to accept tenants and holdings as parameters
- Run bind pieces tests with ECS params
- Modify existing reusable functions with additional attributes
Tests that were affected by the changes

[FAT-16037] Extend Karate coverage for Bind pieces in ECS mode

---

mod-fqm-manager/src/main/resources/corsair/mod-fqm-manager/features/query.feature

`mod-fqm-manager` used to only include non_empty properties during Jackson serialization, however, [this was changed as part of MODFQMMGR-442](https://github.com/folio-org/mod-fqm-manager/commit/f4b54b090b90f910e506fa8421e711f5dfdd4bbd#diff-7bc26be01d3e7c9c566f2a28dc1b5cd87dbdd5cb619184f46eb2bf223bf7825d). This test must be updated to expect this change.

[FAT-16046] Check for null instead of non-present

---

acquisitions/src/main/resources/samples/consortia/orderLines/multi-tenant-order-line.json
acquisitions/src/main/resources/thunderjet/consortia/consortia-orders-junit.feature
acquisitions/src/main/resources/thunderjet/consortia/features/open-order-with-locations-from-different-tenants.feature
acquisitions/src/main/resources/thunderjet/consortia/features/pieces-api-test-for-cross-tenant-envs.feature
acquisitions/src/main/resources/thunderjet/consortia/features/reopen-and-change-instance-connection-order-with-locations-from-different-tenants.feature
mod-consortia/src/main/resources/thunderjet/mod-consortia/consortia-junit.feature

https://folio-org.atlassian.net/browse/FAT-16038
- Do unopen the order, check appropriate state of Inventory 
-  Inherit Change instance connection test when order has related items from different 
- Change affiliation in Piece and check that item and holding was re-created in correct 
- Open 1 order with Create Instance, Hodling, Item, and another with Create Instance, Holding. In both cases pieces should have receivingTenantId populated

[FAT- 16038] - Extend Central Ordering Karate tests coverage

---

mod-inventory/src/main/resources/folijet/mod-inventory/features/consortia/features/update-ownership.feature

[MODINV-1074](https://folio-org.atlassian.net/browse/MODINV-1074) Keep original UUIDs when updating ownership of Holdings/Items
fix karate test

MODINV-1074 Keep original UUIDs when updating ownership of Holdings/Items

---

mod-dcb/src/main/resources/karate-config.js
mod-dcb/src/main/resources/volaris/mod-dcb/mod-dcb-junit.feature

when enabling modules for a tenant in the karate env "dev", module dependencies are not pulled in.

Enable the ability to run tests without dependency checking

---

teams-assignment.json

Jira Development team was renamed, that breaks CI CD Pipeline

[URGENT] [BLOCKER] Align Core Platform team name in configuration

---

acquisitions/src/main/resources/karate-config.js
acquisitions/src/main/resources/thunderjet/mod-orders/features/update-purchase-order-with-order-lines.feature
acquisitions/src/main/resources/thunderjet/mod-orders/features/update-purchase-order-workflow-status.feature
acquisitions/src/main/resources/thunderjet/mod-orders/reusable/update-order-line.feature
acquisitions/src/main/resources/thunderjet/mod-orders/reusable/update-order.feature
acquisitions/src/main/resources/thunderjet/mod-orders/reusable/validate-composite-orders.feature
acquisitions/src/test/java/org/folio/OrdersApiTest.java

- <https://folio-org.atlassian.net/browse/MODORDERS-369>
- Add order update tests to verify that changing order workflow status can be done from the API, i.e. no async processing is involved or prevents this action from succeeding
- Add order line update tests which verify that changing order line statuses from the API can affect order workflow status via async processing (Vert.X EventBus)

[MODORDERS-369]. Allow manual setting of workflowStatus via composite_orders API

---

acquisitions/src/main/resources/thunderjet/consortia/consortia-orders-junit.feature
acquisitions/src/main/resources/thunderjet/consortia/features/pieces-api-test-for-cross-tenant-envs.feature
acquisitions/src/main/resources/thunderjet/consortia/tenant-utils/consortium.feature

[[MODORDERS-1174] Filter pieces based on user affiliations](https://folio-org.atlassian.net/browse/MODORDERS-1174)
- Update tests to enable central ordering and filter pieces correctly

[MODORDERS-1174] Use CQL query to filter pieces based on user affiliations

---

mod-sender/src/main/resources/vega/mod-sender/sender-junit.feature

https://folio-org.atlassian.net/browse/FAT-16870
Update the mod-sender permission as part of https://folio-org.atlassian.net/browse/MODSENDER-69
Merge at the same time as https://github.com/folio-org/mod-sender/pull/59

FAT-16870 - MODSENDER-69 - Update the permission name.

---

acquisitions/src/main/resources/thunderjet/mod-invoice/features/check-invoice-lines-with-vat-adjustments.feature
acquisitions/src/main/resources/thunderjet/mod-invoice/reusable/create-invoice-line.feature
acquisitions/src/main/resources/thunderjet/mod-invoice/reusable/create-invoice.feature
acquisitions/src/test/java/org/folio/InvoicesApiTest.java

- <https://folio-org.atlassian.net/browse/MODINVOICE-554>
- Add supplementary Karate tests covering new custom method for VAT adjustment calculation
- Tested against current invoice, finance and cross-modules tests for breaking changes

[MODINVOICE-554]. Invoices app: Incorrect formula for calculating adjustments, that are included and pro-rated by amount

---

mod-search/src/test/resources/spitfire/mod-search/set-up/tenant-init.feature

[FAT-16833](https://folio-org.atlassian.net/browse/FAT-16833)
Update the permissions in the Karate tests, as the permissions for mod-inventory-storage  have been changed
update the feature file with the new permission for the mod-inventory-storage endpoint:
| Method  | Endpoint | Permission|
| ------------- | ------------- | ------------- |
| POST  | /instance-storage/batch/synchronous | inventory-storage.instances.batch.synchronous.post|

FAT-16833: Update permission for "POST:/instance-storage/batch/synchronous" endpoint.

---

acquisitions/src/main/resources/thunderjet/mod-finance/reusable/createBudget.feature
acquisitions/src/main/resources/thunderjet/mod-orders/features/check-order-total-fields-calculated-correctly.feature
acquisitions/src/test/java/org/folio/OrdersApiTest.java

[[MODORDERS-1191] Apply restriction to edit Locations based on user affiliations](https://folio-org.atlassian.net/browse/MODORDERS-1191)
- Use related invoice totals to calculate total expanded and credited values and use transactions to calculate total encumbered.

[MODORDERS-1191] Update total expended amount calculation for Purchase order

---

acquisitions/src/main/resources/thunderjet/mod-orders/features/check-order-total-fields-calculated-correctly.feature

[MODORDERS-1203] Total expended amount is not displayed when order has no fund distributions
- Add new scenario to check calculated totals without POL fund distribution
Unrelated fail for only 1 testcase

[MODORDERS-1203] Total expended amount is not displayed when order has no fund distributions

---

mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/quick-marc-authority-records.feature

mod-quick-marc: remove calls to removed endpoints

FAT-17335 mod-quick-marc: remove calls to removed endpoints

---

acquisitions/src/main/resources/thunderjet/mod-invoice/features/audit-event-invoice-line.feature
acquisitions/src/main/resources/thunderjet/mod-invoice/features/audit-event-invoice.feature

[[MODINVOSTO-187] Implement audit outbox pattern for sending kafka events about invoice updates](https://folio-org.atlassian.net/browse/MODINVOSTO-187)
[[MODINVOSTO-188] Implement audit outbox pattern for sending kafka events about invoice line updates](https://folio-org.atlassian.net/browse/MODINVOSTO-188)
- Increase time interval to let audit consumer process events
https://folio-org.atlassian.net/browse/FAT-17421
https://folio-org.atlassian.net/browse/FAT-17422

[MODINVOSTO-187] Increase retry intervals for audit event testing

---

acquisitions/src/test/java/org/folio/InvoicesApiTest.java

[[MODINVOSTO-187] Implement audit outbox pattern for sending kafka events about invoice updates](https://folio-org.atlassian.net/browse/MODINVOSTO-187)
[[MODINVOSTO-188] Implement audit outbox pattern for sending kafka events about invoice line updates](https://folio-org.atlassian.net/browse/MODINVOSTO-188)
- Disable tests temporarily

[MODINVOSTO-187] Disable invoice audit tests temporarily

---

mod-linked-data/src/main/resources/citation/mod-linked-data/create-ref-data.feature
mod-linked-data/src/main/resources/citation/mod-linked-data/features/create-bib-api/create-bib-api.feature
mod-linked-data/src/main/resources/citation/mod-linked-data/features/create-bib-api/create-resource.feature
mod-linked-data/src/main/resources/citation/mod-linked-data/features/suppress-flags/suppress-flags.feature
mod-linked-data/src/main/resources/karate-config.js
mod-linked-data/src/test/java/org/folio/CreateResourceSimulation.scala
mod-linked-data/src/test/java/org/folio/ModLinkedDataTest.java

Fix failing Gatling performance test of mod-linked-data
1. Updated the login process to use 'callonce,' ensuring no repeated login attempts occur during performance testing.
2. Previously, performance tests for mod-linked-data included calls to mod-inventory and mod-search, which was unnecessary. This update isolates the performance testing to focus only on mod-linked-data calls.

MODLD-596: mod-linked-data - Fix Gatling performance test

---

mod-inventory/src/main/resources/folijet/mod-inventory/features/consortia/consortia-inventory-junit.feature

Temporarily fix update ownership tests
add a timeout to wait until the cache reload

[FAT-17480] Add temporary handling of mod-inventory-storage install using consortium data cache

---

mod-batch-print/src/main/resources/odin/mod-batch-print/batch-print-junit.feature

Fix failing mod-batch-print test
There was permission updated for collection endpoint. Add missing permission to test so that test passes

FAT-16909 Add missing permission in batch-print-junit.feature

---

acquisitions/src/main/resources/karate-config.js
acquisitions/src/main/resources/thunderjet/mod-finance/reusable/createBudget.feature
acquisitions/src/main/resources/thunderjet/mod-orders/features/pieces-batch-update-status.feature
acquisitions/src/main/resources/thunderjet/mod-orders/orders.feature
acquisitions/src/main/resources/thunderjet/mod-orders/reusable/update-pieces-batch-status.feature
acquisitions/src/test/java/org/folio/OrdersApiTest.java

[[MODORDERS-1210] Implement API to change piece statuses in batch](https://folio-org.atlassian.net/browse/MODORDERS-1210)
Add new feature to cover the new piece batch status update API endpoint
Bind pieces failing as mod-settings is missing, when enabled then busybee is unable to start all modules locally for me

[MODORDERS-1210] Implement API to change piece statuses in batch

---

acquisitions/src/main/resources/thunderjet/mod-orders/features/open-orders-with-poLines.feature
acquisitions/src/main/resources/thunderjet/mod-orders/orders.feature
acquisitions/src/test/java/org/folio/OrdersApiTest.java

- <https://folio-org.atlassian.net/browse/MODORDERS-1226>
- Add supplementary tests
- Test output for `mod-orders` and `cross-modules` folders:

[MODORDERS-1226]. Update validation to prevent opening an order without po lines

---

mod-entities-links/src/main/resources/spitfire/mod-entities-links/features/get-authorities-with-filtering.feature

Fix unstable authority deletion scenario
Add retry on GET request after authority deletion
[FAT-17996](https://folio-org.atlassian.net/browse/FAT-17996)

feat(entities-links): Fix unstable authority deletion scenario

---

acquisitions/src/main/resources/karate-config.js
acquisitions/src/main/resources/thunderjet/cross-modules/features/rollover-with-pending-order.feature
acquisitions/src/main/resources/thunderjet/mod-finance/reusable/backdateFY.feature
acquisitions/src/main/resources/thunderjet/mod-finance/reusable/rollover.feature
acquisitions/src/test/java/org/folio/CrossModulesApiTest.java

[MODORDERS-1217](https://folio-org.atlassian.net/browse/MODORDERS-1217): Ongoing orders cannot be reopened with inactive budget for fund
Added a test of a FYRO with a pending order with an encumbrance. The encumbrance link should be deleted, and it should be possible to open the pending order in the new fiscal year after FYRO.
[mod-orders PR](https://github.com/folio-org/mod-orders/pull/1082)

[MODORDERS-1217] FYRO with a pending order with an encumbrance

---

acquisitions/src/main/resources/thunderjet/mod-finance/features/finance-data.feature

[MODFIN-402](https://folio-org.atlassian.net/browse/MODFIN-402) - Update current budget value and display budget records in appropriate fiscal year in downloaded .csv allocations
- Ensures ids do not collide with other tests
- Fixed FY codes and series
- Added `budgetCurrentAllocation`
- Fixed the tests, taking into account that a ledger is not tied to a single fiscal year, and finance data may contain fund data without budget data
Related PRs: [mod-finance-storage](https://github.com/folio-org/mod-finance-storage/pull/448), [mod-finance](https://github.com/folio-org/mod-finance/pull/272)

[MODFIN-402] Fixes to finance data endpoint

---

acquisitions/src/main/resources/thunderjet/mod-finance/features/finance-data.feature

[MODFIN-407](https://folio-org.atlassian.net/browse/MODFIN-407) - Make fund active when creating or increasing allocation
- Made the tests more parallel (previously update log checks would fail in parallel, and other checks with funds and budgets could also fail randomly)
- Added checks for `fundStatus` automatic update
- TODO: More validation in mod-finance, especially for `budgetCurrentAllocation`, see [MODFIN-403](https://folio-org.atlassian.net/browse/MODFIN-403). Right now the integration test will fail because a 422 is expected and a 500 is returned.
[mod-finance-storage PR](https://github.com/folio-org/mod-finance-storage/pull/449), [mod-finance PR](https://github.com/folio-org/mod-finance/pull/273)

[MODFIN-407] Finance data test updates

---

acquisitions/src/main/resources/thunderjet/mod-finance/features/finance-data.feature

[MODFISTO-517](https://folio-org.atlassian.net/browse/MODFISTO-517) - Create budget when adding batch allocation to fund without budget
- Added new tests
- Fixed unrelated issue with error messages (related to first MODFIN-403 PR)
[mod-finance-storage PR](https://github.com/folio-org/mod-finance-storage/pull/450), [mod-finance PR](https://github.com/folio-org/mod-finance/pull/275)

[MODFISTO-517] Create budgets with batch allocations

---

acquisitions/src/main/resources/thunderjet/mod-orders/features/change-pending-distribution-with-inactive-budget.feature
acquisitions/src/main/resources/thunderjet/mod-orders/orders.feature
acquisitions/src/test/java/org/folio/OrdersApiTest.java

[MODORDERS-1253](https://folio-org.atlassian.net/browse/MODORDERS-1253) - User can edit fund distribution for unopened order with inactive budget in POL
Added a new test with the scenarios in MODORDERS-1253.
[mod-orders PR](https://github.com/folio-org/mod-orders/pull/1093)

[MODORDERS-1253] Change pending distribution with inactive budget

---

mod-fqm-manager/src/main/resources/corsair/mod-fqm-manager/fqm-junit.feature
mod-lists/src/main/resources/corsair/mod-lists/lists-junit.feature

Update corsair integration tests to include permission required to access new transaction entity type, introduced in [MODFQMMGR-685](https://folio-org.atlassian.net/browse/MODFQMMGR-685)

[MODFQMMGR-685] Add required permission for transaction entity type

---

acquisitions/src/main/resources/thunderjet/mod-finance/features/finance-data.feature

- <https://folio-org.atlassian.net/browse/MODFIN-416>
- Add `ledgerId` to finance data objects
- Test output with applied changes:

[MODFIN-416]. Batch allocation logs - restrict by acq units

---

acquisitions/src/main/resources/thunderjet/mod-finance/create-inactive-budget.feature
acquisitions/src/main/resources/thunderjet/mod-finance/finance.feature
acquisitions/src/main/resources/thunderjet/mod-finance/reusable/createBudget.feature
acquisitions/src/test/java/org/folio/FinanceApiTest.java

[MODFIN-405](https://folio-org.atlassian.net/browse/MODFIN-405) - Current budget is created with incorrect values ​​despite the received error
Three new tests:
- Create an inactive budget without any allocation
-  Create an inactive budget with an allocation
-  Try to create a budget with negative allowableEncumbrance or allowableExpenditure (expect a 422)
[mod-finance PR](https://github.com/folio-org/mod-finance/pull/284)

[MODFIN-405] Create inactive budget

---

acquisitions/src/main/resources/thunderjet/mod-finance/features/finance-data.feature
acquisitions/src/test/java/org/folio/FinanceApiTest.java

[[MODFIN-417] Finance-data integration tests should run in parallel](https://folio-org.atlassian.net/browse/MODFIN-417)
- Use custom fund tag to differentiate job ids after creating finance data
- Filter finance data logs by job id's determined by the tag
Tested the feature with 1, 2, 4, 8, 16 threads to run scenarios in parallel

[MODFIN-417] Finance-data integration tests should run in parallel

---

acquisitions/src/main/resources/karate-config.js
acquisitions/src/main/resources/thunderjet/mod-finance/features/allowable-encumbrance-and-expenditure-restrictions.feature
acquisitions/src/main/resources/thunderjet/mod-finance/features/batch-transaction-api.feature
acquisitions/src/main/resources/thunderjet/mod-finance/reusable/createBudget.feature
acquisitions/src/main/resources/thunderjet/mod-finance/reusable/createEncumbrance.feature
acquisitions/src/main/resources/thunderjet/mod-finance/reusable/createPayment.feature
acquisitions/src/main/resources/thunderjet/mod-finance/reusable/createPendingPayment.feature

[MODFISTO-515](https://folio-org.atlassian.net/browse/MODFISTO-515) - Support deleting pending payments with batch transaction API
- New tests for the batch API, to delete a pending payment
- Fixed and updated the tests to check the allowable encumbrance/expenditures (previously the test for expenditures was actually checking encumbrance; also it is more realistic to create a pending payment before creating a payment - this way the test will be less dependent on the implementation)
[mod-finance-storage PR](https://github.com/folio-org/mod-finance-storage/pull/465)

[MODFISTO-515] Delete a pending payment to revert creation

---

common/src/main/resources/common/eureka/setup-users.feature

changed entitlement creation flow to stop further requests when response status is cancelled or cancellation_failed or failed

Exit entitlement wait on error

---

mod-linked-data/src/main/resources/citation/mod-linked-data/features/import-bib/samples/expected-search-response.json

The response structure of `GET search/linked-data-works` API got updated for MSEARCH-989. Purpose of this PR is to update the integration tests accordingly.

FAT-19376 / MSEARCH-989: Use new fields in classification object

---

acquisitions/src/main/resources/thunderjet/cross-modules/features/approve-or-cancel-invoice-with-polinepaymentstatus-parameter.feature
acquisitions/src/main/resources/thunderjet/mod-invoice/reusable/approve-invoice.feature
acquisitions/src/main/resources/thunderjet/mod-invoice/reusable/cancel-invoice.feature
acquisitions/src/main/resources/thunderjet/mod-orders/features/check-order-total-fields-calculated-correctly.feature

[MODINVOICE-573](https://folio-org.atlassian.net/browse/MODINVOICE-573) - Updating order status when approving or cancelling an invoice against a previous fiscal year
This is an update to the [previous PR](https://github.com/folio-org/folio-integration-tests/pull/1730).
- Fix an existing test to use the new parameter
- Added the parameter to `approveInvoice` and `cancelInvoice` to simplify

[MODINVOICE-573] Fix an existing test to use the new parameter

---

mod-kb-ebsco-java/src/main/resources/karate-config.js
mod-kb-ebsco-java/src/main/resources/spitfire/mod-kb-ebsco-java/features/setup/setup-resources.feature

Fix agreement assinment violating unique name constraint
- Add random number to an agreement name in case agreement from previous test runs didn't get unassigned
[FAT-19329](https://folio-org.atlassian.net/browse/FAT-19329)

fix(mod-kb-ebsco-java): Fix agreement assignment violating unique name constraint

---

mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/quick-marc-linking-records.feature

Fix linking records feature record update issues
Add retries
[FAT-19289](https://folio-org.atlassian.net/browse/FAT-19289)

fix(mod-quick-marc): Fix linking records feature record update issues

---

mod-search/src/test/resources/spitfire/mod-search/search/single-property-search.feature

Fix search by metadata dates
Adjust dates to search by, adjust expected counts to match non null dates
Null metadata createdDate/updatedDate are now excluded from search so tests needed to be adjusted accordingly

fix(mod-search): Fix search by metadata dates

---

acquisitions/src/main/resources/thunderjet/mod-invoice/features/invoice-with-identical-adjustments.feature
acquisitions/src/main/resources/thunderjet/mod-invoice/invoice.feature
acquisitions/src/test/java/org/folio/InvoicesApiTest.java

[MODINVOICE-586](https://folio-org.atlassian.net/browse/MODINVOICE-586) - Error when cancelling a paid invoice with 2 invoice-level adjustments using the same fund and expense class
New test: Create, approve, pay and cancel an invoice with identical invoice-level adjustments
[mod-finance-storage PR](https://github.com/folio-org/mod-finance-storage/pull/471)

[MODINVOICE-586] Invoice with identical adjustments

---

edge-rtac/src/test/java/org/folio/EdgeRtacTests.java

This PR includes disabling tests for Dreamliner team

disable: Dreamliner team module due to migration to Eureka

---

mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/setup/setup.feature

[FAT-12649](https://folio-org.atlassian.net/browse/FAT-12649) fix retry for quickMARC Bib record creation scenario
The `retry` step must come before `method` and `status`
<kbd>
</kbd>

fix retry for quickMARC Bib record creation scenario

---

mod-circulation/src/main/resources/vega/mod-circulation/features/root.feature

Increasing token expiration time for Circulation Tests
Changing token expiration time in root.feature
` * call read('classpath:common/eureka/keycloak.feature@configureAccessTokenTime') { 'AccessTokenLifespance' : 3600 }`

Vega - Increasing token expiration time

---

acquisitions/src/main/resources/thunderjet/consortia/consortia-orders-junit.feature
acquisitions/src/main/resources/thunderjet/mod-data-export-spring/data-export-spring-junit.feature
acquisitions/src/main/resources/thunderjet/mod-finance/finance-junit.feature
acquisitions/src/main/resources/thunderjet/mod-invoice/invoice-junit.feature

Increasing token expiration time for Thunderjet Tests
Changing token expiration time in root.feature
` * call read('classpath:common/eureka/keycloak.feature@configureAccessTokenTime') { 'AccessTokenLifespance' : 3600 }`

 Increase token lifetime

---

acquisitions/src/main/resources/karate-config.js
acquisitions/src/main/resources/thunderjet/consortia/consortia-orders-junit.feature
acquisitions/src/main/resources/thunderjet/consortia/features/bind-pieces-ecs.feature
acquisitions/src/main/resources/thunderjet/consortia/features/mode-item-and-holding-to-update-order-data-ecs.feature
acquisitions/src/main/resources/thunderjet/consortia/features/open-order-with-locations-from-different-tenants.feature
acquisitions/src/main/resources/thunderjet/consortia/features/pieces-api-test-for-cross-tenant-envs.feature
acquisitions/src/main/resources/thunderjet/consortia/features/prf-open-order-with-many-locations-from-different-tenants.feature
acquisitions/src/main/resources/thunderjet/consortia/features/reopen-and-change-instance-connection-order-with-locations-from-different-tenants.feature
acquisitions/src/main/resources/thunderjet/consortia/features/update-inventory-ownership-changes-order-data.feature
acquisitions/src/main/resources/thunderjet/consortia/features/update-unaffiliated-pol-locations.feature
acquisitions/src/main/resources/thunderjet/consortia/order-utils/configuration.feature
acquisitions/src/main/resources/thunderjet/consortia/order-utils/finances.feature
acquisitions/src/main/resources/thunderjet/consortia/order-utils/inventory-university.feature
acquisitions/src/main/resources/thunderjet/consortia/order-utils/inventory.feature
acquisitions/src/main/resources/thunderjet/consortia/order-utils/orders.feature
acquisitions/src/main/resources/thunderjet/consortia/order-utils/organizations.feature
acquisitions/src/main/resources/thunderjet/consortia/variables/variablesCentral.feature
acquisitions/src/main/resources/thunderjet/mod-gobi/gobi-junit.feature
acquisitions/src/main/resources/thunderjet/mod-orders/features/bind-piece.feature
acquisitions/src/main/resources/thunderjet/mod-orders/reusable/user-init-data.feature

[MODORDERS-1272](https://folio-org.atlassian.net/browse/MODORDERS-1272) - Run ACQ Karate tests on Eureka platform
- Cleaned up consortia-orders-junit.feature to make it easier to read
- Fixed the headers for all requests in consortia tests (note that "`And header`" does not work when `configure` is used)
- Removed unused permissions
- Continue fixing tests for Eureka
- Look at non-junit features
- Someone else should look at the remaining errors in `open-order-with-locations-from-different-tenants` and `reopen-and-change-instance-connection-order-with-locations-from-different-tenants`, they are probably caused by errors in the consortia tests (as multiple errors were cancelling each other and the user/permissions were fixed)

[MODORDERS-1272] Fixed users and permissions for consortia tests

---

mod-dcb/src/main/resources/volaris/mod-dcb/features/borrowing-flow.feature
mod-dcb/src/main/resources/volaris/mod-dcb/features/pickup-flow.feature

Fix failing validation test cases for pickup and borrowing flows
- no request body is needed for `GET /material-types`
- use `query` param to fetch material-type by name
[FAT-19900](https://folio-org.atlassian.net/browse/FAT-19900)

FAT-19900: Fix GET /material-types query in validation test cases

---

acquisitions/src/main/resources/thunderjet/cross-modules/cross-modules.feature
acquisitions/src/main/resources/thunderjet/cross-modules/features/check-order-total-fields-calculated-correctly.feature
acquisitions/src/main/resources/thunderjet/mod-orders/orders.feature
acquisitions/src/test/java/org/folio/CrossModulesApiTest.java
acquisitions/src/test/java/org/folio/OrdersApiTest.java

[MODORDERS-1308](https://folio-org.atlassian.net/browse/MODORDERS-1308) - Order expended amount is not converting the invoice currency
- Moved `check-order-total-fields-calculated-correctly.feature` from mod-orders to cross-module tests.
- Adjusted user/header usage
- Added a test to check order totals when an invoice uses a different currency than the system currency
[mod-orders PR](https://github.com/folio-org/mod-orders/pull/1130)

[MODORDERS-1308] Test order totals with different invoice currency

---

testrail-integration/src/main/java/org/folio/test/TestBaseEureka.java

Fix reference to class in TestBaseEureka for correct prefixing of team names
In the previous state, the class retrieved was the FeatureRunner class. This class does not have the annotation for the team names. The code now retrieves the TestBaseEureka class now.

Fix reference to class in TestBaseEureka for correct prefixing of team names

---

acquisitions/src/main/resources/thunderjet/consortia/features/open-orders-in-member-tenant.feature
acquisitions/src/main/resources/thunderjet/consortia/reusable/createInstance.feature

[MODORDERS-1310](https://folio-org.atlassian.net/browse/MODORDERS-1310) - Make Local order matching ECS aware such that shadows will be created for shared instances before local instances will be created.
Fixes to the test.

[MODORDERS-1310] Test fixes

---

data-import/src/main/resources/folijet/data-import/features/marc-records/data-import-set-for-deletion.feature
data-import/src/main/resources/folijet/data-import/global/import-marc-json-and-verify.feature
data-import/src/main/resources/folijet/data-import/global/import-record.feature
data-import/src/main/resources/folijet/data-import/global/setup-marc-to-marc-update-profile.feature
data-import/src/main/resources/folijet/data-import/samples/marcBib.mrc.json
data-import/src/main/resources/folijet/data-import/samples/mrc-files/marcBibDeletedLeader.mrc.json
data-import/src/test/java/test/java/WriteData.java

Covering test for MODSOURCE-898
1. Create MARC instance using default job profile for creating instance
2. Mark instance as deleted using DELETE /inventory/instances/{id}/mark-deleted
3. Export MARC instance using data export
4. Create MARC update job profile (MARC-MARC matching with 999ff$i)
5. Update exported MARC file
6. Run import with created job profile and updated file

MODSOURCE-898 Update deleted instances with MARC-MARC matching

---

acquisitions/src/main/resources/thunderjet/edge-orders/features/gobi.feature

- Fix broken Edge-orders GOBI tests
- Change base URL from Edge (external) to Kong (internal)
- Test on Rancher edev cluster (thunderjet-2nd namespace):

Fix Edge-Orders GOBI Tests

---

acquisitions/src/main/resources/global/configuration.feature
acquisitions/src/main/resources/thunderjet/consortia/features/open-orders-in-member-tenant.feature
acquisitions/src/main/resources/thunderjet/cross-modules/init-cross-modules.feature
acquisitions/src/main/resources/thunderjet/edge-orders/init-edge-orders.feature
acquisitions/src/main/resources/thunderjet/mod-data-export-spring/init-data-export-spring.feature
acquisitions/src/main/resources/thunderjet/mod-ebsconet/init-ebsconet.feature
acquisitions/src/main/resources/thunderjet/mod-finance/init-finance.feature
acquisitions/src/main/resources/thunderjet/mod-mosaic/init-mosaic.feature
acquisitions/src/main/resources/thunderjet/mod-orders/init-orders.feature

- <https://folio-org.atlassian.net/browse/MODORDERS-1214>
- Add missing permissions
- `init-edge-orders.feature`
- `init-data-export-spring.feature`
- `init-ebsconet.feature`
- `init-finance.feature`
- `init-mosaic.feature`
- Change Accept header in `open-orders-in-member-tenant.feature` from `application/json` to `*/*`

[MODORDERS-1214-2]. Add missing settings permissions

---

acquisitions/src/main/resources/thunderjet/mod-orders/features/open-and-unopen-order.feature
acquisitions/src/main/resources/thunderjet/mod-orders/features/poline-change-instance-connection-with-holdings-items.feature

[[MODORDERS-1343] Do not delete used holdings during un-opening the order](https://folio-org.atlassian.net/browse/MODORDERS-1343)
Add new scenario to verify presence of a holding after unopening order

[MODORDERS-1343] Do not delete used holdings during un-opening the order

---

mod-dcb/src/main/resources/karate-config.js

Fix the integration test startup issue using karate.properties instead of direct mapping
- Fix configuration in `karate-config.js`

MODDCB-231: Make mockServerUrl optional with default value

---

mod-data-export/src/test/resources/firebird/dataexport/features/export-deleted-authorities.feature

[FAT-21678](https://folio-org.atlassian.net/browse/FAT-21678) - Karate test fail: [firebird/data-export] ModDataExportApiTest {16} firebird/dataexport/features/export-deleted-authorities.feature
Fix data-export authority deleted
Add pauses before and after authority deletion.

FAT-21678 - Karate test fail: [firebird/data-export] ModDataExportApiTest {16} firebird/dataexport/features/export-deleted-authorities.feature

---

mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/marc-bib-update.feature
mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/quick-marc-authority-records.feature
mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/quick-marc-bib-records.feature
mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/quick-marc-handle-literal-dollar.feature
mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/quick-marc-holdings-records.feature
mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/quick-marc-linking-records.feature
mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/quick-marc-tags-order.feature
mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/quick-marc-update-linked-authority-records.feature
mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/setup/samples/parsed-records/authority.json
mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/setup/samples/parsed-records/bib-record.json
mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/setup/samples/parsed-records/holdings.json
mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/setup/samples/parsed-records/marc-authority-record.json
mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/setup/samples/parsed-records/marc-bib-record.json
mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/setup/samples/parsed-records/marc-holding-record.json
mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/setup/setup.feature

[FAT-21887](https://folio-org.atlassian.net/browse/FAT-21887)
[FAT-21888](https://folio-org.atlassian.net/browse/FAT-21888)
Karate test fail: QuickMarcApiTest
- Runs the login feature before every scenario in the feature files where an `UnauthorizedException` (401 Unauthorized HTTP status) occurs due to API call retries and timeouts between retries.
- Remove the non-existent `relatedRecordVersion` field from the MARC records.
- Fix the API request body in the `quick-marc-update-linked-authority-records.feature` file.
https://jenkins.ci.folio.org/job/folioTestingTools/job/runKarateTests/448/cucumber-html-reports/overview-features.html

[FAT-21887] fix the mod-quick-marc tests
